In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!cp /content/drive/MyDrive/image/images.zip -d /content/images.zip
!unzip -q images.zip

In [3]:
!rm /content/images.zip

In [4]:
import os
A=os.listdir('/content')
A

['.config', 'drive', 'images', 'sample_data']

In [5]:
import pandas as pd
import glob
import os
import numpy as np
import matplotlib.pyplot as plt
s='/content/images/*'
path=glob.glob(s)
import re
def sorted_alphanumeric(data):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ]
    return sorted(data, key=alphanum_key)

path1=sorted_alphanumeric(path)
path1 = [item.replace('p','_') for item in path1]
data=pd.read_excel('/content/drive/MyDrive/image/data_c.xlsx')
data
len(path1)
print(path1)
type(path1)
path1=np.array(path1)
path1.shape
path1[0]

['/content/images/C_1_1_1.raw', '/content/images/C_1_1_16.raw', '/content/images/C_1_1_31.raw', '/content/images/C_1_1_46.raw', '/content/images/C_1_1_61.raw', '/content/images/C_1_1_76.raw', '/content/images/C_1_1_91.raw', '/content/images/C_1_1_106.raw', '/content/images/C_1_1_121.raw', '/content/images/C_1_1_136.raw', '/content/images/C_1_1_151.raw', '/content/images/C_1_1_166.raw', '/content/images/C_1_1_181.raw', '/content/images/C_1_1_196.raw', '/content/images/C_1_1_211.raw', '/content/images/C_1_1_226.raw', '/content/images/C_1_1_241.raw', '/content/images/C_1_1_256.raw', '/content/images/C_1_1_271.raw', '/content/images/C_1_1_286.raw', '/content/images/C_1_1_301.raw', '/content/images/C_1_16_1.raw', '/content/images/C_1_16_16.raw', '/content/images/C_1_16_31.raw', '/content/images/C_1_16_46.raw', '/content/images/C_1_16_61.raw', '/content/images/C_1_16_76.raw', '/content/images/C_1_16_91.raw', '/content/images/C_1_16_106.raw', '/content/images/C_1_16_121.raw', '/content/images/C_1_16_136.raw', '/content/images/C_1_16_151.raw', '/content/images/C_1_16_166.raw', '/content/images/C_1_16_181.raw', '/content/images/C_1_16_196.raw', '/content/images/C_1_16_211.raw', '/content/images/C_1_16_226.raw', '/content/images/C_1_16_241.raw', '/content/images/C_1_16_256.raw', '/content/images/C_1_16_271.raw', '/content/images/C_1_16_286.raw', '/content/images/C_1_16_301.raw', '/content/images/C_1_31_1.raw', '/content/images/C_1_31_16.raw', '/content/images/C_1_31_31.raw', '/content/images/C_1_31_46.raw', '/content/images/C_1_31_61.raw', '/content/images/C_1_31_76.raw', '/content/images/C_1_31_91.raw', '/content/images/C_1_31_106.raw', '/content/images/C_1_31_121.raw', '/content/images/C_1_31_136.raw', '/content/images/C_1_31_151.raw', '/content/images/C_1_31_166.raw', '/content/images/C_1_31_181.raw', '/content/images/C_1_31_196.raw', '/content/images/C_1_31_211.raw', '/content/images/C_1_31_226.raw', '/content/images/C_1_31_241.raw', '/content/images/C_1_31_256.raw', '/content/images/C_1_31_271.raw', '/content/images/C_1_31_286.raw', '/content/images/C_1_31_301.raw', '/content/images/C_1_46_1.raw', '/content/images/C_1_46_16.raw', '/content/images/C_1_46_31.raw', '/content/images/C_1_46_46.raw', '/content/images/C_1_46_61.raw', '/content/images/C_1_46_76.raw', '/content/images/C_1_46_91.raw', '/content/images/C_1_46_106.raw', '/content/images/C_1_46_121.raw', '/content/images/C_1_46_136.raw', '/content/images/C_1_46_151.raw', '/content/images/C_1_46_166.raw', '/content/images/C_1_46_181.raw', '/content/images/C_1_46_196.raw', '/content/images/C_1_46_211.raw', '/content/images/C_1_46_226.raw', '/content/images/C_1_46_241.raw', '/content/images/C_1_46_256.raw', '/content/images/C_1_46_271.raw', '/content/images/C_1_46_286.raw', '/content/images/C_1_46_301.raw', '/content/images/C_1_61_1.raw', '/content/images/C_1_61_16.raw', '/content/images/C_1_61_31.raw', '/content/images/C_1_61_46.raw', '/content/images/C_1_61_61.raw', '/content/images/C_1_61_76.raw', '/content/images/C_1_61_91.raw', '/content/images/C_1_61_106.raw', '/content/images/C_1_61_121.raw', '/content/images/C_1_61_136.raw', '/content/images/C_1_61_151.raw', '/content/images/C_1_61_166.raw', '/content/images/C_1_61_181.raw', '/content/images/C_1_61_196.raw', '/content/images/C_1_61_211.raw', '/content/images/C_1_61_226.raw', '/content/images/C_1_61_241.raw', '/content/images/C_1_61_256.raw', '/content/images/C_1_61_271.raw', '/content/images/C_1_61_286.raw', '/content/images/C_1_61_301.raw', '/content/images/C_1_76_1.raw', '/content/images/C_1_76_16.raw', '/content/images/C_1_76_31.raw', '/content/images/C_1_76_46.raw', '/content/images/C_1_76_61.raw', '/content/images/C_1_76_76.raw', '/content/images/C_1_76_91.raw', '/content/images/C_1_76_106.raw', '/content/images/C_1_76_121.raw', '/content/images/C_1_76_136.raw', '/content/images/C_1_76_151.raw', '/content/images/C_1_76_166.raw', '/content/images/C_1_76_181.raw', '/content/images/C_1_76_196.raw', '/content/images/C_1_76_211.raw', '/content/images/C_1_76_226.raw', '/content/images/C_1_76_241.raw', '/content/images/C_1_76_256.raw', '/content/images/C_1_76_271.raw', '/content/images/C_1_76_286.raw', '/content/images/C_1_76_301.raw', '/content/images/C_1_91_1.raw', '/content/images/C_1_91_16.raw', '/content/images/C_1_91_31.raw', '/content/images/C_1_91_46.raw', '/content/images/C_1_91_61.raw', '/content/images/C_1_91_76.raw', '/content/images/C_1_91_91.raw', '/content/images/C_1_91_106.raw', '/content/images/C_1_91_121.raw', '/content/images/C_1_91_136.raw', '/content/images/C_1_91_151.raw', '/content/images/C_1_91_166.raw', '/content/images/C_1_91_181.raw', '/content/images/C_1_91_196.raw', '/content/images/C_1_91_211.raw', '/content/images/C_1_91_226.raw', '/content/images/C_1_91_241.raw', '/content/images/C_1_91_256.raw', '/content/images/C_1_91_271.raw', '/content/images/C_1_91_286.raw', '/content/images/C_1_91_301.raw', '/content/images/C_1_106_1.raw', '/content/images/C_1_106_16.raw', '/content/images/C_1_106_31.raw', '/content/images/C_1_106_46.raw', '/content/images/C_1_106_61.raw', '/content/images/C_1_106_76.raw', '/content/images/C_1_106_91.raw', '/content/images/C_1_106_106.raw', '/content/images/C_1_106_121.raw', '/content/images/C_1_106_136.raw', '/content/images/C_1_106_151.raw', '/content/images/C_1_106_166.raw', '/content/images/C_1_106_181.raw', '/content/images/C_1_106_196.raw', '/content/images/C_1_106_211.raw', '/content/images/C_1_106_226.raw', '/content/images/C_1_106_241.raw', '/content/images/C_1_106_256.raw', '/content/images/C_1_106_271.raw', '/content/images/C_1_106_286.raw', '/content/images/C_1_106_301.raw', '/content/images/C_1_121_1.raw', '/content/images/C_1_121_16.raw', '/content/images/C_1_121_31.raw', '/content/images/C_1_121_46.raw', '/content/images/C_1_121_61.raw', '/content/images/C_1_121_76.raw', '/content/images/C_1_121_91.raw', '/content/images/C_1_121_106.raw', '/content/images/C_1_121_121.raw', '/content/images/C_1_121_136.raw', '/content/images/C_1_121_151.raw', '/content/images/C_1_121_166.raw', '/content/images/C_1_121_181.raw', '/content/images/C_1_121_196.raw', '/content/images/C_1_121_211.raw', '/content/images/C_1_121_226.raw', '/content/images/C_1_121_241.raw', '/content/images/C_1_121_256.raw', '/content/images/C_1_121_271.raw', '/content/images/C_1_121_286.raw', '/content/images/C_1_121_301.raw', '/content/images/C_1_136_1.raw', '/content/images/C_1_136_16.raw', '/content/images/C_1_136_31.raw', '/content/images/C_1_136_46.raw', '/content/images/C_1_136_61.raw', '/content/images/C_1_136_76.raw', '/content/images/C_1_136_91.raw', '/content/images/C_1_136_106.raw', '/content/images/C_1_136_121.raw', '/content/images/C_1_136_136.raw', '/content/images/C_1_136_151.raw', '/content/images/C_1_136_166.raw', '/content/images/C_1_136_181.raw', '/content/images/C_1_136_196.raw', '/content/images/C_1_136_211.raw', '/content/images/C_1_136_226.raw', '/content/images/C_1_136_241.raw', '/content/images/C_1_136_256.raw', '/content/images/C_1_136_271.raw', '/content/images/C_1_136_286.raw', '/content/images/C_1_136_301.raw', '/content/images/C_1_151_1.raw', '/content/images/C_1_151_16.raw', '/content/images/C_1_151_31.raw', '/content/images/C_1_151_46.raw', '/content/images/C_1_151_61.raw', '/content/images/C_1_151_76.raw', '/content/images/C_1_151_91.raw', '/content/images/C_1_151_106.raw', '/content/images/C_1_151_121.raw', '/content/images/C_1_151_136.raw', '/content/images/C_1_151_151.raw', '/content/images/C_1_151_166.raw', '/content/images/C_1_151_181.raw', '/content/images/C_1_151_196.raw', '/content/images/C_1_151_211.raw', '/content/images/C_1_151_226.raw', '/content/images/C_1_151_241.raw', '/content/images/C_1_151_256.raw', '/content/images/C_1_151_271.raw', '/content/images/C_1_151_286.raw', '/content/images/C_1_151_301.raw', '/content/images/C_1_166_1.raw', '/content/images/C_1_166_16.raw', '/content/images/C_1_166_31.raw', '/content/images/C_1_166_46.raw', '/content/images/C_1_166_61.raw', '/content/images/C_1_166_76.raw', '/content/images/C_1_166_91.raw', '/content/images/C_1_166_106.raw', '/content/images/C_1_166_121.raw', '/content/images/C_1_166_136.raw', '/content/images/C_1_166_151.raw', '/content/images/C_1_166_166.raw', '/content/images/C_1_166_181.raw', '/content/images/C_1_166_196.raw', '/content/images/C_1_166_211.raw', '/content/images/C_1_166_226.raw', '/content/images/C_1_166_241.raw', '/content/images/C_1_166_256.raw', '/content/images/C_1_166_271.raw', '/content/images/C_1_166_286.raw', '/content/images/C_1_166_301.raw', '/content/images/C_1_181_1.raw', '/content/images/C_1_181_16.raw', '/content/images/C_1_181_31.raw', '/content/images/C_1_181_46.raw', '/content/images/C_1_181_61.raw', '/content/images/C_1_181_76.raw', '/content/images/C_1_181_91.raw', '/content/images/C_1_181_106.raw', '/content/images/C_1_181_121.raw', '/content/images/C_1_181_136.raw', '/content/images/C_1_181_151.raw', '/content/images/C_1_181_166.raw', '/content/images/C_1_181_181.raw', '/content/images/C_1_181_196.raw', '/content/images/C_1_181_211.raw', '/content/images/C_1_181_226.raw', '/content/images/C_1_181_241.raw', '/content/images/C_1_181_256.raw', '/content/images/C_1_181_271.raw', '/content/images/C_1_181_286.raw', '/content/images/C_1_181_301.raw', '/content/images/C_1_196_1.raw', '/content/images/C_1_196_16.raw', '/content/images/C_1_196_31.raw', '/content/images/C_1_196_46.raw', '/content/images/C_1_196_61.raw', '/content/images/C_1_196_76.raw', '/content/images/C_1_196_91.raw', '/content/images/C_1_196_106.raw', '/content/images/C_1_196_121.raw', '/content/images/C_1_196_136.raw', '/content/images/C_1_196_151.raw', '/content/images/C_1_196_166.raw', '/content/images/C_1_196_181.raw', '/content/images/C_1_196_196.raw', '/content/images/C_1_196_211.raw', '/content/images/C_1_196_226.raw', '/content/images/C_1_196_241.raw', '/content/images/C_1_196_256.raw', '/content/images/C_1_196_271.raw', '/content/images/C_1_196_286.raw', '/content/images/C_1_196_301.raw', '/content/images/C_1_211_1.raw', '/content/images/C_1_211_16.raw', '/content/images/C_1_211_31.raw', '/content/images/C_1_211_46.raw', '/content/images/C_1_211_61.raw', '/content/images/C_1_211_76.raw', '/content/images/C_1_211_91.raw', '/content/images/C_1_211_106.raw', '/content/images/C_1_211_121.raw', '/content/images/C_1_211_136.raw', '/content/images/C_1_211_151.raw', '/content/images/C_1_211_166.raw', '/content/images/C_1_211_181.raw', '/content/images/C_1_211_196.raw', '/content/images/C_1_211_211.raw', '/content/images/C_1_211_226.raw', '/content/images/C_1_211_241.raw', '/content/images/C_1_211_256.raw', '/content/images/C_1_211_271.raw', '/content/images/C_1_211_286.raw', '/content/images/C_1_211_301.raw', '/content/images/C_1_226_1.raw', '/content/images/C_1_226_16.raw', '/content/images/C_1_226_31.raw', '/content/images/C_1_226_46.raw', '/content/images/C_1_226_61.raw', '/content/images/C_1_226_76.raw', '/content/images/C_1_226_91.raw', '/content/images/C_1_226_106.raw', '/content/images/C_1_226_121.raw', '/content/images/C_1_226_136.raw', '/content/images/C_1_226_151.raw', '/content/images/C_1_226_166.raw', '/content/images/C_1_226_181.raw', '/content/images/C_1_226_196.raw', '/content/images/C_1_226_211.raw', '/content/images/C_1_226_226.raw', '/content/images/C_1_226_241.raw', '/content/images/C_1_226_256.raw', '/content/images/C_1_226_271.raw', '/content/images/C_1_226_286.raw', '/content/images/C_1_226_301.raw', '/content/images/C_1_241_1.raw', '/content/images/C_1_241_16.raw', '/content/images/C_1_241_31.raw', '/content/images/C_1_241_46.raw', '/content/images/C_1_241_61.raw', '/content/images/C_1_241_76.raw', '/content/images/C_1_241_91.raw', '/content/images/C_1_241_106.raw', '/content/images/C_1_241_121.raw', '/content/images/C_1_241_136.raw', '/content/images/C_1_241_151.raw', '/content/images/C_1_241_166.raw', '/content/images/C_1_241_181.raw', '/content/images/C_1_241_196.raw', '/content/images/C_1_241_211.raw', '/content/images/C_1_241_226.raw', '/content/images/C_1_241_241.raw', '/content/images/C_1_241_256.raw', '/content/images/C_1_241_271.raw', '/content/images/C_1_241_286.raw', '/content/images/C_1_241_301.raw', '/content/images/C_1_256_1.raw', '/content/images/C_1_256_16.raw', '/content/images/C_1_256_31.raw', '/content/images/C_1_256_46.raw', '/content/images/C_1_256_61.raw', '/content/images/C_1_256_76.raw', '/content/images/C_1_256_91.raw', '/content/images/C_1_256_106.raw', '/content/images/C_1_256_121.raw', '/content/images/C_1_256_136.raw', '/content/images/C_1_256_151.raw', '/content/images/C_1_256_166.raw', '/content/images/C_1_256_181.raw', '/content/images/C_1_256_196.raw', '/content/images/C_1_256_211.raw', '/content/images/C_1_256_226.raw', '/content/images/C_1_256_241.raw', '/content/images/C_1_256_256.raw', '/content/images/C_1_256_271.raw', '/content/images/C_1_256_286.raw', '/content/images/C_1_256_301.raw', '/content/images/C_1_271_1.raw', '/content/images/C_1_271_16.raw', '/content/images/C_1_271_31.raw', '/content/images/C_1_271_46.raw', '/content/images/C_1_271_61.raw', '/content/images/C_1_271_76.raw', '/content/images/C_1_271_91.raw', '/content/images/C_1_271_106.raw', '/content/images/C_1_271_121.raw', '/content/images/C_1_271_136.raw', '/content/images/C_1_271_151.raw', '/content/images/C_1_271_166.raw', '/content/images/C_1_271_181.raw', '/content/images/C_1_271_196.raw', '/content/images/C_1_271_211.raw', '/content/images/C_1_271_226.raw', '/content/images/C_1_271_241.raw', '/content/images/C_1_271_256.raw', '/content/images/C_1_271_271.raw', '/content/images/C_1_271_286.raw', '/content/images/C_1_271_301.raw', '/content/images/C_1_286_1.raw', '/content/images/C_1_286_16.raw', '/content/images/C_1_286_31.raw', '/content/images/C_1_286_46.raw', '/content/images/C_1_286_61.raw', '/content/images/C_1_286_76.raw', '/content/images/C_1_286_91.raw', '/content/images/C_1_286_106.raw', '/content/images/C_1_286_121.raw', '/content/images/C_1_286_136.raw', '/content/images/C_1_286_151.raw', '/content/images/C_1_286_166.raw', '/content/images/C_1_286_181.raw', '/content/images/C_1_286_196.raw', '/content/images/C_1_286_211.raw', '/content/images/C_1_286_226.raw', '/content/images/C_1_286_241.raw', '/content/images/C_1_286_256.raw', '/content/images/C_1_286_271.raw', '/content/images/C_1_286_286.raw', '/content/images/C_1_286_301.raw', '/content/images/C_1_301_1.raw', '/content/images/C_1_301_16.raw', '/content/images/C_1_301_31.raw', '/content/images/C_1_301_46.raw', '/content/images/C_1_301_61.raw', '/content/images/C_1_301_76.raw', '/content/images/C_1_301_91.raw', '/content/images/C_1_301_106.raw', '/content/images/C_1_301_121.raw', '/content/images/C_1_301_136.raw', '/content/images/C_1_301_151.raw', '/content/images/C_1_301_166.raw', '/content/images/C_1_301_181.raw', '/content/images/C_1_301_196.raw', '/content/images/C_1_301_211.raw', '/content/images/C_1_301_226.raw', '/content/images/C_1_301_241.raw', '/content/images/C_1_301_256.raw', '/content/images/C_1_301_271.raw', '/content/images/C_1_301_286.raw', '/content/images/C_1_301_301.raw', '/content/images/C_16_1_1.raw', '/content/images/C_16_1_16.raw', '/content/images/C_16_1_31.raw', '/content/images/C_16_1_46.raw', '/content/images/C_16_1_61.raw', '/content/images/C_16_1_76.raw', '/content/images/C_16_1_91.raw', '/content/images/C_16_1_106.raw', '/content/images/C_16_1_121.raw', '/content/images/C_16_1_136.raw', '/content/images/C_16_1_151.raw', '/content/images/C_16_1_166.raw', '/content/images/C_16_1_181.raw', '/content/images/C_16_1_196.raw', '/content/images/C_16_1_211.raw', '/content/images/C_16_1_226.raw', '/content/images/C_16_1_241.raw', '/content/images/C_16_1_256.raw', '/content/images/C_16_1_271.raw', '/content/images/C_16_1_286.raw', '/content/images/C_16_1_301.raw', '/content/images/C_16_16_1.raw', '/content/images/C_16_16_16.raw', '/content/images/C_16_16_31.raw', '/content/images/C_16_16_46.raw', '/content/images/C_16_16_61.raw', '/content/images/C_16_16_76.raw', '/content/images/C_16_16_91.raw', '/content/images/C_16_16_106.raw', '/content/images/C_16_16_121.raw', '/content/images/C_16_16_136.raw', '/content/images/C_16_16_151.raw', '/content/images/C_16_16_166.raw', '/content/images/C_16_16_181.raw', '/content/images/C_16_16_196.raw', '/content/images/C_16_16_211.raw', '/content/images/C_16_16_226.raw', '/content/images/C_16_16_241.raw', '/content/images/C_16_16_256.raw', '/content/images/C_16_16_271.raw', '/content/images/C_16_16_286.raw', '/content/images/C_16_16_301.raw', '/content/images/C_16_31_1.raw', '/content/images/C_16_31_16.raw', '/content/images/C_16_31_31.raw', '/content/images/C_16_31_46.raw', '/content/images/C_16_31_61.raw', '/content/images/C_16_31_76.raw', '/content/images/C_16_31_91.raw', '/content/images/C_16_31_106.raw', '/content/images/C_16_31_121.raw', '/content/images/C_16_31_136.raw', '/content/images/C_16_31_151.raw', '/content/images/C_16_31_166.raw', '/content/images/C_16_31_181.raw', '/content/images/C_16_31_196.raw', '/content/images/C_16_31_211.raw', '/content/images/C_16_31_226.raw', '/content/images/C_16_31_241.raw', '/content/images/C_16_31_256.raw', '/content/images/C_16_31_271.raw', '/content/images/C_16_31_286.raw', '/content/images/C_16_31_301.raw', '/content/images/C_16_46_1.raw', '/content/images/C_16_46_16.raw', '/content/images/C_16_46_31.raw', '/content/images/C_16_46_46.raw', '/content/images/C_16_46_61.raw', '/content/images/C_16_46_76.raw', '/content/images/C_16_46_91.raw', '/content/images/C_16_46_106.raw', '/content/images/C_16_46_121.raw', '/content/images/C_16_46_136.raw', '/content/images/C_16_46_151.raw', '/content/images/C_16_46_166.raw', '/content/images/C_16_46_181.raw', '/content/images/C_16_46_196.raw', '/content/images/C_16_46_211.raw', '/content/images/C_16_46_226.raw', '/content/images/C_16_46_241.raw', '/content/images/C_16_46_256.raw', '/content/images/C_16_46_271.raw', '/content/images/C_16_46_286.raw', '/content/images/C_16_46_301.raw', '/content/images/C_16_61_1.raw', '/content/images/C_16_61_16.raw', '/content/images/C_16_61_31.raw', '/content/images/C_16_61_46.raw', '/content/images/C_16_61_61.raw', '/content/images/C_16_61_76.raw', '/content/images/C_16_61_91.raw', '/content/images/C_16_61_106.raw', '/content/images/C_16_61_121.raw', '/content/images/C_16_61_136.raw', '/content/images/C_16_61_151.raw', '/content/images/C_16_61_166.raw', '/content/images/C_16_61_181.raw', '/content/images/C_16_61_196.raw', '/content/images/C_16_61_211.raw', '/content/images/C_16_61_226.raw', '/content/images/C_16_61_241.raw', '/content/images/C_16_61_256.raw', '/content/images/C_16_61_271.raw', '/content/images/C_16_61_286.raw', '/content/images/C_16_61_301.raw', '/content/images/C_16_76_1.raw', '/content/images/C_16_76_16.raw', '/content/images/C_16_76_31.raw', '/content/images/C_16_76_46.raw', '/content/images/C_16_76_61.raw', '/content/images/C_16_76_76.raw', '/content/images/C_16_76_91.raw', '/content/images/C_16_76_106.raw', '/content/images/C_16_76_121.raw', '/content/images/C_16_76_136.raw', '/content/images/C_16_76_151.raw', '/content/images/C_16_76_166.raw', '/content/images/C_16_76_181.raw', '/content/images/C_16_76_196.raw', '/content/images/C_16_76_211.raw', '/content/images/C_16_76_226.raw', '/content/images/C_16_76_241.raw', '/content/images/C_16_76_256.raw', '/content/images/C_16_76_271.raw', '/content/images/C_16_76_286.raw', '/content/images/C_16_76_301.raw', '/content/images/C_16_91_1.raw', '/content/images/C_16_91_16.raw', '/content/images/C_16_91_31.raw', '/content/images/C_16_91_46.raw', '/content/images/C_16_91_61.raw', '/content/images/C_16_91_76.raw', '/content/images/C_16_91_91.raw', '/content/images/C_16_91_106.raw', '/content/images/C_16_91_121.raw', '/content/images/C_16_91_136.raw', '/content/images/C_16_91_151.raw', '/content/images/C_16_91_166.raw', '/content/images/C_16_91_181.raw', '/content/images/C_16_91_196.raw', '/content/images/C_16_91_211.raw', '/content/images/C_16_91_226.raw', '/conte

'/content/images/C_1_1_1.raw'

In [6]:
path1=np.array(path1)
data=np.array(data)
data
len(data)

9261

In [7]:
df=pd.DataFrame({'imgpath':path1,'Porosity':data[:,0],'throat radius':data[:,1],'pore radius':data[:,2],'pore_connection_number':data[:,3],'pore shape factor':data[:,4]})

In [8]:
df

,imgpath,Porosity,throat radius,pore radius,pore_connection_number,pore shape factor
0,/content/images/C_1_1_1.raw,0.200016,0.000009,0.000013,1.92857,0.037024
1,/content/images/C_1_1_16.raw,0.211707,0.000008,0.000012,2.25000,0.036642
2,/content/images/C_1_1_31.raw,0.233293,0.000008,0.000013,1.96875,0.038013
3,/content/images/C_1_1_46.raw,0.264409,0.000009,0.000014,2.18182,0.039828
4,/content/images/C_1_1_61.raw,0.277295,0.000009,0.000014,2.27273,0.038306
...,...,...,...,...,...,...
9256,/content/images/C_301_301_241.raw,0.136927,0.000008,0.000013,2.35443,0.036514
9257,/content/images/C_301_301_256.raw,0.136191,0.000008,0.000013,2.12658,0.036236
9258,/content/images/C_301_301_271.raw,0.147490,0.000008,0.000014,2.17722,0.033896
9259,/content/images/C_301_301_286.raw,0.161413,0.000008,0.000013,2.18987,0.035108
9260,/content/images/C_301_301_301.raw,0.179779,0.000009,0.000015,1.97468,0.029493

In [9]:
df_new=df[df['Porosity'] <0.35 ]
df_new.shape
df_new

,imgpath,Porosity,throat radius,pore radius,pore_connection_number,pore shape factor
0,/content/images/C_1_1_1.raw,0.200016,0.000009,0.000013,1.92857,0.037024
1,/content/images/C_1_1_16.raw,0.211707,0.000008,0.000012,2.25000,0.036642
2,/content/images/C_1_1_31.raw,0.233293,0.000008,0.000013,1.96875,0.038013
3,/content/images/C_1_1_46.raw,0.264409,0.000009,0.000014,2.18182,0.039828
4,/content/images/C_1_1_61.raw,0.277295,0.000009,0.000014,2.27273,0.038306
...,...,...,...,...,...,...
9256,/content/images/C_301_301_241.raw,0.136927,0.000008,0.000013,2.35443,0.036514
9257,/content/images/C_301_301_256.raw,0.136191,0.000008,0.000013,2.12658,0.036236
9258,/content/images/C_301_301_271.raw,0.147490,0.000008,0.000014,2.17722,0.033896
9259,/content/images/C_301_301_286.raw,0.161413,0.000008,0.000013,2.18987,0.035108
9260,/content/images/C_301_301_301.raw,0.179779,0.000009,0.000015,1.97468,0.029493

In [10]:
from sklearn.preprocessing import StandardScaler
import numpy as np
data2=np.array(df_new)
scaler = StandardScaler()
data1= scaler.fit_transform(data2[:,1:])
print(data1)
print(type(data1))
data1.shape

[[ 0.11455659  0.58493673  0.28969785 -0.82815281 -0.22691552]
 [ 0.27058416 -0.34306756 -0.15901557 -0.0260099  -0.34020621]
 [ 0.55866997 -0.05166937  0.52032542 -0.72788183  0.06680977]
 ...
 [-0.58645309 -0.39830083  0.62718527 -0.20763563 -1.1561657 ]
 [-0.40063734  0.06434896  0.10229779 -0.17606699 -0.79601231]
 [-0.15552552  0.3087704   1.25751387 -0.71308325 -2.46407987]]
<class 'numpy.ndarray'>

(7921, 5)

In [11]:
data2

array([['/content/images/C_1_1_1.raw', 0.200016, 9.0343e-06,
        1.3046116e-05, 1.92857, 0.037023878929],
       ['/content/images/C_1_1_16.raw', 0.211707, 7.7305e-06,
        1.2303802e-05, 2.25, 0.03664248875],
       ['/content/images/C_1_1_31.raw', 0.233293, 8.1399e-06,
        1.3427647e-05, 1.96875, 0.0380126975],
       ...,
       ['/content/images/C_301_301_271.raw', 0.14749, 7.6529e-06,
        1.3604427e-05, 2.17722, 0.033895582308],
       ['/content/images/C_301_301_286.raw', 0.161413, 8.3029e-06,
        1.2736097e-05, 2.18987, 0.035108029333],
       ['/content/images/C_301_301_301.raw', 0.179779, 8.6463e-06,
        1.464719e-05, 1.97468, 0.0294925232]], dtype=object)

In [12]:
df=pd.DataFrame({'imgpath':df_new['imgpath'],'Porosity':data1[:,0],'throat radius':data1[:,1],'pore radius':data1[:,2],'pore_connection_number':data1[:,3],'pore shape factor':data1[:,4]})
df

,imgpath,Porosity,throat radius,pore radius,pore_connection_number,pore shape factor
0,/content/images/C_1_1_1.raw,0.114557,0.584937,0.289698,-0.828153,-0.226916
1,/content/images/C_1_1_16.raw,0.270584,-0.343068,-0.159016,-0.026010,-0.340206
2,/content/images/C_1_1_31.raw,0.558670,-0.051669,0.520325,-0.727882,0.066810
3,/content/images/C_1_1_46.raw,0.973943,0.745227,0.630089,-0.196156,0.606040
4,/content/images/C_1_1_61.raw,1.145919,0.514543,1.057970,0.030714,0.154056
...,...,...,...,...,...,...
9256,/content/images/C_301_301_241.raw,-0.727426,-0.487201,0.223571,0.234600,-0.378288
9257,/content/images/C_301_301_256.raw,-0.737249,-0.264275,0.454180,-0.334010,-0.460952
9258,/content/images/C_301_301_271.raw,-0.586453,-0.398301,0.627185,-0.207636,-1.156166
9259,/content/images/C_301_301_286.raw,-0.400637,0.064349,0.102298,-0.176067,-0.796012
9260,/content/images/C_301_301_301.raw,-0.155526,0.308770,1.257514,-0.713083,-2.464080

In [13]:
data_t_general=df.sample(frac=0.9,random_state=1)
df_valid=data_t_general.sample(frac=0.15,random_state=2)
df_train=data_t_general.loc[~data_t_general.index.isin(df_valid.index)]
df_test =df.loc[~df.index.isin(data_t_general.index)]
len(df_train)

6060

In [14]:
def Data_generator(df, batch_size, augment=False):

    while True:

            for start in range(0, df.shape[0], batch_size):
                x_batch_img = []
                y_batch=[]
                end = min(start + batch_size, df.shape[0])

                for idd in range(start,end):
                    img = open(np.array(df.imgpath)[idd],'rb').read()
                    img_1=np.frombuffer(img,dtype=np.uint8)
                    img_1=img_1.reshape(100,100,100,1)
                    Porosity=np.array(df.Porosity)[idd]
                    throat_radius=np.array(df['throat radius'])[idd]
                    pore_radius=np.array(df['pore radius'])[idd]
                    pore_connection_number=np.array(df.pore_connection_number)[idd]
                    pore_shape_factor=np.array(df['pore shape factor'])[idd]
                    y_1=np.concatenate((Porosity, throat_radius,pore_radius,pore_connection_number, pore_shape_factor),axis=None)
                    y=np.array([y_1])
                    x_batch_img.append(img_1)
                    y_batch.append(y)


                x_batch_img = np.array(x_batch_img)
                y_batch= np.array(y_batch)
                y_batch=y_batch.reshape(-1,5)
              #y_batch = to_categorical(y_batch,5)
                yield x_batch_img , y_batch

In [15]:
def Data_predict_generator(df, batch_size, augment=False):

    while True:

            for start in range(0, df.shape[0], batch_size):
                x_batch_img_2 = []

                end = min(start + batch_size, df.shape[0])

                for idd in range(start,end):
                    img = open(np.array(df.imgpath)[idd],'rb').read()
                    img_1=np.frombuffer(img,dtype=np.uint8)
                    img_1=img_1.reshape(100,100,100,1)
                    x_batch_img_2.append(img_1)



                x_batch_img_2 = np.array(x_batch_img_2)

              #y_batch = to_categorical(y_batch,5)
                yield x_batch_img_2

In [16]:
batch_size=10
train_gen= Data_generator(df_train,batch_size)
valid_gen= Data_generator(df_valid,batch_size)
train_gen_pre=Data_predict_generator(df_train,batch_size)
valid_gen_pre=Data_predict_generator(df_valid,batch_size)
test_gen= Data_generator(df_test,batch_size)
test_gen_pre=Data_predict_generator(df_test,batch_size)

In [17]:
import math
ntrain, nvalid, ntest = df_train.shape[0], df_valid.shape[0],  df_test.shape[0]
nbatches_train=math.ceil(df_train.shape[0]/batch_size)
nbatches_valid=math.ceil(df_valid.shape[0]/batch_size)
nbatches_test=math.ceil( df_test.shape[0]/batch_size)
nworkers=1

In [ ]:
print(nbatches_valid,nbatches_train,nbatches_test)

107 606 80

In [18]:
from keras.models import Sequential
from keras.layers import Conv3D,MaxPooling3D,Dropout,Flatten,Dense,BatchNormalization,ReLU
from tensorflow.keras import initializers
from keras.callbacks import *
import tensorflow as tf

In [19]:
model=Sequential()
model.add(Conv3D(16,kernel_size=(8,8,8),input_shape=(100,100,100,1),padding="same",activation='relu',kernel_initializer=initializers.RandomNormal(stddev=0.01),))
model.add(BatchNormalization())
model.add(MaxPooling3D(pool_size=(2,2,2)))
model.add(Conv3D(32,kernel_size=(4,4,4),activation='relu',padding="same",kernel_initializer=initializers.RandomNormal(stddev=0.01)))
model.add(BatchNormalization())
#model.add(Dropout(0.2))
model.add(MaxPooling3D(pool_size=(2,2,2)))
model.add(Conv3D(64,kernel_size=(2,2,2),activation='relu',padding="same",kernel_initializer=initializers.RandomNormal(stddev=0.01)))
model.add(BatchNormalization())
#model.add(Dropout(0.2))
model.add(MaxPooling3D(pool_size=(2,2,2)))
model.add(Conv3D(128,kernel_size=(2,2,2),activation='relu',padding="same",kernel_initializer=initializers.RandomNormal(stddev=0.01)))
model.add(BatchNormalization())
#model.add(Dropout(0.2))
model.add(MaxPooling3D(pool_size=(2,2,2)))
model.add(Conv3D(256,kernel_size=(2,2,2),activation='relu',padding="same",kernel_initializer=initializers.RandomNormal(stddev=0.01)))
model.add(BatchNormalization())
model.add(MaxPooling3D(pool_size=(2,2,2)))
#model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(1024,activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(512,activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(5))
model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv3d (Conv3D)                      │ (None, 100, 100, 100, 16)   │           8,208 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization                  │ (None, 100, 100, 100, 16)   │              64 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling3d (MaxPooling3D)         │ (None, 50, 50, 50, 16)      │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv3d_1 (Conv3D)                    │ (None, 50, 50, 50, 32)      │          32,800 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_1                │ (None, 50, 50, 50, 32)      │             128 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling3d_1 (MaxPooling3D)       │ (None, 25, 25, 25, 32)      │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv3d_2 (Conv3D)                    │ (None, 25, 25, 25, 64)      │          16,448 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_2                │ (None, 25, 25, 25, 64)      │             256 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling3d_2 (MaxPooling3D)       │ (None, 12, 12, 12, 64)      │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv3d_3 (Conv3D)                    │ (None, 12, 12, 12, 128)     │          65,664 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_3                │ (None, 12, 12, 12, 128)     │             512 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling3d_3 (MaxPooling3D)       │ (None, 6, 6, 6, 128)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv3d_4 (Conv3D)                    │ (None, 6, 6, 6, 256)        │         262,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_4                │ (None, 6, 6, 6, 256)        │           1,024 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling3d_4 (MaxPooling3D)       │ (None, 3, 3, 3, 256)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 6912)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1024)                │       7,078,912 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_5                │ (None, 1024)                │           4,096 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 1024)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 512)                 │         524,800 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_6                │ (None, 512)                 │           2,048 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 512)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 5)                   │           2,565 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 7,999,925 (30.52 MB)

 Trainable params: 7,995,861 (30.50 MB)

 Non-trainable params: 4,064 (15.88 KB)

In [ ]:
import os
checkpoint_path="/content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-{epoch:03d}.ckpt"
#os.makedirs("/content/drive/MyDrive/image/porosity_filtering/training_5layers", exist_ok=True)
#ckpt_callback = ModelCheckpoint(filepath='/content/drive/MyDrive/image/porosity_filtering/training_model_5layers/weights.{epoch:02d}-{val_loss:.2f}.hdf5', monitor='val_loss')
cp_callback=ModelCheckpoint(filepath=checkpoint_path,save_weights_only=True,verbose=1)

In [ ]:
csvlogger=CSVLogger('/content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_169.log')

In [20]:
opt = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(opt,loss='mse',metrics=['mse'])

In [ ]:
wieght='/content/drive/MyDrive/image/porosity_filtering/kernel_dimension/training_model_weights/cp-055.ckpt'
model.load_weights(wieght)

In [ ]:
history=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=55)

<ipython-input-25-130ffbaf157e>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=55)

Epoch 56/200

Epoch 56: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-056.ckpt
606/606 - 365s - loss: 0.1495 - mse: 0.1495 - val_loss: 0.1567 - val_mse: 0.1567 - 365s/epoch - 602ms/step
Epoch 57/200

Epoch 57: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-057.ckpt
606/606 - 325s - loss: 0.1499 - mse: 0.1499 - val_loss: 13.4552 - val_mse: 13.4552 - 325s/epoch - 536ms/step
Epoch 58/200

Epoch 58: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-058.ckpt
606/606 - 324s - loss: 0.1500 - mse: 0.1500 - val_loss: 0.1844 - val_mse: 0.1844 - 324s/epoch - 535ms/step
Epoch 59/200

In [ ]:
wieght='/content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-060.ckpt'
model.load_weights(wieght)

In [ ]:
history=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=60)

Epoch 61/200

<ipython-input-25-336c9aeb01bc>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=60)

Epoch 61: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-061.ckpt
606/606 - 357s - loss: 0.1490 - mse: 0.1490 - val_loss: 0.3412 - val_mse: 0.3412 - 357s/epoch - 590ms/step
Epoch 62/200

Epoch 62: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-062.ckpt
606/606 - 309s - loss: 0.1484 - mse: 0.1484 - val_loss: 0.6663 - val_mse: 0.6663 - 309s/epoch - 509ms/step
Epoch 63/200

Epoch 63: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-063.ckpt
606/606 - 308s - loss: 0.1467 - mse: 0.1467 - val_loss: 1.0202 - val_mse: 1.0202 - 308s/epoch - 509ms/step
Epoch 64/200

Epoch 64: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-064.ckpt
606/606 - 308s - loss: 0.1480 - mse: 0.1480 - val_loss: 0.1445 - val_mse: 0.1445 - 308s/epoch - 509ms/step
Epoch 65/200

Epoch 65: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-065.ckpt
606/606 - 325s - loss: 0.1467 - mse: 0.1467 - val_loss: 0.2124 - val_mse: 0.2124 - 325s/epoch - 537ms/step
Epoch 66/200

Epoch 66: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-066.ckpt
606/606 - 325s - loss: 0.1463 - mse: 0.1463 - val_loss: 0.3815 - val_mse: 0.3815 - 325s/epoch - 537ms/step
Epoch 67/200

Epoch 67: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-067.ckpt
606/606 - 308s - loss: 0.1461 - mse: 0.1461 - val_loss: 0.1831 - val_mse: 0.1831 - 308s/epoch - 509ms/step
Epoch 68/200

Epoch 68: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-068.ckpt
606/606 - 308s - loss: 0.1453 - mse: 0.1453 - val_loss: 7.9823 - val_mse: 7.9823 - 308s/epoch - 509ms/step
Epoch 69/200

Epoch 69: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-069.ckpt
606/606 - 325s - loss: 0.1459 - mse: 0.1459 - val_loss: 0.9236 - val_mse: 0.9236 - 325s/epoch - 537ms/step
Epoch 70/200

Epoch 70: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-070.ckpt
606/606 - 309s - loss: 0.1450 - mse: 0.1450 - val_loss: 0.4606 - val_mse: 0.4606 - 309s/epoch - 509ms/step
Epoch 71/200

Epoch 71: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-071.ckpt
606/606 - 325s - loss: 0.1445 - mse: 0.1445 - val_loss: 0.1425 - val_mse: 0.1425 - 325s/epoch - 537ms/step
Epoch 72/200

Epoch 72: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-072.ckpt
606/606 - 308s - loss: 0.1437 - mse: 0.1437 - val_loss: 0.1226 - val_mse: 0.1226 - 308s/epoch - 509ms/step
Epoch 73/200

Epoch 73: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-073.ckpt
606/606 - 308s - loss: 0.1446 - mse: 0.1446 - val_loss: 0.1453 - val_mse: 0.1453 - 308s/epoch - 509ms/step
Epoch 74/200

Epoch 74: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-074.ckpt
606/606 - 325s - loss: 0.1425 - mse: 0.1425 - val_loss: 0.1238 - val_mse: 0.1238 - 325s/epoch - 537ms/step
Epoch 75/200

Epoch 75: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-075.ckpt
606/606 - 308s - loss: 0.1428 - mse: 0.1428 - val_loss: 0.1380 - val_mse: 0.1380 - 308s/epoch - 509ms/step
Epoch 76/200

Epoch 76: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-076.ckpt
606/606 - 325s - loss: 0.1425 - mse: 0.1425 - val_loss: 0.1280 - val_mse: 0.1280 - 325s/epoch - 536ms/step
Epoch 77/200

Epoch 77: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-077.ckpt
606/606 - 325s - loss: 0.1439 - mse: 0.1439 - val_loss: 0.1434 - val_mse: 0.1434 - 325s/epoch - 537ms/step
Epoch 78/200

Epoch 78: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-078.ckpt
606/606 - 326s - loss: 0.1423 - mse: 0.1423 - val_loss: 0.2326 - val_mse: 0.2326 - 326s/epoch - 537ms/step
Epoch 79/200

Epoch 79: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-079.ckpt
606/606 - 326s - loss: 0.1419 - mse: 0.1419 - val_loss: 0.1648 - val_mse: 0.1648 - 326s/epoch - 537ms/step
Epoch 80/200

Epoch 80: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-080.ckpt
606/606 - 308s - loss: 0.1418 - mse: 0.1418 - val_loss: 0.1538 - val_mse: 0.1538 - 308s/epoch - 509ms/step
Epoch 81/200

Epoch 81: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-081.ckpt
606/606 - 308s - loss: 0.1413 - mse: 0.1413 - val_loss: 0.1781 - val_mse: 0.1781 - 308s/epoch - 509ms/step
Epoch 82/200

Epoch 82: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-082.ckpt
606/606 - 325s - loss: 0.1435 - mse: 0.1435 - val_loss: 0.1219 - val_mse: 0.1219 - 325s/epoch - 537ms/step
Epoch 83/200

Epoch 83: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-083.ckpt
606/606 - 326s - loss: 0.1396 - mse: 0.1396 - val_loss: 0.1330 - val_mse: 0.1330 - 326s/epoch - 537ms/step
Epoch 84/200

Epoch 84: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-084.ckpt
606/606 - 326s - loss: 0.1412 - mse: 0.1412 - val_loss: 0.1385 - val_mse: 0.1385 - 326s/epoch - 537ms/step
Epoch 85/200

Epoch 85: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-085.ckpt
606/606 - 309s - loss: 0.1411 - mse: 0.1411 - val_loss: 0.1263 - val_mse: 0.1263 - 309s/epoch - 509ms/step
Epoch 86/200

Epoch 86: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-086.ckpt
606/606 - 308s - loss: 0.1404 - mse: 0.1404 - val_loss: 0.1324 - val_mse: 0.1324 - 308s/epoch - 509ms/step
Epoch 87/200

Epoch 87: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-087.ckpt
606/606 - 325s - loss: 0.1404 - mse: 0.1404 - val_loss: 0.1371 - val_mse: 0.1371 - 325s/epoch - 537ms/step
Epoch 88/200

In [ ]:
wieght='/content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-088.ckpt'
model.load_weights(wieght)

In [ ]:
history=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=88)

Epoch 89/200

<ipython-input-25-eefbb4dae443>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=88)

Epoch 89: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-089.ckpt
606/606 - 371s - loss: 0.1410 - mse: 0.1410 - val_loss: 0.1366 - val_mse: 0.1366 - 371s/epoch - 613ms/step
Epoch 90/200

Epoch 90: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-090.ckpt
606/606 - 310s - loss: 0.1396 - mse: 0.1396 - val_loss: 0.1514 - val_mse: 0.1514 - 310s/epoch - 512ms/step
Epoch 91/200

Epoch 91: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-091.ckpt
606/606 - 327s - loss: 0.1410 - mse: 0.1410 - val_loss: 0.1256 - val_mse: 0.1256 - 327s/epoch - 539ms/step
Epoch 92/200

Epoch 92: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-092.ckpt
606/606 - 327s - loss: 0.1390 - mse: 0.1390 - val_loss: 0.1284 - val_mse: 0.1284 - 327s/epoch - 540ms/step
Epoch 93/200

Epoch 93: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-093.ckpt
606/606 - 310s - loss: 0.1392 - mse: 0.1392 - val_loss: 0.1363 - val_mse: 0.1363 - 310s/epoch - 512ms/step
Epoch 94/200

Epoch 94: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-094.ckpt
606/606 - 327s - loss: 0.1398 - mse: 0.1398 - val_loss: 0.1758 - val_mse: 0.1758 - 327s/epoch - 539ms/step
Epoch 95/200

Epoch 95: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-095.ckpt
606/606 - 310s - loss: 0.1395 - mse: 0.1395 - val_loss: 0.1301 - val_mse: 0.1301 - 310s/epoch - 512ms/step
Epoch 96/200

Epoch 96: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-096.ckpt
606/606 - 310s - loss: 0.1423 - mse: 0.1423 - val_loss: 0.1894 - val_mse: 0.1894 - 310s/epoch - 511ms/step
Epoch 97/200

Epoch 97: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-097.ckpt
606/606 - 310s - loss: 0.1402 - mse: 0.1402 - val_loss: 0.1215 - val_mse: 0.1215 - 310s/epoch - 512ms/step
Epoch 98/200

In [ ]:
wieght='/content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-099.ckpt'
model.load_weights(wieght)

In [ ]:
history=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=99)

<ipython-input-25-e085a21a682f>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=99)

Epoch 100/200

Epoch 100: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-100.ckpt
606/606 - 341s - loss: 0.1377 - mse: 0.1377 - val_loss: 0.1291 - val_mse: 0.1291 - 341s/epoch - 563ms/step
Epoch 101/200

Epoch 101: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-101.ckpt
606/606 - 317s - loss: 0.1372 - mse: 0.1372 - val_loss: 0.1176 - val_mse: 0.1176 - 317s/epoch - 523ms/step
Epoch 102/200

Epoch 102: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-102.ckpt
606/606 - 317s - loss: 0.1382 - mse: 0.1382 - val_loss: 0.1271 - val_mse: 0.1271 - 317s/epoch - 523ms/step
Epoch 103/200

Epoch 103: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-103.ckpt
606/606 - 333s - loss: 0.1379 - mse: 0.1379 - val_loss: 0.1326 - val_mse: 0.1326 - 333s/epoch - 550ms/step
Epoch 104/200

Epoch 104: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-104.ckpt
606/606 - 334s - loss: 0.1391 - mse: 0.1391 - val_loss: 0.1176 - val_mse: 0.1176 - 334s/epoch - 551ms/step
Epoch 105/200

Epoch 105: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-105.ckpt
606/606 - 334s - loss: 0.1383 - mse: 0.1383 - val_loss: 0.1162 - val_mse: 0.1162 - 334s/epoch - 551ms/step
Epoch 106/200

Epoch 106: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-106.ckpt
606/606 - 334s - loss: 0.1367 - mse: 0.1367 - val_loss: 0.1252 - val_mse: 0.1252 - 334s/epoch - 551ms/step
Epoch 107/200

Epoch 107: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-107.ckpt
606/606 - 334s - loss: 0.1377 - mse: 0.1377 - val_loss: 0.1258 - val_mse: 0.1258 - 334s/epoch - 551ms/step
Epoch 108/200

Epoch 108: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-108.ckpt
606/606 - 318s - loss: 0.1369 - mse: 0.1369 - val_loss: 0.1450 - val_mse: 0.1450 - 318s/epoch - 524ms/step
Epoch 109/200

Epoch 109: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-109.ckpt
606/606 - 334s - loss: 0.1374 - mse: 0.1374 - val_loss: 0.1190 - val_mse: 0.1190 - 334s/epoch - 551ms/step
Epoch 110/200

Epoch 110: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-110.ckpt
606/606 - 334s - loss: 0.1363 - mse: 0.1363 - val_loss: 0.1328 - val_mse: 0.1328 - 334s/epoch - 551ms/step
Epoch 111/200

Epoch 111: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-111.ckpt
606/606 - 318s - loss: 0.1362 - mse: 0.1362 - val_loss: 0.1290 - val_mse: 0.1290 - 318s/epoch - 525ms/step
Epoch 112/200

Epoch 112: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-112.ckpt
606/606 - 333s - loss: 0.1375 - mse: 0.1375 - val_loss: 0.1232 - val_mse: 0.1232 - 333s/epoch - 550ms/step
Epoch 113/200

Epoch 113: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-113.ckpt
606/606 - 334s - loss: 0.1367 - mse: 0.1367 - val_loss: 0.1407 - val_mse: 0.1407 - 334s/epoch - 551ms/step
Epoch 114/200

Epoch 114: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-114.ckpt
606/606 - 318s - loss: 0.1354 - mse: 0.1354 - val_loss: 0.1162 - val_mse: 0.1162 - 318s/epoch - 524ms/step
Epoch 115/200

Epoch 115: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-115.ckpt
606/606 - 333s - loss: 0.1380 - mse: 0.1380 - val_loss: 0.1280 - val_mse: 0.1280 - 333s/epoch - 550ms/step
Epoch 116/200

Epoch 116: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-116.ckpt
606/606 - 334s - loss: 0.1364 - mse: 0.1364 - val_loss: 0.1164 - val_mse: 0.1164 - 334s/epoch - 551ms/step
Epoch 117/200

Epoch 117: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-117.ckpt
606/606 - 318s - loss: 0.1353 - mse: 0.1353 - val_loss: 0.1218 - val_mse: 0.1218 - 318s/epoch - 524ms/step
Epoch 118/200

Epoch 118: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-118.ckpt
606/606 - 333s - loss: 0.1358 - mse: 0.1358 - val_loss: 0.1307 - val_mse: 0.1307 - 333s/epoch - 550ms/step
Epoch 119/200

Epoch 119: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-119.ckpt
606/606 - 334s - loss: 0.1370 - mse: 0.1370 - val_loss: 0.1290 - val_mse: 0.1290 - 334s/epoch - 551ms/step
Epoch 120/200

In [ ]:
wieght='/content/drive/MyDrive/image/porosity_filtering/kernel_dimension/training_model_weights/cp-168.ckpt'
model.load_weights(wieght)

In [ ]:
history=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=168)

<ipython-input-26-081e4b7fdb0b>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=168)

Epoch 169/200

Epoch 169: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-169.ckpt
606/606 - 352s - loss: 0.1329 - mse: 0.1329 - val_loss: 0.1394 - val_mse: 0.1394 - 352s/epoch - 580ms/step
Epoch 170/200

Epoch 170: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-170.ckpt
606/606 - 309s - loss: 0.1323 - mse: 0.1323 - val_loss: 0.1195 - val_mse: 0.1195 - 309s/epoch - 510ms/step
Epoch 171/200

Epoch 171: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-171.ckpt
606/606 - 326s - loss: 0.1332 - mse: 0.1332 - val_loss: 0.1181 - val_mse: 0.1181 - 326s/epoch - 538ms/step
Epoch 172/200

Epoch 172: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-172.ckpt
606/606 - 326s - loss: 0.1334 - mse: 0.1334 - val_loss: 0.1199 - val_mse: 0.1199 - 326s/epoch - 538ms/step
Epoch 173/200

Epoch 173: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-173.ckpt
606/606 - 309s - loss: 0.1322 - mse: 0.1322 - val_loss: 0.1162 - val_mse: 0.1162 - 309s/epoch - 510ms/step
Epoch 174/200

Epoch 174: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-174.ckpt
606/606 - 326s - loss: 0.1335 - mse: 0.1335 - val_loss: 0.1291 - val_mse: 0.1291 - 326s/epoch - 538ms/step
Epoch 175/200

Epoch 175: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-175.ckpt
606/606 - 309s - loss: 0.1316 - mse: 0.1316 - val_loss: 0.1113 - val_mse: 0.1113 - 309s/epoch - 510ms/step
Epoch 176/200

Epoch 176: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-176.ckpt
606/606 - 309s - loss: 0.1322 - mse: 0.1322 - val_loss: 0.1148 - val_mse: 0.1148 - 309s/epoch - 510ms/step
Epoch 177/200

Epoch 177: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-177.ckpt
606/606 - 326s - loss: 0.1329 - mse: 0.1329 - val_loss: 0.1175 - val_mse: 0.1175 - 326s/epoch - 538ms/step
Epoch 178/200

Epoch 178: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-178.ckpt
606/606 - 309s - loss: 0.1316 - mse: 0.1316 - val_loss: 0.1144 - val_mse: 0.1144 - 309s/epoch - 510ms/step
Epoch 179/200

Epoch 179: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-179.ckpt
606/606 - 326s - loss: 0.1314 - mse: 0.1314 - val_loss: 0.1296 - val_mse: 0.1296 - 326s/epoch - 538ms/step
Epoch 180/200

Epoch 180: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-180.ckpt
606/606 - 326s - loss: 0.1325 - mse: 0.1325 - val_loss: 0.1247 - val_mse: 0.1247 - 326s/epoch - 539ms/step
Epoch 181/200

Epoch 181: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-181.ckpt
606/606 - 310s - loss: 0.1323 - mse: 0.1323 - val_loss: 0.1238 - val_mse: 0.1238 - 310s/epoch - 511ms/step
Epoch 182/200

Epoch 182: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-182.ckpt
606/606 - 326s - loss: 0.1314 - mse: 0.1314 - val_loss: 0.1245 - val_mse: 0.1245 - 326s/epoch - 538ms/step
Epoch 183/200

Epoch 183: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-183.ckpt
606/606 - 309s - loss: 0.1322 - mse: 0.1322 - val_loss: 0.1212 - val_mse: 0.1212 - 309s/epoch - 510ms/step
Epoch 184/200

Epoch 184: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-184.ckpt
606/606 - 309s - loss: 0.1327 - mse: 0.1327 - val_loss: 0.1263 - val_mse: 0.1263 - 309s/epoch - 510ms/step
Epoch 185/200

Epoch 185: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-185.ckpt
606/606 - 309s - loss: 0.1320 - mse: 0.1320 - val_loss: 0.1251 - val_mse: 0.1251 - 309s/epoch - 510ms/step
Epoch 186/200

Epoch 186: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-186.ckpt
606/606 - 326s - loss: 0.1315 - mse: 0.1315 - val_loss: 0.1369 - val_mse: 0.1369 - 326s/epoch - 538ms/step
Epoch 187/200

Epoch 187: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-187.ckpt
606/606 - 309s - loss: 0.1325 - mse: 0.1325 - val_loss: 0.1269 - val_mse: 0.1269 - 309s/epoch - 510ms/step
Epoch 188/200

Epoch 188: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-188.ckpt
606/606 - 309s - loss: 0.1320 - mse: 0.1320 - val_loss: 0.1254 - val_mse: 0.1254 - 309s/epoch - 509ms/step
Epoch 189/200

Epoch 189: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-189.ckpt
606/606 - 309s - loss: 0.1314 - mse: 0.1314 - val_loss: 0.1165 - val_mse: 0.1165 - 309s/epoch - 510ms/step
Epoch 190/200

Epoch 190: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-190.ckpt
606/606 - 326s - loss: 0.1310 - mse: 0.1310 - val_loss: 0.1197 - val_mse: 0.1197 - 326s/epoch - 538ms/step
Epoch 191/200

Epoch 191: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-191.ckpt
606/606 - 326s - loss: 0.1317 - mse: 0.1317 - val_loss: 0.1189 - val_mse: 0.1189 - 326s/epoch - 538ms/step
Epoch 192/200

Epoch 192: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-192.ckpt
606/606 - 309s - loss: 0.1309 - mse: 0.1309 - val_loss: 0.1163 - val_mse: 0.1163 - 309s/epoch - 510ms/step
Epoch 193/200

Epoch 193: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-193.ckpt
606/606 - 309s - loss: 0.1327 - mse: 0.1327 - val_loss: 0.1159 - val_mse: 0.1159 - 309s/epoch - 509ms/step
Epoch 194/200

Epoch 194: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-194.ckpt
606/606 - 326s - loss: 0.1318 - mse: 0.1318 - val_loss: 0.1160 - val_mse: 0.1160 - 326s/epoch - 538ms/step
Epoch 195/200

Epoch 195: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-195.ckpt
606/606 - 309s - loss: 0.1301 - mse: 0.1301 - val_loss: 0.1145 - val_mse: 0.1145 - 309s/epoch - 510ms/step
Epoch 196/200

Epoch 196: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-196.ckpt
606/606 - 309s - loss: 0.1314 - mse: 0.1314 - val_loss: 0.1180 - val_mse: 0.1180 - 309s/epoch - 509ms/step
Epoch 197/200

Epoch 197: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-197.ckpt
606/606 - 326s - loss: 0.1311 - mse: 0.1311 - val_loss: 0.1211 - val_mse: 0.1211 - 326s/epoch - 537ms/step
Epoch 198/200

Epoch 198: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-198.ckpt
606/606 - 309s - loss: 0.1307 - mse: 0.1307 - val_loss: 0.1204 - val_mse: 0.1204 - 309s/epoch - 509ms/step
Epoch 199/200

Epoch 199: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-199.ckpt
606/606 - 310s - loss: 0.1311 - mse: 0.1311 - val_loss: 0.1294 - val_mse: 0.1294 - 310s/epoch - 511ms/step
Epoch 200/200

Epoch 200: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-200.ckpt
606/606 - 309s - loss: 0.1315 - mse: 0.1315 - val_loss: 0.1160 - val_mse: 0.1160 - 309s/epoch - 510ms/step

In [ ]:
#**********************************************predicting***********************************************

In [22]:
wieght='/content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-200.ckpt'
model.load_weights(wieght)

ValueError: File format not supported: filepath=/content/drive/MyDrive/image/porosity_filtering/kernel_dimension/8*4*2*2*2/training_model_weights/cp-200.ckpt. Keras 3 only supports V3 `.keras` and `.weights.h5` files, or legacy V1/V2 `.h5` files.

In [ ]:
model.evaluate_generator(test_gen,  nbatches_test, workers=1)

<ipython-input-25-42647287b486>:1: UserWarning: `Model.evaluate_generator` is deprecated and will be removed in a future version. Please use `Model.evaluate`, which supports generators.
  model.evaluate_generator(test_gen,  nbatches_test, workers=1)

[0.10907711833715439, 0.10907711833715439]

In [ ]:
y=model.predict_generator(
    test_gen_pre,
    verbose=1,
    steps=nbatches_test,
    callbacks=None,
    max_queue_size=10,
    workers=1,
    use_multiprocessing=False)

<ipython-input-26-e1afb12c7042>:1: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  y=model.predict_generator(

80/80 [==============================] - 18s 221ms/step

In [ ]:
y_1=pd.DataFrame({'porosity':((y[:,0]*df_new['Porosity'].std())+df_new['Porosity'].mean()),
                  'throat radius':((y[:,1]*df_new['throat radius'].std())+df_new['throat radius'].mean()),
                'pore radius':((y[:,2]*df_new['pore radius'].std())+df_new['pore radius'].mean()),
                'pore_connection_number':((y[:,3]*df_new.pore_connection_number.std())+df_new.pore_connection_number.mean()),
                 'pore shape factor':((y[:,4]*df_new['pore shape factor'].std())+df_new['pore shape factor'].mean())})

In [ ]:
df_test_1=np.array(df_test)
df_test_2=pd.DataFrame({'porosity':((df_test_1[:,1]*df_new.Porosity.std())+df_new.Porosity.mean()),
                  'throat radius':((df_test_1[:,2]*df_new['throat radius'].std())+df_new['throat radius'].mean()),
                'pore radius':((df_test_1[:,3]*df_new['pore radius'].std())+df_new['pore radius'].mean()),
                'pore_connection_number':((df_test_1[:,4]*df_new.pore_connection_number.std())+df_new.pore_connection_number.mean()),
                 'pore shape factor':((df_test_1[:,5]*df_new['pore shape factor'].std())+df_new['pore shape factor'].mean())})

In [ ]:
#R^2_porosity
from sklearn.metrics import r2_score
x_values = np.array(df_test_2['porosity'])
y_values = np.array(y_1['porosity'])
r_squared_porosity=r2_score(x_values, y_values)
#orrelation_matrix = np.corrcoef(x_values, y_values)
#correlation_xy = correlation_matrix[0,1]
#r_squared_porosity = correlation_xy**2
print(r_squared_porosity)

0.9863472912056863

In [ ]:
#R^2_porosity
from sklearn.metrics import r2_score
x_values = np.array(df_test_2['pore shape factor'])
y_values = np.array(y_1['pore shape factor'])
r_squared_pore_shape_factor=r2_score(x_values, y_values)
#orrelation_matrix = np.corrcoef(x_values, y_values)
#correlation_xy = correlation_matrix[0,1]
#r_squared_porosity = correlation_xy**2
print(r_squared_pore_shape_factor)

0.7141543052248689

In [ ]:
from sklearn.metrics import r2_score
x_values = np.array(df_test_2['throat radius'])
y_values = np.array(y_1['throat radius'])
r_squared_throat_radius=r2_score(x_values, y_values)
#orrelation_matrix = np.corrcoef(x_values, y_values)
#correlation_xy = correlation_matrix[0,1]
#r_squared_porosity = correlation_xy**2
print(r_squared_throat_radius)

0.9023461826055661

In [ ]:
#R^2_porosity
from sklearn.metrics import r2_score
x_values = np.array(df_test_2['pore radius'])
y_values = np.array(y_1['pore radius'])
r_squared_pore_radius=r2_score(x_values, y_values)
#orrelation_matrix = np.corrcoef(x_values, y_values)
#correlation_xy = correlation_matrix[0,1]
#r_squared_porosity = correlation_xy**2
print(r_squared_pore_radius)

0.9270746558118239

In [ ]:
#R^2_porosity
from sklearn.metrics import r2_score
x_values = np.array(df_test_2['pore_connection_number'])
y_values = np.array(y_1['pore_connection_number'])
r_squared_pore_connection_number=r2_score(x_values, y_values)
#orrelation_matrix = np.corrcoef(x_values, y_values)
#correlation_xy = correlation_matrix[0,1]
#r_squared_porosity = correlation_xy**2
print(r_squared_pore_connection_number)

0.9172568570303352

In [ ]:
average = np.mean([r_squared_porosity, r_squared_pore_shape_factor, r_squared_throat_radius, r_squared_pore_radius,r_squared_pore_connection_number], axis=0)
print(average)

0.889435858375656