In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!cp /content/drive/MyDrive/image/images.zip -d /content/images.zip
!unzip -q images.zip

In [3]:
!rm /content/images.zip

In [4]:
import os
A=os.listdir('/content')
A

['.config', 'drive', 'images', 'sample_data']

In [5]:
import pandas as pd
import glob
import os
import numpy as np
import matplotlib.pyplot as plt
s='/content/images/*'
path=glob.glob(s)
import re
def sorted_alphanumeric(data):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ]
    return sorted(data, key=alphanum_key)

path1=sorted_alphanumeric(path)
path1 = [item.replace('p','_') for item in path1]
data=pd.read_excel('/content/drive/MyDrive/image/data_c.xlsx')
data
len(path1)
print(path1)
type(path1)
path1=np.array(path1)
path1.shape
path1[0]

['/content/images/C_1_1_1.raw', '/content/images/C_1_1_16.raw', '/content/images/C_1_1_31.raw', '/content/images/C_1_1_46.raw', '/content/images/C_1_1_61.raw', '/content/images/C_1_1_76.raw', '/content/images/C_1_1_91.raw', '/content/images/C_1_1_106.raw', '/content/images/C_1_1_121.raw', '/content/images/C_1_1_136.raw', '/content/images/C_1_1_151.raw', '/content/images/C_1_1_166.raw', '/content/images/C_1_1_181.raw', '/content/images/C_1_1_196.raw', '/content/images/C_1_1_211.raw', '/content/images/C_1_1_226.raw', '/content/images/C_1_1_241.raw', '/content/images/C_1_1_256.raw', '/content/images/C_1_1_271.raw', '/content/images/C_1_1_286.raw', '/content/images/C_1_1_301.raw', '/content/images/C_1_16_1.raw', '/content/images/C_1_16_16.raw', '/content/images/C_1_16_31.raw', '/content/images/C_1_16_46.raw', '/content/images/C_1_16_61.raw', '/content/images/C_1_16_76.raw', '/content/images/C_1_16_91.raw', '/content/images/C_1_16_106.raw', '/content/images/C_1_16_121.raw', '/content/images/C_1_16_136.raw', '/content/images/C_1_16_151.raw', '/content/images/C_1_16_166.raw', '/content/images/C_1_16_181.raw', '/content/images/C_1_16_196.raw', '/content/images/C_1_16_211.raw', '/content/images/C_1_16_226.raw', '/content/images/C_1_16_241.raw', '/content/images/C_1_16_256.raw', '/content/images/C_1_16_271.raw', '/content/images/C_1_16_286.raw', '/content/images/C_1_16_301.raw', '/content/images/C_1_31_1.raw', '/content/images/C_1_31_16.raw', '/content/images/C_1_31_31.raw', '/content/images/C_1_31_46.raw', '/content/images/C_1_31_61.raw', '/content/images/C_1_31_76.raw', '/content/images/C_1_31_91.raw', '/content/images/C_1_31_106.raw', '/content/images/C_1_31_121.raw', '/content/images/C_1_31_136.raw', '/content/images/C_1_31_151.raw', '/content/images/C_1_31_166.raw', '/content/images/C_1_31_181.raw', '/content/images/C_1_31_196.raw', '/content/images/C_1_31_211.raw', '/content/images/C_1_31_226.raw', '/content/images/C_1_31_241.raw', '/content/images/C_1_31_256.raw', '/content/images/C_1_31_271.raw', '/content/images/C_1_31_286.raw', '/content/images/C_1_31_301.raw', '/content/images/C_1_46_1.raw', '/content/images/C_1_46_16.raw', '/content/images/C_1_46_31.raw', '/content/images/C_1_46_46.raw', '/content/images/C_1_46_61.raw', '/content/images/C_1_46_76.raw', '/content/images/C_1_46_91.raw', '/content/images/C_1_46_106.raw', '/content/images/C_1_46_121.raw', '/content/images/C_1_46_136.raw', '/content/images/C_1_46_151.raw', '/content/images/C_1_46_166.raw', '/content/images/C_1_46_181.raw', '/content/images/C_1_46_196.raw', '/content/images/C_1_46_211.raw', '/content/images/C_1_46_226.raw', '/content/images/C_1_46_241.raw', '/content/images/C_1_46_256.raw', '/content/images/C_1_46_271.raw', '/content/images/C_1_46_286.raw', '/content/images/C_1_46_301.raw', '/content/images/C_1_61_1.raw', '/content/images/C_1_61_16.raw', '/content/images/C_1_61_31.raw', '/content/images/C_1_61_46.raw', '/content/images/C_1_61_61.raw', '/content/images/C_1_61_76.raw', '/content/images/C_1_61_91.raw', '/content/images/C_1_61_106.raw', '/content/images/C_1_61_121.raw', '/content/images/C_1_61_136.raw', '/content/images/C_1_61_151.raw', '/content/images/C_1_61_166.raw', '/content/images/C_1_61_181.raw', '/content/images/C_1_61_196.raw', '/content/images/C_1_61_211.raw', '/content/images/C_1_61_226.raw', '/content/images/C_1_61_241.raw', '/content/images/C_1_61_256.raw', '/content/images/C_1_61_271.raw', '/content/images/C_1_61_286.raw', '/content/images/C_1_61_301.raw', '/content/images/C_1_76_1.raw', '/content/images/C_1_76_16.raw', '/content/images/C_1_76_31.raw', '/content/images/C_1_76_46.raw', '/content/images/C_1_76_61.raw', '/content/images/C_1_76_76.raw', '/content/images/C_1_76_91.raw', '/content/images/C_1_76_106.raw', '/content/images/C_1_76_121.raw', '/content/images/C_1_76_136.raw', '/content/images/C_1_76_151.raw', '/content/images/C_1_76_166.raw', '/content/images/C_1_76_181.raw', '/content/images/C_1_76_196.raw', '/content/images/C_1_76_211.raw', '/content/images/C_1_76_226.raw', '/content/images/C_1_76_241.raw', '/content/images/C_1_76_256.raw', '/content/images/C_1_76_271.raw', '/content/images/C_1_76_286.raw', '/content/images/C_1_76_301.raw', '/content/images/C_1_91_1.raw', '/content/images/C_1_91_16.raw', '/content/images/C_1_91_31.raw', '/content/images/C_1_91_46.raw', '/content/images/C_1_91_61.raw', '/content/images/C_1_91_76.raw', '/content/images/C_1_91_91.raw', '/content/images/C_1_91_106.raw', '/content/images/C_1_91_121.raw', '/content/images/C_1_91_136.raw', '/content/images/C_1_91_151.raw', '/content/images/C_1_91_166.raw', '/content/images/C_1_91_181.raw', '/content/images/C_1_91_196.raw', '/content/images/C_1_91_211.raw', '/content/images/C_1_91_226.raw', '/content/images/C_1_91_241.raw', '/content/images/C_1_91_256.raw', '/content/images/C_1_91_271.raw', '/content/images/C_1_91_286.raw', '/content/images/C_1_91_301.raw', '/content/images/C_1_106_1.raw', '/content/images/C_1_106_16.raw', '/content/images/C_1_106_31.raw', '/content/images/C_1_106_46.raw', '/content/images/C_1_106_61.raw', '/content/images/C_1_106_76.raw', '/content/images/C_1_106_91.raw', '/content/images/C_1_106_106.raw', '/content/images/C_1_106_121.raw', '/content/images/C_1_106_136.raw', '/content/images/C_1_106_151.raw', '/content/images/C_1_106_166.raw', '/content/images/C_1_106_181.raw', '/content/images/C_1_106_196.raw', '/content/images/C_1_106_211.raw', '/content/images/C_1_106_226.raw', '/content/images/C_1_106_241.raw', '/content/images/C_1_106_256.raw', '/content/images/C_1_106_271.raw', '/content/images/C_1_106_286.raw', '/content/images/C_1_106_301.raw', '/content/images/C_1_121_1.raw', '/content/images/C_1_121_16.raw', '/content/images/C_1_121_31.raw', '/content/images/C_1_121_46.raw', '/content/images/C_1_121_61.raw', '/content/images/C_1_121_76.raw', '/content/images/C_1_121_91.raw', '/content/images/C_1_121_106.raw', '/content/images/C_1_121_121.raw', '/content/images/C_1_121_136.raw', '/content/images/C_1_121_151.raw', '/content/images/C_1_121_166.raw', '/content/images/C_1_121_181.raw', '/content/images/C_1_121_196.raw', '/content/images/C_1_121_211.raw', '/content/images/C_1_121_226.raw', '/content/images/C_1_121_241.raw', '/content/images/C_1_121_256.raw', '/content/images/C_1_121_271.raw', '/content/images/C_1_121_286.raw', '/content/images/C_1_121_301.raw', '/content/images/C_1_136_1.raw', '/content/images/C_1_136_16.raw', '/content/images/C_1_136_31.raw', '/content/images/C_1_136_46.raw', '/content/images/C_1_136_61.raw', '/content/images/C_1_136_76.raw', '/content/images/C_1_136_91.raw', '/content/images/C_1_136_106.raw', '/content/images/C_1_136_121.raw', '/content/images/C_1_136_136.raw', '/content/images/C_1_136_151.raw', '/content/images/C_1_136_166.raw', '/content/images/C_1_136_181.raw', '/content/images/C_1_136_196.raw', '/content/images/C_1_136_211.raw', '/content/images/C_1_136_226.raw', '/content/images/C_1_136_241.raw', '/content/images/C_1_136_256.raw', '/content/images/C_1_136_271.raw', '/content/images/C_1_136_286.raw', '/content/images/C_1_136_301.raw', '/content/images/C_1_151_1.raw', '/content/images/C_1_151_16.raw', '/content/images/C_1_151_31.raw', '/content/images/C_1_151_46.raw', '/content/images/C_1_151_61.raw', '/content/images/C_1_151_76.raw', '/content/images/C_1_151_91.raw', '/content/images/C_1_151_106.raw', '/content/images/C_1_151_121.raw', '/content/images/C_1_151_136.raw', '/content/images/C_1_151_151.raw', '/content/images/C_1_151_166.raw', '/content/images/C_1_151_181.raw', '/content/images/C_1_151_196.raw', '/content/images/C_1_151_211.raw', '/content/images/C_1_151_226.raw', '/content/images/C_1_151_241.raw', '/content/images/C_1_151_256.raw', '/content/images/C_1_151_271.raw', '/content/images/C_1_151_286.raw', '/content/images/C_1_151_301.raw', '/content/images/C_1_166_1.raw', '/content/images/C_1_166_16.raw', '/content/images/C_1_166_31.raw', '/content/images/C_1_166_46.raw', '/content/images/C_1_166_61.raw', '/content/images/C_1_166_76.raw', '/content/images/C_1_166_91.raw', '/content/images/C_1_166_106.raw', '/content/images/C_1_166_121.raw', '/content/images/C_1_166_136.raw', '/content/images/C_1_166_151.raw', '/content/images/C_1_166_166.raw', '/content/images/C_1_166_181.raw', '/content/images/C_1_166_196.raw', '/content/images/C_1_166_211.raw', '/content/images/C_1_166_226.raw', '/content/images/C_1_166_241.raw', '/content/images/C_1_166_256.raw', '/content/images/C_1_166_271.raw', '/content/images/C_1_166_286.raw', '/content/images/C_1_166_301.raw', '/content/images/C_1_181_1.raw', '/content/images/C_1_181_16.raw', '/content/images/C_1_181_31.raw', '/content/images/C_1_181_46.raw', '/content/images/C_1_181_61.raw', '/content/images/C_1_181_76.raw', '/content/images/C_1_181_91.raw', '/content/images/C_1_181_106.raw', '/content/images/C_1_181_121.raw', '/content/images/C_1_181_136.raw', '/content/images/C_1_181_151.raw', '/content/images/C_1_181_166.raw', '/content/images/C_1_181_181.raw', '/content/images/C_1_181_196.raw', '/content/images/C_1_181_211.raw', '/content/images/C_1_181_226.raw', '/content/images/C_1_181_241.raw', '/content/images/C_1_181_256.raw', '/content/images/C_1_181_271.raw', '/content/images/C_1_181_286.raw', '/content/images/C_1_181_301.raw', '/content/images/C_1_196_1.raw', '/content/images/C_1_196_16.raw', '/content/images/C_1_196_31.raw', '/content/images/C_1_196_46.raw', '/content/images/C_1_196_61.raw', '/content/images/C_1_196_76.raw', '/content/images/C_1_196_91.raw', '/content/images/C_1_196_106.raw', '/content/images/C_1_196_121.raw', '/content/images/C_1_196_136.raw', '/content/images/C_1_196_151.raw', '/content/images/C_1_196_166.raw', '/content/images/C_1_196_181.raw', '/content/images/C_1_196_196.raw', '/content/images/C_1_196_211.raw', '/content/images/C_1_196_226.raw', '/content/images/C_1_196_241.raw', '/content/images/C_1_196_256.raw', '/content/images/C_1_196_271.raw', '/content/images/C_1_196_286.raw', '/content/images/C_1_196_301.raw', '/content/images/C_1_211_1.raw', '/content/images/C_1_211_16.raw', '/content/images/C_1_211_31.raw', '/content/images/C_1_211_46.raw', '/content/images/C_1_211_61.raw', '/content/images/C_1_211_76.raw', '/content/images/C_1_211_91.raw', '/content/images/C_1_211_106.raw', '/content/images/C_1_211_121.raw', '/content/images/C_1_211_136.raw', '/content/images/C_1_211_151.raw', '/content/images/C_1_211_166.raw', '/content/images/C_1_211_181.raw', '/content/images/C_1_211_196.raw', '/content/images/C_1_211_211.raw', '/content/images/C_1_211_226.raw', '/content/images/C_1_211_241.raw', '/content/images/C_1_211_256.raw', '/content/images/C_1_211_271.raw', '/content/images/C_1_211_286.raw', '/content/images/C_1_211_301.raw', '/content/images/C_1_226_1.raw', '/content/images/C_1_226_16.raw', '/content/images/C_1_226_31.raw', '/content/images/C_1_226_46.raw', '/content/images/C_1_226_61.raw', '/content/images/C_1_226_76.raw', '/content/images/C_1_226_91.raw', '/content/images/C_1_226_106.raw', '/content/images/C_1_226_121.raw', '/content/images/C_1_226_136.raw', '/content/images/C_1_226_151.raw', '/content/images/C_1_226_166.raw', '/content/images/C_1_226_181.raw', '/content/images/C_1_226_196.raw', '/content/images/C_1_226_211.raw', '/content/images/C_1_226_226.raw', '/content/images/C_1_226_241.raw', '/content/images/C_1_226_256.raw', '/content/images/C_1_226_271.raw', '/content/images/C_1_226_286.raw', '/content/images/C_1_226_301.raw', '/content/images/C_1_241_1.raw', '/content/images/C_1_241_16.raw', '/content/images/C_1_241_31.raw', '/content/images/C_1_241_46.raw', '/content/images/C_1_241_61.raw', '/content/images/C_1_241_76.raw', '/content/images/C_1_241_91.raw', '/content/images/C_1_241_106.raw', '/content/images/C_1_241_121.raw', '/content/images/C_1_241_136.raw', '/content/images/C_1_241_151.raw', '/content/images/C_1_241_166.raw', '/content/images/C_1_241_181.raw', '/content/images/C_1_241_196.raw', '/content/images/C_1_241_211.raw', '/content/images/C_1_241_226.raw', '/content/images/C_1_241_241.raw', '/content/images/C_1_241_256.raw', '/content/images/C_1_241_271.raw', '/content/images/C_1_241_286.raw', '/content/images/C_1_241_301.raw', '/content/images/C_1_256_1.raw', '/content/images/C_1_256_16.raw', '/content/images/C_1_256_31.raw', '/content/images/C_1_256_46.raw', '/content/images/C_1_256_61.raw', '/content/images/C_1_256_76.raw', '/content/images/C_1_256_91.raw', '/content/images/C_1_256_106.raw', '/content/images/C_1_256_121.raw', '/content/images/C_1_256_136.raw', '/content/images/C_1_256_151.raw', '/content/images/C_1_256_166.raw', '/content/images/C_1_256_181.raw', '/content/images/C_1_256_196.raw', '/content/images/C_1_256_211.raw', '/content/images/C_1_256_226.raw', '/content/images/C_1_256_241.raw', '/content/images/C_1_256_256.raw', '/content/images/C_1_256_271.raw', '/content/images/C_1_256_286.raw', '/content/images/C_1_256_301.raw', '/content/images/C_1_271_1.raw', '/content/images/C_1_271_16.raw', '/content/images/C_1_271_31.raw', '/content/images/C_1_271_46.raw', '/content/images/C_1_271_61.raw', '/content/images/C_1_271_76.raw', '/content/images/C_1_271_91.raw', '/content/images/C_1_271_106.raw', '/content/images/C_1_271_121.raw', '/content/images/C_1_271_136.raw', '/content/images/C_1_271_151.raw', '/content/images/C_1_271_166.raw', '/content/images/C_1_271_181.raw', '/content/images/C_1_271_196.raw', '/content/images/C_1_271_211.raw', '/content/images/C_1_271_226.raw', '/content/images/C_1_271_241.raw', '/content/images/C_1_271_256.raw', '/content/images/C_1_271_271.raw', '/content/images/C_1_271_286.raw', '/content/images/C_1_271_301.raw', '/content/images/C_1_286_1.raw', '/content/images/C_1_286_16.raw', '/content/images/C_1_286_31.raw', '/content/images/C_1_286_46.raw', '/content/images/C_1_286_61.raw', '/content/images/C_1_286_76.raw', '/content/images/C_1_286_91.raw', '/content/images/C_1_286_106.raw', '/content/images/C_1_286_121.raw', '/content/images/C_1_286_136.raw', '/content/images/C_1_286_151.raw', '/content/images/C_1_286_166.raw', '/content/images/C_1_286_181.raw', '/content/images/C_1_286_196.raw', '/content/images/C_1_286_211.raw', '/content/images/C_1_286_226.raw', '/content/images/C_1_286_241.raw', '/content/images/C_1_286_256.raw', '/content/images/C_1_286_271.raw', '/content/images/C_1_286_286.raw', '/content/images/C_1_286_301.raw', '/content/images/C_1_301_1.raw', '/content/images/C_1_301_16.raw', '/content/images/C_1_301_31.raw', '/content/images/C_1_301_46.raw', '/content/images/C_1_301_61.raw', '/content/images/C_1_301_76.raw', '/content/images/C_1_301_91.raw', '/content/images/C_1_301_106.raw', '/content/images/C_1_301_121.raw', '/content/images/C_1_301_136.raw', '/content/images/C_1_301_151.raw', '/content/images/C_1_301_166.raw', '/content/images/C_1_301_181.raw', '/content/images/C_1_301_196.raw', '/content/images/C_1_301_211.raw', '/content/images/C_1_301_226.raw', '/content/images/C_1_301_241.raw', '/content/images/C_1_301_256.raw', '/content/images/C_1_301_271.raw', '/content/images/C_1_301_286.raw', '/content/images/C_1_301_301.raw', '/content/images/C_16_1_1.raw', '/content/images/C_16_1_16.raw', '/content/images/C_16_1_31.raw', '/content/images/C_16_1_46.raw', '/content/images/C_16_1_61.raw', '/content/images/C_16_1_76.raw', '/content/images/C_16_1_91.raw', '/content/images/C_16_1_106.raw', '/content/images/C_16_1_121.raw', '/content/images/C_16_1_136.raw', '/content/images/C_16_1_151.raw', '/content/images/C_16_1_166.raw', '/content/images/C_16_1_181.raw', '/content/images/C_16_1_196.raw', '/content/images/C_16_1_211.raw', '/content/images/C_16_1_226.raw', '/content/images/C_16_1_241.raw', '/content/images/C_16_1_256.raw', '/content/images/C_16_1_271.raw', '/content/images/C_16_1_286.raw', '/content/images/C_16_1_301.raw', '/content/images/C_16_16_1.raw', '/content/images/C_16_16_16.raw', '/content/images/C_16_16_31.raw', '/content/images/C_16_16_46.raw', '/content/images/C_16_16_61.raw', '/content/images/C_16_16_76.raw', '/content/images/C_16_16_91.raw', '/content/images/C_16_16_106.raw', '/content/images/C_16_16_121.raw', '/content/images/C_16_16_136.raw', '/content/images/C_16_16_151.raw', '/content/images/C_16_16_166.raw', '/content/images/C_16_16_181.raw', '/content/images/C_16_16_196.raw', '/content/images/C_16_16_211.raw', '/content/images/C_16_16_226.raw', '/content/images/C_16_16_241.raw', '/content/images/C_16_16_256.raw', '/content/images/C_16_16_271.raw', '/content/images/C_16_16_286.raw', '/content/images/C_16_16_301.raw', '/content/images/C_16_31_1.raw', '/content/images/C_16_31_16.raw', '/content/images/C_16_31_31.raw', '/content/images/C_16_31_46.raw', '/content/images/C_16_31_61.raw', '/content/images/C_16_31_76.raw', '/content/images/C_16_31_91.raw', '/content/images/C_16_31_106.raw', '/content/images/C_16_31_121.raw', '/content/images/C_16_31_136.raw', '/content/images/C_16_31_151.raw', '/content/images/C_16_31_166.raw', '/content/images/C_16_31_181.raw', '/content/images/C_16_31_196.raw', '/content/images/C_16_31_211.raw', '/content/images/C_16_31_226.raw', '/content/images/C_16_31_241.raw', '/content/images/C_16_31_256.raw', '/content/images/C_16_31_271.raw', '/content/images/C_16_31_286.raw', '/content/images/C_16_31_301.raw', '/content/images/C_16_46_1.raw', '/content/images/C_16_46_16.raw', '/content/images/C_16_46_31.raw', '/content/images/C_16_46_46.raw', '/content/images/C_16_46_61.raw', '/content/images/C_16_46_76.raw', '/content/images/C_16_46_91.raw', '/content/images/C_16_46_106.raw', '/content/images/C_16_46_121.raw', '/content/images/C_16_46_136.raw', '/content/images/C_16_46_151.raw', '/content/images/C_16_46_166.raw', '/content/images/C_16_46_181.raw', '/content/images/C_16_46_196.raw', '/content/images/C_16_46_211.raw', '/content/images/C_16_46_226.raw', '/content/images/C_16_46_241.raw', '/content/images/C_16_46_256.raw', '/content/images/C_16_46_271.raw', '/content/images/C_16_46_286.raw', '/content/images/C_16_46_301.raw', '/content/images/C_16_61_1.raw', '/content/images/C_16_61_16.raw', '/content/images/C_16_61_31.raw', '/content/images/C_16_61_46.raw', '/content/images/C_16_61_61.raw', '/content/images/C_16_61_76.raw', '/content/images/C_16_61_91.raw', '/content/images/C_16_61_106.raw', '/content/images/C_16_61_121.raw', '/content/images/C_16_61_136.raw', '/content/images/C_16_61_151.raw', '/content/images/C_16_61_166.raw', '/content/images/C_16_61_181.raw', '/content/images/C_16_61_196.raw', '/content/images/C_16_61_211.raw', '/content/images/C_16_61_226.raw', '/content/images/C_16_61_241.raw', '/content/images/C_16_61_256.raw', '/content/images/C_16_61_271.raw', '/content/images/C_16_61_286.raw', '/content/images/C_16_61_301.raw', '/content/images/C_16_76_1.raw', '/content/images/C_16_76_16.raw', '/content/images/C_16_76_31.raw', '/content/images/C_16_76_46.raw', '/content/images/C_16_76_61.raw', '/content/images/C_16_76_76.raw', '/content/images/C_16_76_91.raw', '/content/images/C_16_76_106.raw', '/content/images/C_16_76_121.raw', '/content/images/C_16_76_136.raw', '/content/images/C_16_76_151.raw', '/content/images/C_16_76_166.raw', '/content/images/C_16_76_181.raw', '/content/images/C_16_76_196.raw', '/content/images/C_16_76_211.raw', '/content/images/C_16_76_226.raw', '/content/images/C_16_76_241.raw', '/content/images/C_16_76_256.raw', '/content/images/C_16_76_271.raw', '/content/images/C_16_76_286.raw', '/content/images/C_16_76_301.raw', '/content/images/C_16_91_1.raw', '/content/images/C_16_91_16.raw', '/content/images/C_16_91_31.raw', '/content/images/C_16_91_46.raw', '/content/images/C_16_91_61.raw', '/content/images/C_16_91_76.raw', '/content/images/C_16_91_91.raw', '/content/images/C_16_91_106.raw', '/content/images/C_16_91_121.raw', '/content/images/C_16_91_136.raw', '/content/images/C_16_91_151.raw', '/content/images/C_16_91_166.raw', '/content/images/C_16_91_181.raw', '/content/images/C_16_91_196.raw', '/content/images/C_16_91_211.raw', '/content/images/C_16_91_226.raw', '/conte

'/content/images/C_1_1_1.raw'

In [6]:
path1=np.array(path1)
data=np.array(data)

In [7]:
df=pd.DataFrame({'imgpath':path1,'Porosity':data[:,0],'throat radius':data[:,1],'pore radius':data[:,2],'pore_connection_number':data[:,3],'pore shape factor':data[:,4]})

In [8]:
df_new=df[df['Porosity'] <0.35 ]
df_new.shape
df_new

,imgpath,Porosity,throat radius,pore radius,pore_connection_number,pore shape factor
0,/content/images/C_1_1_1.raw,0.200016,0.000009,0.000013,1.92857,0.037024
1,/content/images/C_1_1_16.raw,0.211707,0.000008,0.000012,2.25000,0.036642
2,/content/images/C_1_1_31.raw,0.233293,0.000008,0.000013,1.96875,0.038013
3,/content/images/C_1_1_46.raw,0.264409,0.000009,0.000014,2.18182,0.039828
4,/content/images/C_1_1_61.raw,0.277295,0.000009,0.000014,2.27273,0.038306
...,...,...,...,...,...,...
9256,/content/images/C_301_301_241.raw,0.136927,0.000008,0.000013,2.35443,0.036514
9257,/content/images/C_301_301_256.raw,0.136191,0.000008,0.000013,2.12658,0.036236
9258,/content/images/C_301_301_271.raw,0.147490,0.000008,0.000014,2.17722,0.033896
9259,/content/images/C_301_301_286.raw,0.161413,0.000008,0.000013,2.18987,0.035108
9260,/content/images/C_301_301_301.raw,0.179779,0.000009,0.000015,1.97468,0.029493

In [9]:
from sklearn.preprocessing import StandardScaler
import numpy as np
data1=np.array(df_new)
scaler = StandardScaler()
data1= scaler.fit_transform(data1[:,1:])
print(data1)
print(type(data1))
data1.shape

[[ 0.11455659  0.58493673  0.28969785 -0.82815281 -0.22691552]
 [ 0.27058416 -0.34306756 -0.15901557 -0.0260099  -0.34020621]
 [ 0.55866997 -0.05166937  0.52032542 -0.72788183  0.06680977]
 ...
 [-0.58645309 -0.39830083  0.62718527 -0.20763563 -1.1561657 ]
 [-0.40063734  0.06434896  0.10229779 -0.17606699 -0.79601231]
 [-0.15552552  0.3087704   1.25751387 -0.71308325 -2.46407987]]
<class 'numpy.ndarray'>

(7921, 5)

In [10]:
df=pd.DataFrame({'imgpath':df_new['imgpath'],'Porosity':data1[:,0],'throat radius':data1[:,1],'pore radius':data1[:,2],'pore_connection_number':data1[:,3],'pore shape factor':data1[:,4]})
df

,imgpath,Porosity,throat radius,pore radius,pore_connection_number,pore shape factor
0,/content/images/C_1_1_1.raw,0.114557,0.584937,0.289698,-0.828153,-0.226916
1,/content/images/C_1_1_16.raw,0.270584,-0.343068,-0.159016,-0.026010,-0.340206
2,/content/images/C_1_1_31.raw,0.558670,-0.051669,0.520325,-0.727882,0.066810
3,/content/images/C_1_1_46.raw,0.973943,0.745227,0.630089,-0.196156,0.606040
4,/content/images/C_1_1_61.raw,1.145919,0.514543,1.057970,0.030714,0.154056
...,...,...,...,...,...,...
9256,/content/images/C_301_301_241.raw,-0.727426,-0.487201,0.223571,0.234600,-0.378288
9257,/content/images/C_301_301_256.raw,-0.737249,-0.264275,0.454180,-0.334010,-0.460952
9258,/content/images/C_301_301_271.raw,-0.586453,-0.398301,0.627185,-0.207636,-1.156166
9259,/content/images/C_301_301_286.raw,-0.400637,0.064349,0.102298,-0.176067,-0.796012
9260,/content/images/C_301_301_301.raw,-0.155526,0.308770,1.257514,-0.713083,-2.464080

In [11]:
data_t_general=df.sample(frac=0.9,random_state=1)
df_valid=data_t_general.sample(frac=0.15,random_state=2)
df_train=data_t_general.loc[~data_t_general.index.isin(df_valid.index)]
df_test =df.loc[~df.index.isin(data_t_general.index)]
len(df_train)

6060

In [12]:
def Data_generator(df, batch_size, augment=False):

    while True:

            for start in range(0, df.shape[0], batch_size):
                x_batch_img = []
                y_batch=[]
                end = min(start + batch_size, df.shape[0])

                for idd in range(start,end):
                    img = open(np.array(df.imgpath)[idd],'rb').read()
                    img_1=np.frombuffer(img,dtype=np.uint8)
                    img_1=img_1.reshape(100,100,100,1)
                    Porosity=np.array(df.Porosity)[idd]
                    throat_radius=np.array(df['throat radius'])[idd]
                    pore_radius=np.array(df['pore radius'])[idd]
                    pore_connection_number=np.array(df.pore_connection_number)[idd]
                    pore_shape_factor=np.array(df['pore shape factor'])[idd]
                    y_1=np.concatenate((Porosity, throat_radius,pore_radius,pore_connection_number, pore_shape_factor),axis=None)
                    y=np.array([y_1])
                    x_batch_img.append(img_1)
                    y_batch.append(y)


                x_batch_img = np.array(x_batch_img)
                y_batch= np.array(y_batch)
                y_batch=y_batch.reshape(-1,5)
              #y_batch = to_categorical(y_batch,5)
                yield x_batch_img , y_batch

In [13]:
def Data_predict_generator(df, batch_size, augment=False):

    while True:

            for start in range(0, df.shape[0], batch_size):
                x_batch_img_2 = []

                end = min(start + batch_size, df.shape[0])

                for idd in range(start,end):
                    img = open(np.array(df.imgpath)[idd],'rb').read()
                    img_1=np.frombuffer(img,dtype=np.uint8)
                    img_1=img_1.reshape(100,100,100,1)
                    x_batch_img_2.append(img_1)



                x_batch_img_2 = np.array(x_batch_img_2)

              #y_batch = to_categorical(y_batch,5)
                yield x_batch_img_2

In [14]:
batch_size=10
train_gen= Data_generator(df_train,batch_size)
valid_gen= Data_generator(df_valid,batch_size)
train_gen_pre=Data_predict_generator(df_train,batch_size)
valid_gen_pre=Data_predict_generator(df_valid,batch_size)
test_gen= Data_generator(df_test,batch_size)
test_gen_pre=Data_predict_generator(df_test,batch_size)

In [15]:
import math
ntrain, nvalid, ntest = df_train.shape[0], df_valid.shape[0],  df_test.shape[0]
nbatches_train=math.ceil(df_train.shape[0]/batch_size)
nbatches_valid=math.ceil(df_valid.shape[0]/batch_size)
nbatches_test=math.ceil( df_test.shape[0]/batch_size)
nworkers=1

In [16]:
print(nbatches_valid,nbatches_train,nbatches_test)

107 606 80

In [17]:
from keras.models import Sequential
from keras.layers import Conv3D,MaxPooling3D,Dropout,Flatten,Dense,BatchNormalization,ReLU
from tensorflow.keras import initializers
from keras.callbacks import *
import tensorflow as tf

In [18]:
model=Sequential()
model.add(Conv3D(16,kernel_size=(7,7,7),input_shape=(100,100,100,1),padding="same",activation='relu',kernel_initializer=initializers.RandomNormal(stddev=0.01),))
model.add(BatchNormalization())
model.add(MaxPooling3D(pool_size=(2,2,2)))
model.add(Conv3D(32,kernel_size=(3,3,3),activation='relu',padding="same",kernel_initializer=initializers.RandomNormal(stddev=0.01)))
model.add(BatchNormalization())
#model.add(Dropout(0.2))
model.add(MaxPooling3D(pool_size=(2,2,2)))
model.add(Conv3D(64,kernel_size=(3,3,3),activation='relu',padding="same",kernel_initializer=initializers.RandomNormal(stddev=0.01)))
model.add(BatchNormalization())
#model.add(Dropout(0.2))
model.add(MaxPooling3D(pool_size=(2,2,2)))
model.add(Conv3D(128,kernel_size=(3,3,3),activation='relu',padding="same",kernel_initializer=initializers.RandomNormal(stddev=0.01)))
model.add(BatchNormalization())
#model.add(Dropout(0.2))
model.add(MaxPooling3D(pool_size=(2,2,2)))
model.add(Conv3D(256,kernel_size=(3,3,3),activation='relu',padding="same",kernel_initializer=initializers.RandomNormal(stddev=0.01)))
model.add(BatchNormalization())
model.add(MaxPooling3D(pool_size=(2,2,2)))
#model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(1024,activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(512,activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(5))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv3d (Conv3D)             (None, 100, 100, 100, 16  5504
                             )

 batch_normalization (BatchN  (None, 100, 100, 100, 16  64
 ormalization)               )

 max_pooling3d (MaxPooling3D  (None, 50, 50, 50, 16)   0
 )

 conv3d_1 (Conv3D)           (None, 50, 50, 50, 32)    13856

 batch_normalization_1 (Batc  (None, 50, 50, 50, 32)   128
 hNormalization)

 max_pooling3d_1 (MaxPooling  (None, 25, 25, 25, 32)   0
 3D)

 conv3d_2 (Conv3D)           (None, 25, 25, 25, 64)    55360

 batch_normalization_2 (Batc  (None, 25, 25, 25, 64)   256
 hNormalization)

 max_pooling3d_2 (MaxPooling  (None, 12, 12, 12, 64)   0
 3D)

 conv3d_3 (Conv3D)           (None, 12, 12, 12, 128)   221312

 batch_normalization_3 (Batc  (None, 12, 12, 12, 128)  512
 hNormalization)

 max_pooling3d_3 (MaxPooling  (None, 6, 6, 6, 128)     0
 3D)

 conv3d_4 (Conv3D)           (None, 6, 6, 6, 256)      884992

 batch_normalization_4 (Batc  (None, 6, 6, 6, 256)     1024
 hNormalization)

 max_pooling3d_4 (MaxPooling  (None, 3, 3, 3, 256)     0
 3D)

 flatten (Flatten)           (None, 6912)              0

 dense (Dense)               (None, 1024)              7078912

 batch_normalization_5 (Batc  (None, 1024)             4096
 hNormalization)

 dropout (Dropout)           (None, 1024)              0

 dense_1 (Dense)             (None, 512)               524800

 batch_normalization_6 (Batc  (None, 512)              2048
 hNormalization)

 dropout_1 (Dropout)         (None, 512)               0

 dense_2 (Dense)             (None, 5)                 2565

=================================================================
Total params: 8,795,429
Trainable params: 8,791,365
Non-trainable params: 4,064
_________________________________________________________________

In [19]:
import os
checkpoint_path="/content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-{epoch:03d}.ckpt"
#os.makedirs("/content/drive/MyDrive/image/porosity_filtering/training_5layers", exist_ok=True)
#ckpt_callback = ModelCheckpoint(filepath='/content/drive/MyDrive/image/porosity_filtering/training_model_5layers/weights.{epoch:02d}-{val_loss:.2f}.hdf5', monitor='val_loss')
cp_callback=ModelCheckpoint(filepath=checkpoint_path,save_weights_only=True,verbose=1)

In [ ]:
csvlogger=CSVLogger('/content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/Training_172.log')

In [20]:
opt = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(opt,loss='mse',metrics=['mse'])

In [ ]:
history=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger])

Epoch 1/200

<ipython-input-28-2be0de0fe96b>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger])

Epoch 1: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-001.ckpt
606/606 - 282s - loss: 1.8239 - mse: 1.8239 - val_loss: 18.9219 - val_mse: 18.9219 - 282s/epoch - 465ms/step
Epoch 2/200

Epoch 2: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-002.ckpt
606/606 - 261s - loss: 0.6441 - mse: 0.6441 - val_loss: 0.6326 - val_mse: 0.6326 - 261s/epoch - 430ms/step
Epoch 3/200

Epoch 3: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-003.ckpt
606/606 - 259s - loss: 0.4494 - mse: 0.4494 - val_loss: 0.9847 - val_mse: 0.9847 - 259s/epoch - 427ms/step
Epoch 4/200

Epoch 4: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-004.ckpt
606/606 - 261s - loss: 0.3955 - mse: 0.3955 - val_loss: 0.2893 - val_mse: 0.2893 - 261s/epoch - 430ms/step
Epoch 5/200

Epoch 5: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-005.ckpt
606/606 - 259s - loss: 0.3661 - mse: 0.3661 - val_loss: 0.8822 - val_mse: 0.8822 - 259s/epoch - 427ms/step
Epoch 6/200

Epoch 6: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-006.ckpt
606/606 - 261s - loss: 0.3407 - mse: 0.3407 - val_loss: 0.7284 - val_mse: 0.7284 - 261s/epoch - 430ms/step
Epoch 7/200

Epoch 7: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-007.ckpt
606/606 - 259s - loss: 0.3310 - mse: 0.3310 - val_loss: 0.6016 - val_mse: 0.6016 - 259s/epoch - 427ms/step
Epoch 8/200

Epoch 8: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-008.ckpt
606/606 - 260s - loss: 0.3113 - mse: 0.3113 - val_loss: 0.3240 - val_mse: 0.3240 - 260s/epoch - 430ms/step
Epoch 9/200

Epoch 9: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-009.ckpt
606/606 - 260s - loss: 0.2963 - mse: 0.2963 - val_loss: 0.2359 - val_mse: 0.2359 - 260s/epoch - 430ms/step
Epoch 10/200

Epoch 10: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-010.ckpt
606/606 - 259s - loss: 0.2819 - mse: 0.2819 - val_loss: 0.3750 - val_mse: 0.3750 - 259s/epoch - 427ms/step
Epoch 11/200

Epoch 11: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-011.ckpt
606/606 - 259s - loss: 0.2791 - mse: 0.2791 - val_loss: 2.0267 - val_mse: 2.0267 - 259s/epoch - 427ms/step
Epoch 12/200

Epoch 12: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-012.ckpt
606/606 - 259s - loss: 0.2908 - mse: 0.2908 - val_loss: 0.2383 - val_mse: 0.2383 - 259s/epoch - 427ms/step
Epoch 13/200

Epoch 13: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-013.ckpt
606/606 - 261s - loss: 0.2512 - mse: 0.2512 - val_loss: 0.6996 - val_mse: 0.6996 - 261s/epoch - 430ms/step
Epoch 14/200

Epoch 14: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-014.ckpt
606/606 - 261s - loss: 0.2469 - mse: 0.2469 - val_loss: 0.3263 - val_mse: 0.3263 - 261s/epoch - 430ms/step
Epoch 15/200

Epoch 15: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-015.ckpt
606/606 - 258s - loss: 0.2346 - mse: 0.2346 - val_loss: 0.1845 - val_mse: 0.1845 - 258s/epoch - 426ms/step
Epoch 16/200

Epoch 16: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-016.ckpt
606/606 - 258s - loss: 0.2191 - mse: 0.2191 - val_loss: 0.2026 - val_mse: 0.2026 - 258s/epoch - 426ms/step
Epoch 17/200

Epoch 17: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-017.ckpt
606/606 - 258s - loss: 0.2147 - mse: 0.2147 - val_loss: 0.2053 - val_mse: 0.2053 - 258s/epoch - 425ms/step
Epoch 18/200

Epoch 18: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-018.ckpt
606/606 - 260s - loss: 0.2087 - mse: 0.2087 - val_loss: 0.1699 - val_mse: 0.1699 - 260s/epoch - 429ms/step
Epoch 19/200

Epoch 19: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-019.ckpt
606/606 - 260s - loss: 0.2010 - mse: 0.2010 - val_loss: 0.2243 - val_mse: 0.2243 - 260s/epoch - 429ms/step
Epoch 20/200

Epoch 20: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-020.ckpt
606/606 - 260s - loss: 0.2006 - mse: 0.2006 - val_loss: 0.5359 - val_mse: 0.5359 - 260s/epoch - 429ms/step
Epoch 21/200

Epoch 21: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-021.ckpt
606/606 - 260s - loss: 0.1945 - mse: 0.1945 - val_loss: 0.2028 - val_mse: 0.2028 - 260s/epoch - 429ms/step
Epoch 22/200

Epoch 22: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-022.ckpt
606/606 - 260s - loss: 0.1897 - mse: 0.1897 - val_loss: 0.1668 - val_mse: 0.1668 - 260s/epoch - 429ms/step
Epoch 23/200

Epoch 23: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-023.ckpt
606/606 - 258s - loss: 0.1885 - mse: 0.1885 - val_loss: 0.2040 - val_mse: 0.2040 - 258s/epoch - 426ms/step
Epoch 24/200

Epoch 24: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-024.ckpt
606/606 - 259s - loss: 0.1855 - mse: 0.1855 - val_loss: 0.1988 - val_mse: 0.1988 - 259s/epoch - 428ms/step
Epoch 25/200

Epoch 25: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-025.ckpt
606/606 - 260s - loss: 0.1807 - mse: 0.1807 - val_loss: 0.1945 - val_mse: 0.1945 - 260s/epoch - 428ms/step
Epoch 26/200

Epoch 26: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-026.ckpt
606/606 - 258s - loss: 0.1786 - mse: 0.1786 - val_loss: 0.1482 - val_mse: 0.1482 - 258s/epoch - 425ms/step
Epoch 27/200

Epoch 27: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-027.ckpt
606/606 - 258s - loss: 0.1753 - mse: 0.1753 - val_loss: 0.1441 - val_mse: 0.1441 - 258s/epoch - 425ms/step
Epoch 28/200

Epoch 28: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-028.ckpt
606/606 - 260s - loss: 0.1720 - mse: 0.1720 - val_loss: 0.1517 - val_mse: 0.1517 - 260s/epoch - 429ms/step
Epoch 29/200

Epoch 29: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-029.ckpt
606/606 - 260s - loss: 0.1697 - mse: 0.1697 - val_loss: 0.1623 - val_mse: 0.1623 - 260s/epoch - 429ms/step
Epoch 30/200

Epoch 30: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-030.ckpt
606/606 - 260s - loss: 0.1673 - mse: 0.1673 - val_loss: 0.1609 - val_mse: 0.1609 - 260s/epoch - 430ms/step
Epoch 31/200

Epoch 31: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-031.ckpt
606/606 - 258s - loss: 0.1681 - mse: 0.1681 - val_loss: 0.2271 - val_mse: 0.2271 - 258s/epoch - 425ms/step
Epoch 32/200

Epoch 32: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-032.ckpt
606/606 - 259s - loss: 0.1672 - mse: 0.1672 - val_loss: 0.1491 - val_mse: 0.1491 - 259s/epoch - 428ms/step
Epoch 33/200

Epoch 33: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-033.ckpt
606/606 - 260s - loss: 0.1622 - mse: 0.1622 - val_loss: 0.1433 - val_mse: 0.1433 - 260s/epoch - 429ms/step
Epoch 34/200

Epoch 34: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-034.ckpt
606/606 - 260s - loss: 0.1619 - mse: 0.1619 - val_loss: 0.1324 - val_mse: 0.1324 - 260s/epoch - 428ms/step
Epoch 35/200

Epoch 35: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-035.ckpt
606/606 - 260s - loss: 0.1598 - mse: 0.1598 - val_loss: 0.1660 - val_mse: 0.1660 - 260s/epoch - 429ms/step
Epoch 36/200

Epoch 36: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-036.ckpt
606/606 - 260s - loss: 0.1590 - mse: 0.1590 - val_loss: 0.1548 - val_mse: 0.1548 - 260s/epoch - 429ms/step
Epoch 37/200

Epoch 37: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-037.ckpt
606/606 - 258s - loss: 0.1594 - mse: 0.1594 - val_loss: 0.1384 - val_mse: 0.1384 - 258s/epoch - 425ms/step
Epoch 38/200

Epoch 38: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-038.ckpt
606/606 - 259s - loss: 0.1562 - mse: 0.1562 - val_loss: 0.1374 - val_mse: 0.1374 - 259s/epoch - 428ms/step
Epoch 39/200

Epoch 39: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-039.ckpt
606/606 - 260s - loss: 0.1552 - mse: 0.1552 - val_loss: 0.1427 - val_mse: 0.1427 - 260s/epoch - 428ms/step
Epoch 40/200

Epoch 40: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-040.ckpt
606/606 - 258s - loss: 0.1550 - mse: 0.1550 - val_loss: 0.1262 - val_mse: 0.1262 - 258s/epoch - 425ms/step
Epoch 41/200

Epoch 41: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-041.ckpt
606/606 - 259s - loss: 0.1540 - mse: 0.1540 - val_loss: 0.1730 - val_mse: 0.1730 - 259s/epoch - 428ms/step
Epoch 42/200

Epoch 42: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-042.ckpt
606/606 - 258s - loss: 0.1514 - mse: 0.1514 - val_loss: 0.1445 - val_mse: 0.1445 - 258s/epoch - 425ms/step
Epoch 43/200

Epoch 43: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-043.ckpt
606/606 - 257s - loss: 0.1556 - mse: 0.1556 - val_loss: 0.2010 - val_mse: 0.2010 - 257s/epoch - 425ms/step
Epoch 44/200

Epoch 44: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-044.ckpt
606/606 - 259s - loss: 0.1523 - mse: 0.1523 - val_loss: 0.1349 - val_mse: 0.1349 - 259s/epoch - 428ms/step
Epoch 45/200

Epoch 45: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-045.ckpt
606/606 - 258s - loss: 0.1496 - mse: 0.1496 - val_loss: 0.2221 - val_mse: 0.2221 - 258s/epoch - 425ms/step
Epoch 46/200

Epoch 46: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-046.ckpt
606/606 - 258s - loss: 0.1490 - mse: 0.1490 - val_loss: 0.1373 - val_mse: 0.1373 - 258s/epoch - 426ms/step
Epoch 47/200

Epoch 47: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-047.ckpt
606/606 - 260s - loss: 0.1510 - mse: 0.1510 - val_loss: 0.8006 - val_mse: 0.8006 - 260s/epoch - 428ms/step
Epoch 48/200

Epoch 48: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-048.ckpt
606/606 - 258s - loss: 0.1502 - mse: 0.1502 - val_loss: 0.4532 - val_mse: 0.4532 - 258s/epoch - 426ms/step
Epoch 49/200

Epoch 49: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-049.ckpt
606/606 - 258s - loss: 0.1484 - mse: 0.1484 - val_loss: 0.2630 - val_mse: 0.2630 - 258s/epoch - 426ms/step
Epoch 50/200

Epoch 50: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-050.ckpt
606/606 - 260s - loss: 0.1469 - mse: 0.1469 - val_loss: 0.3879 - val_mse: 0.3879 - 260s/epoch - 428ms/step
Epoch 51/200

Epoch 51: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-051.ckpt
606/606 - 258s - loss: 0.1474 - mse: 0.1474 - val_loss: 0.1472 - val_mse: 0.1472 - 258s/epoch - 425ms/step
Epoch 52/200

Epoch 52: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-052.ckpt
606/606 - 258s - loss: 0.1465 - mse: 0.1465 - val_loss: 0.2429 - val_mse: 0.2429 - 258s/epoch - 425ms/step
Epoch 53/200

In [ ]:
wieght='/content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-046.ckpt'
model.load_weights(wieght)

In [ ]:
history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=46)

Epoch 47/200

<ipython-input-24-6c890e2714d6>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=46)

Epoch 47: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-047.ckpt
606/606 - 272s - loss: 0.1501 - mse: 0.1501 - val_loss: 0.5371 - val_mse: 0.5371 - 272s/epoch - 450ms/step
Epoch 48/200

Epoch 48: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-048.ckpt
606/606 - 248s - loss: 0.1493 - mse: 0.1493 - val_loss: 0.1498 - val_mse: 0.1498 - 248s/epoch - 409ms/step
Epoch 49/200

Epoch 49: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-049.ckpt
606/606 - 248s - loss: 0.1486 - mse: 0.1486 - val_loss: 0.2293 - val_mse: 0.2293 - 248s/epoch - 409ms/step
Epoch 50/200

Epoch 50: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-050.ckpt
606/606 - 244s - loss: 0.1478 - mse: 0.1478 - val_loss: 0.5439 - val_mse: 0.5439 - 244s/epoch - 403ms/step
Epoch 51/200

Epoch 51: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-051.ckpt
606/606 - 245s - loss: 0.1460 - mse: 0.1460 - val_loss: 0.8212 - val_mse: 0.8212 - 245s/epoch - 404ms/step
Epoch 52/200

Epoch 52: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-052.ckpt
606/606 - 244s - loss: 0.1466 - mse: 0.1466 - val_loss: 0.1937 - val_mse: 0.1937 - 244s/epoch - 403ms/step
Epoch 53/200

Epoch 53: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-053.ckpt
606/606 - 247s - loss: 0.1456 - mse: 0.1456 - val_loss: 0.2127 - val_mse: 0.2127 - 247s/epoch - 408ms/step
Epoch 54/200

Epoch 54: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-054.ckpt
606/606 - 247s - loss: 0.1454 - mse: 0.1454 - val_loss: 0.4010 - val_mse: 0.4010 - 247s/epoch - 408ms/step
Epoch 55/200

Epoch 55: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-055.ckpt
606/606 - 247s - loss: 0.1445 - mse: 0.1445 - val_loss: 0.7184 - val_mse: 0.7184 - 247s/epoch - 408ms/step
Epoch 56/200

Epoch 56: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-056.ckpt
606/606 - 247s - loss: 0.1449 - mse: 0.1449 - val_loss: 0.3275 - val_mse: 0.3275 - 247s/epoch - 408ms/step
Epoch 57/200

Epoch 57: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-057.ckpt
606/606 - 247s - loss: 0.1445 - mse: 0.1445 - val_loss: 0.5524 - val_mse: 0.5524 - 247s/epoch - 408ms/step
Epoch 58/200

Epoch 58: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-058.ckpt
606/606 - 244s - loss: 0.1448 - mse: 0.1448 - val_loss: 0.1487 - val_mse: 0.1487 - 244s/epoch - 403ms/step
Epoch 59/200

Epoch 59: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-059.ckpt
606/606 - 247s - loss: 0.1437 - mse: 0.1437 - val_loss: 0.1237 - val_mse: 0.1237 - 247s/epoch - 408ms/step
Epoch 60/200

Epoch 60: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-060.ckpt
606/606 - 244s - loss: 0.1436 - mse: 0.1436 - val_loss: 0.1150 - val_mse: 0.1150 - 244s/epoch - 403ms/step
Epoch 61/200

Epoch 61: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-061.ckpt
606/606 - 247s - loss: 0.1433 - mse: 0.1433 - val_loss: 0.2592 - val_mse: 0.2592 - 247s/epoch - 407ms/step
Epoch 62/200

Epoch 62: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-062.ckpt
606/606 - 244s - loss: 0.1432 - mse: 0.1432 - val_loss: 0.2253 - val_mse: 0.2253 - 244s/epoch - 403ms/step
Epoch 63/200

Epoch 63: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-063.ckpt
606/606 - 247s - loss: 0.1407 - mse: 0.1407 - val_loss: 0.1381 - val_mse: 0.1381 - 247s/epoch - 408ms/step
Epoch 64/200

Epoch 64: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-064.ckpt
606/606 - 244s - loss: 0.1396 - mse: 0.1396 - val_loss: 0.2206 - val_mse: 0.2206 - 244s/epoch - 403ms/step
Epoch 65/200

Epoch 65: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-065.ckpt
606/606 - 244s - loss: 0.1422 - mse: 0.1422 - val_loss: 0.4397 - val_mse: 0.4397 - 244s/epoch - 403ms/step
Epoch 66/200

Epoch 66: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-066.ckpt
606/606 - 247s - loss: 0.1414 - mse: 0.1414 - val_loss: 1.4157 - val_mse: 1.4157 - 247s/epoch - 408ms/step
Epoch 67/200

In [ ]:
wieght='/content/drive/MyDrive/image/porosity_filtering/kernel_dimension/training_model_weights/cp-081.ckpt'
model.load_weights(wieght)

In [ ]:
history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=82)

<ipython-input-23-6fb104b5ec33>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=82)

Epoch 83/200

Epoch 83: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-083.ckpt
606/606 - 276s - loss: 0.1373 - mse: 0.1373 - val_loss: 0.3799 - val_mse: 0.3799 - 276s/epoch - 455ms/step
Epoch 84/200

Epoch 84: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-084.ckpt
606/606 - 250s - loss: 0.1380 - mse: 0.1380 - val_loss: 0.1456 - val_mse: 0.1456 - 250s/epoch - 412ms/step
Epoch 85/200

Epoch 85: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-085.ckpt
606/606 - 250s - loss: 0.1367 - mse: 0.1367 - val_loss: 0.1226 - val_mse: 0.1226 - 250s/epoch - 413ms/step
Epoch 86/200

Epoch 86: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-086.ckpt
606/606 - 250s - loss: 0.1367 - mse: 0.1367 - val_loss: 0.1230 - val_mse: 0.1230 - 250s/epoch - 412ms/step
Epoch 87/200

Epoch 87: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-087.ckpt
606/606 - 247s - loss: 0.1368 - mse: 0.1368 - val_loss: 0.1225 - val_mse: 0.1225 - 247s/epoch - 408ms/step
Epoch 88/200

Epoch 88: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-088.ckpt
606/606 - 250s - loss: 0.1367 - mse: 0.1367 - val_loss: 0.1178 - val_mse: 0.1178 - 250s/epoch - 412ms/step
Epoch 89/200

Epoch 89: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-089.ckpt
606/606 - 248s - loss: 0.1368 - mse: 0.1368 - val_loss: 0.1225 - val_mse: 0.1225 - 248s/epoch - 409ms/step
Epoch 90/200

Epoch 90: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-090.ckpt
606/606 - 247s - loss: 0.1355 - mse: 0.1355 - val_loss: 0.2238 - val_mse: 0.2238 - 247s/epoch - 407ms/step
Epoch 91/200

Epoch 91: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-091.ckpt
606/606 - 250s - loss: 0.1350 - mse: 0.1350 - val_loss: 0.1221 - val_mse: 0.1221 - 250s/epoch - 412ms/step
Epoch 92/200

Epoch 92: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-092.ckpt
606/606 - 250s - loss: 0.1361 - mse: 0.1361 - val_loss: 0.1126 - val_mse: 0.1126 - 250s/epoch - 412ms/step
Epoch 93/200

Epoch 93: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-093.ckpt
606/606 - 250s - loss: 0.1364 - mse: 0.1364 - val_loss: 0.1111 - val_mse: 0.1111 - 250s/epoch - 412ms/step
Epoch 94/200

Epoch 94: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-094.ckpt
606/606 - 247s - loss: 0.1363 - mse: 0.1363 - val_loss: 0.1154 - val_mse: 0.1154 - 247s/epoch - 407ms/step
Epoch 95/200

Epoch 95: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-095.ckpt
606/606 - 247s - loss: 0.1352 - mse: 0.1352 - val_loss: 0.1127 - val_mse: 0.1127 - 247s/epoch - 407ms/step
Epoch 96/200

Epoch 96: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-096.ckpt
606/606 - 247s - loss: 0.1351 - mse: 0.1351 - val_loss: 0.1802 - val_mse: 0.1802 - 247s/epoch - 408ms/step
Epoch 97/200

Epoch 97: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-097.ckpt
606/606 - 250s - loss: 0.1364 - mse: 0.1364 - val_loss: 0.1147 - val_mse: 0.1147 - 250s/epoch - 412ms/step
Epoch 98/200

Epoch 98: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-098.ckpt
606/606 - 250s - loss: 0.1345 - mse: 0.1345 - val_loss: 0.1162 - val_mse: 0.1162 - 250s/epoch - 412ms/step
Epoch 99/200

Epoch 99: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-099.ckpt
606/606 - 250s - loss: 0.1341 - mse: 0.1341 - val_loss: 0.1181 - val_mse: 0.1181 - 250s/epoch - 412ms/step
Epoch 100/200

Epoch 100: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-100.ckpt
606/606 - 250s - loss: 0.1346 - mse: 0.1346 - val_loss: 0.1256 - val_mse: 0.1256 - 250s/epoch - 412ms/step
Epoch 101/200

Epoch 101: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-101.ckpt
606/606 - 250s - loss: 0.1346 - mse: 0.1346 - val_loss: 0.1909 - val_mse: 0.1909 - 250s/epoch - 412ms/step
Epoch 102/200

Epoch 102: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-102.ckpt
606/606 - 250s - loss: 0.1351 - mse: 0.1351 - val_loss: 0.1303 - val_mse: 0.1303 - 250s/epoch - 413ms/step
Epoch 103/200

Epoch 103: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-103.ckpt
606/606 - 247s - loss: 0.1346 - mse: 0.1346 - val_loss: 0.1089 - val_mse: 0.1089 - 247s/epoch - 407ms/step
Epoch 104/200

Epoch 104: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-104.ckpt
606/606 - 247s - loss: 0.1350 - mse: 0.1350 - val_loss: 0.1121 - val_mse: 0.1121 - 247s/epoch - 408ms/step
Epoch 105/200

Epoch 105: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-105.ckpt
606/606 - 247s - loss: 0.1341 - mse: 0.1341 - val_loss: 0.1668 - val_mse: 0.1668 - 247s/epoch - 407ms/step
Epoch 106/200

Epoch 106: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-106.ckpt
606/606 - 247s - loss: 0.1326 - mse: 0.1326 - val_loss: 0.1150 - val_mse: 0.1150 - 247s/epoch - 407ms/step
Epoch 107/200

Epoch 107: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-107.ckpt
606/606 - 247s - loss: 0.1332 - mse: 0.1332 - val_loss: 0.1487 - val_mse: 0.1487 - 247s/epoch - 407ms/step
Epoch 108/200

Epoch 108: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-108.ckpt
606/606 - 249s - loss: 0.1341 - mse: 0.1341 - val_loss: 0.1081 - val_mse: 0.1081 - 249s/epoch - 412ms/step
Epoch 109/200

Epoch 109: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-109.ckpt
606/606 - 247s - loss: 0.1339 - mse: 0.1339 - val_loss: 0.1133 - val_mse: 0.1133 - 247s/epoch - 408ms/step
Epoch 110/200

Epoch 110: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-110.ckpt
606/606 - 250s - loss: 0.1343 - mse: 0.1343 - val_loss: 0.1111 - val_mse: 0.1111 - 250s/epoch - 412ms/step
Epoch 111/200

Epoch 111: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-111.ckpt
606/606 - 251s - loss: 0.1334 - mse: 0.1334 - val_loss: 0.1203 - val_mse: 0.1203 - 251s/epoch - 414ms/step
Epoch 112/200

Epoch 112: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-112.ckpt
606/606 - 250s - loss: 0.1340 - mse: 0.1340 - val_loss: 0.1140 - val_mse: 0.1140 - 250s/epoch - 412ms/step
Epoch 113/200

Epoch 113: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-113.ckpt
606/606 - 250s - loss: 0.1321 - mse: 0.1321 - val_loss: 0.1092 - val_mse: 0.1092 - 250s/epoch - 412ms/step
Epoch 114/200

Epoch 114: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-114.ckpt
606/606 - 250s - loss: 0.1339 - mse: 0.1339 - val_loss: 0.1121 - val_mse: 0.1121 - 250s/epoch - 413ms/step
Epoch 115/200

Epoch 115: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-115.ckpt
606/606 - 250s - loss: 0.1330 - mse: 0.1330 - val_loss: 0.1099 - val_mse: 0.1099 - 250s/epoch - 412ms/step
Epoch 116/200

Epoch 116: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-116.ckpt
606/606 - 247s - loss: 0.1335 - mse: 0.1335 - val_loss: 0.1163 - val_mse: 0.1163 - 247s/epoch - 408ms/step
Epoch 117/200

Epoch 117: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-117.ckpt
606/606 - 247s - loss: 0.1321 - mse: 0.1321 - val_loss: 0.1105 - val_mse: 0.1105 - 247s/epoch - 407ms/step
Epoch 118/200

Epoch 118: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-118.ckpt
606/606 - 250s - loss: 0.1336 - mse: 0.1336 - val_loss: 0.1100 - val_mse: 0.1100 - 250s/epoch - 412ms/step
Epoch 119/200

Epoch 119: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-119.ckpt
606/606 - 250s - loss: 0.1325 - mse: 0.1325 - val_loss: 2.1507 - val_mse: 2.1507 - 250s/epoch - 412ms/step
Epoch 120/200

Epoch 120: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-120.ckpt
606/606 - 250s - loss: 0.1329 - mse: 0.1329 - val_loss: 0.1082 - val_mse: 0.1082 - 250s/epoch - 412ms/step
Epoch 121/200

Epoch 121: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-121.ckpt
606/606 - 247s - loss: 0.1331 - mse: 0.1331 - val_loss: 0.1131 - val_mse: 0.1131 - 247s/epoch - 408ms/step
Epoch 122/200

Epoch 122: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-122.ckpt
606/606 - 247s - loss: 0.1343 - mse: 0.1343 - val_loss: 0.1364 - val_mse: 0.1364 - 247s/epoch - 408ms/step
Epoch 123/200

Epoch 123: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-123.ckpt
606/606 - 247s - loss: 0.1312 - mse: 0.1312 - val_loss: 0.1173 - val_mse: 0.1173 - 247s/epoch - 408ms/step
Epoch 124/200

Epoch 124: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-124.ckpt
606/606 - 250s - loss: 0.1324 - mse: 0.1324 - val_loss: 0.1069 - val_mse: 0.1069 - 250s/epoch - 412ms/step
Epoch 125/200

Epoch 125: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-125.ckpt
606/606 - 250s - loss: 0.1328 - mse: 0.1328 - val_loss: 0.1090 - val_mse: 0.1090 - 250s/epoch - 412ms/step
Epoch 126/200

Epoch 126: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-126.ckpt
606/606 - 250s - loss: 0.1323 - mse: 0.1323 - val_loss: 0.1094 - val_mse: 0.1094 - 250s/epoch - 412ms/step
Epoch 127/200

Epoch 127: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-127.ckpt
606/606 - 250s - loss: 0.1318 - mse: 0.1318 - val_loss: 0.1102 - val_mse: 0.1102 - 250s/epoch - 412ms/step
Epoch 128/200

Epoch 128: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-128.ckpt
606/606 - 247s - loss: 0.1317 - mse: 0.1317 - val_loss: 0.1090 - val_mse: 0.1090 - 247s/epoch - 408ms/step
Epoch 129/200

Epoch 129: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-129.ckpt
606/606 - 250s - loss: 0.1310 - mse: 0.1310 - val_loss: 1.7145 - val_mse: 1.7145 - 250s/epoch - 412ms/step
Epoch 130/200

Epoch 130: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-130.ckpt
606/606 - 250s - loss: 0.1322 - mse: 0.1322 - val_loss: 4.7772 - val_mse: 4.7772 - 250s/epoch - 412ms/step
Epoch 131/200

Epoch 131: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-131.ckpt
606/606 - 247s - loss: 0.1319 - mse: 0.1319 - val_loss: 0.1116 - val_mse: 0.1116 - 247s/epoch - 408ms/step
Epoch 132/200

Epoch 132: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-132.ckpt
606/606 - 250s - loss: 0.1314 - mse: 0.1314 - val_loss: 0.1102 - val_mse: 0.1102 - 250s/epoch - 412ms/step
Epoch 133/200

Epoch 133: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-133.ckpt
606/606 - 247s - loss: 0.1326 - mse: 0.1326 - val_loss: 0.1075 - val_mse: 0.1075 - 247s/epoch - 407ms/step
Epoch 134/200

Epoch 134: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-134.ckpt
606/606 - 250s - loss: 0.1322 - mse: 0.1322 - val_loss: 0.1081 - val_mse: 0.1081 - 250s/epoch - 412ms/step
Epoch 135/200

Epoch 135: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-135.ckpt
606/606 - 247s - loss: 0.1322 - mse: 0.1322 - val_loss: 0.1172 - val_mse: 0.1172 - 247s/epoch - 408ms/step
Epoch 136/200

Epoch 136: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-136.ckpt
606/606 - 250s - loss: 0.1311 - mse: 0.1311 - val_loss: 12.0791 - val_mse: 12.0791 - 250s/epoch - 412ms/step
Epoch 137/200

Epoch 137: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-137.ckpt
606/606 - 247s - loss: 0.1324 - mse: 0.1324 - val_loss: 0.1072 - val_mse: 0.1072 - 247s/epoch - 408ms/step
Epoch 138/200

Epoch 138: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-138.ckpt
606/606 - 250s - loss: 0.1321 - mse: 0.1321 - val_loss: 722.0319 - val_mse: 722.0319 - 250s/epoch - 412ms/step
Epoch 139/200

Epoch 139: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-139.ckpt

FailedPreconditionError: ignored

In [ ]:
wieght='/content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-138.ckpt'
model.load_weights(wieght)

In [ ]:
history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=138)

<ipython-input-23-ddd98064d07e>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=138)

Epoch 139/200

Epoch 139: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-139.ckpt
606/606 - 283s - loss: 0.1309 - mse: 0.1309 - val_loss: 0.1088 - val_mse: 0.1088 - 283s/epoch - 466ms/step
Epoch 140/200

Epoch 140: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-140.ckpt
606/606 - 257s - loss: 0.1320 - mse: 0.1320 - val_loss: 57.4193 - val_mse: 57.4193 - 257s/epoch - 425ms/step
Epoch 141/200

Epoch 141: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-141.ckpt
606/606 - 258s - loss: 0.1313 - mse: 0.1313 - val_loss: 4.3348 - val_mse: 4.3348 - 258s/epoch - 425ms/step
Epoch 142/200

Epoch 142: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-142.ckpt
606/606 - 258s - loss: 0.1300 - mse: 0.1300 - val_loss: 0.1064 - val_mse: 0.1064 - 258s/epoch - 425ms/step
Epoch 143/200

Epoch 143: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-143.ckpt
606/606 - 258s - loss: 0.1303 - mse: 0.1303 - val_loss: 0.1056 - val_mse: 0.1056 - 258s/epoch - 426ms/step
Epoch 144/200

Epoch 144: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-144.ckpt
606/606 - 256s - loss: 0.1312 - mse: 0.1312 - val_loss: 0.1119 - val_mse: 0.1119 - 256s/epoch - 423ms/step
Epoch 145/200

Epoch 145: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-145.ckpt
606/606 - 258s - loss: 0.1304 - mse: 0.1304 - val_loss: 0.1148 - val_mse: 0.1148 - 258s/epoch - 425ms/step
Epoch 146/200

Epoch 146: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-146.ckpt
606/606 - 256s - loss: 0.1304 - mse: 0.1304 - val_loss: 0.1045 - val_mse: 0.1045 - 256s/epoch - 422ms/step
Epoch 147/200

Epoch 147: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-147.ckpt
606/606 - 256s - loss: 0.1302 - mse: 0.1302 - val_loss: 0.1068 - val_mse: 0.1068 - 256s/epoch - 422ms/step
Epoch 148/200

Epoch 148: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-148.ckpt
606/606 - 256s - loss: 0.1310 - mse: 0.1310 - val_loss: 0.1057 - val_mse: 0.1057 - 256s/epoch - 422ms/step
Epoch 149/200

Epoch 149: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-149.ckpt
606/606 - 255s - loss: 0.1297 - mse: 0.1297 - val_loss: 0.1076 - val_mse: 0.1076 - 255s/epoch - 422ms/step
Epoch 150/200

Epoch 150: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-150.ckpt
606/606 - 256s - loss: 0.1298 - mse: 0.1298 - val_loss: 0.1046 - val_mse: 0.1046 - 256s/epoch - 422ms/step
Epoch 151/200

Epoch 151: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-151.ckpt
606/606 - 256s - loss: 0.1311 - mse: 0.1311 - val_loss: 0.1076 - val_mse: 0.1076 - 256s/epoch - 422ms/step
Epoch 152/200

Epoch 152: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-152.ckpt
606/606 - 258s - loss: 0.1304 - mse: 0.1304 - val_loss: 0.1057 - val_mse: 0.1057 - 258s/epoch - 425ms/step
Epoch 153/200

Epoch 153: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-153.ckpt
606/606 - 256s - loss: 0.1295 - mse: 0.1295 - val_loss: 0.1112 - val_mse: 0.1112 - 256s/epoch - 422ms/step
Epoch 154/200

Epoch 154: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-154.ckpt
606/606 - 258s - loss: 0.1306 - mse: 0.1306 - val_loss: 0.1039 - val_mse: 0.1039 - 258s/epoch - 425ms/step
Epoch 155/200

Epoch 155: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-155.ckpt
606/606 - 256s - loss: 0.1302 - mse: 0.1302 - val_loss: 0.1091 - val_mse: 0.1091 - 256s/epoch - 422ms/step
Epoch 156/200

Epoch 156: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-156.ckpt
606/606 - 255s - loss: 0.1304 - mse: 0.1304 - val_loss: 0.1096 - val_mse: 0.1096 - 255s/epoch - 421ms/step
Epoch 157/200

Epoch 157: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-157.ckpt
606/606 - 258s - loss: 0.1312 - mse: 0.1312 - val_loss: 0.1072 - val_mse: 0.1072 - 258s/epoch - 425ms/step
Epoch 158/200

Epoch 158: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-158.ckpt
606/606 - 255s - loss: 0.1304 - mse: 0.1304 - val_loss: 0.1032 - val_mse: 0.1032 - 255s/epoch - 422ms/step
Epoch 159/200

Epoch 159: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-159.ckpt
606/606 - 257s - loss: 0.1293 - mse: 0.1293 - val_loss: 0.1073 - val_mse: 0.1073 - 257s/epoch - 425ms/step
Epoch 160/200

Epoch 160: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-160.ckpt
606/606 - 256s - loss: 0.1290 - mse: 0.1290 - val_loss: 0.1062 - val_mse: 0.1062 - 256s/epoch - 422ms/step
Epoch 161/200

Epoch 161: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-161.ckpt
606/606 - 256s - loss: 0.1299 - mse: 0.1299 - val_loss: 0.1106 - val_mse: 0.1106 - 256s/epoch - 422ms/step
Epoch 162/200

Epoch 162: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-162.ckpt
606/606 - 256s - loss: 0.1304 - mse: 0.1304 - val_loss: 0.1058 - val_mse: 0.1058 - 256s/epoch - 422ms/step
Epoch 163/200

Epoch 163: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-163.ckpt
606/606 - 258s - loss: 0.1290 - mse: 0.1290 - val_loss: 0.1098 - val_mse: 0.1098 - 258s/epoch - 425ms/step
Epoch 164/200

Epoch 164: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-164.ckpt
606/606 - 257s - loss: 0.1290 - mse: 0.1290 - val_loss: 0.1088 - val_mse: 0.1088 - 257s/epoch - 425ms/step
Epoch 165/200

Epoch 165: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-165.ckpt
606/606 - 255s - loss: 0.1300 - mse: 0.1300 - val_loss: 0.1064 - val_mse: 0.1064 - 255s/epoch - 421ms/step
Epoch 166/200

Epoch 166: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-166.ckpt
606/606 - 257s - loss: 0.1293 - mse: 0.1293 - val_loss: 0.1245 - val_mse: 0.1245 - 257s/epoch - 425ms/step
Epoch 167/200

Epoch 167: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-167.ckpt
606/606 - 258s - loss: 0.1296 - mse: 0.1296 - val_loss: 0.1084 - val_mse: 0.1084 - 258s/epoch - 426ms/step
Epoch 168/200

Epoch 168: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-168.ckpt
606/606 - 258s - loss: 0.1302 - mse: 0.1302 - val_loss: 0.1068 - val_mse: 0.1068 - 258s/epoch - 425ms/step
Epoch 169/200

Epoch 169: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-169.ckpt
606/606 - 258s - loss: 0.1294 - mse: 0.1294 - val_loss: 0.1085 - val_mse: 0.1085 - 258s/epoch - 425ms/step
Epoch 170/200

Epoch 170: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-170.ckpt
606/606 - 256s - loss: 0.1297 - mse: 0.1297 - val_loss: 0.1071 - val_mse: 0.1071 - 256s/epoch - 422ms/step
Epoch 171/200

Epoch 171: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-171.ckpt
606/606 - 256s - loss: 0.1299 - mse: 0.1299 - val_loss: 0.1059 - val_mse: 0.1059 - 256s/epoch - 422ms/step
Epoch 172/200

Epoch 172: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-172.ckpt
606/606 - 258s - loss: 0.1291 - mse: 0.1291 - val_loss: 0.1079 - val_mse: 0.1079 - 258s/epoch - 425ms/step
Epoch 173/200

In [ ]:
wieght='/content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-164.ckpt'
model.load_weights(wieght)

In [ ]:
history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=164)

<ipython-input-24-45d2c2340de4>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=164)

Epoch 165/200

Epoch 165: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-165.ckpt
606/606 - 288s - loss: 0.1297 - mse: 0.1297 - val_loss: 0.1061 - val_mse: 0.1061 - 288s/epoch - 475ms/step
Epoch 166/200

Epoch 166: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-166.ckpt
606/606 - 261s - loss: 0.1298 - mse: 0.1298 - val_loss: 0.1060 - val_mse: 0.1060 - 261s/epoch - 431ms/step
Epoch 167/200

Epoch 167: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-167.ckpt
606/606 - 260s - loss: 0.1305 - mse: 0.1305 - val_loss: 0.1041 - val_mse: 0.1041 - 260s/epoch - 429ms/step
Epoch 168/200

Epoch 168: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-168.ckpt
606/606 - 262s - loss: 0.1292 - mse: 0.1292 - val_loss: 0.1061 - val_mse: 0.1061 - 262s/epoch - 432ms/step
Epoch 169/200

Epoch 169: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-169.ckpt
606/606 - 262s - loss: 0.1297 - mse: 0.1297 - val_loss: 0.1095 - val_mse: 0.1095 - 262s/epoch - 432ms/step
Epoch 170/200

Epoch 170: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-170.ckpt
606/606 - 262s - loss: 0.1290 - mse: 0.1290 - val_loss: 0.1071 - val_mse: 0.1071 - 262s/epoch - 432ms/step
Epoch 171/200

Epoch 171: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-171.ckpt
606/606 - 262s - loss: 0.1297 - mse: 0.1297 - val_loss: 0.1073 - val_mse: 0.1073 - 262s/epoch - 432ms/step
Epoch 172/200

In [ ]:
wieght='/content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-171.ckpt'
model.load_weights(wieght)

In [ ]:
history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=171)

<ipython-input-23-c76bae422c60>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=171)

Epoch 172/200

Epoch 172: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-172.ckpt
606/606 - 278s - loss: 0.1291 - mse: 0.1291 - val_loss: 0.1170 - val_mse: 0.1170 - 278s/epoch - 459ms/step
Epoch 173/200

Epoch 173: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-173.ckpt
606/606 - 250s - loss: 0.1295 - mse: 0.1295 - val_loss: 0.1054 - val_mse: 0.1054 - 250s/epoch - 412ms/step
Epoch 174/200

Epoch 174: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-174.ckpt
606/606 - 249s - loss: 0.1291 - mse: 0.1291 - val_loss: 0.1111 - val_mse: 0.1111 - 249s/epoch - 411ms/step
Epoch 175/200

Epoch 175: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-175.ckpt
606/606 - 253s - loss: 0.1300 - mse: 0.1300 - val_loss: 0.1104 - val_mse: 0.1104 - 253s/epoch - 417ms/step
Epoch 176/200

Epoch 176: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-176.ckpt
606/606 - 249s - loss: 0.1296 - mse: 0.1296 - val_loss: 0.1054 - val_mse: 0.1054 - 249s/epoch - 410ms/step
Epoch 177/200

Epoch 177: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-177.ckpt
606/606 - 251s - loss: 0.1288 - mse: 0.1288 - val_loss: 0.1073 - val_mse: 0.1073 - 251s/epoch - 414ms/step
Epoch 178/200

Epoch 178: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-178.ckpt
606/606 - 251s - loss: 0.1293 - mse: 0.1293 - val_loss: 0.1055 - val_mse: 0.1055 - 251s/epoch - 414ms/step
Epoch 179/200

Epoch 179: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-179.ckpt
606/606 - 251s - loss: 0.1292 - mse: 0.1292 - val_loss: 0.1051 - val_mse: 0.1051 - 251s/epoch - 414ms/step
Epoch 180/200

Epoch 180: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-180.ckpt
606/606 - 251s - loss: 0.1295 - mse: 0.1295 - val_loss: 0.1056 - val_mse: 0.1056 - 251s/epoch - 415ms/step
Epoch 181/200

Epoch 181: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-181.ckpt
606/606 - 251s - loss: 0.1290 - mse: 0.1290 - val_loss: 0.1106 - val_mse: 0.1106 - 251s/epoch - 414ms/step
Epoch 182/200

Epoch 182: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-182.ckpt
606/606 - 251s - loss: 0.1286 - mse: 0.1286 - val_loss: 0.1076 - val_mse: 0.1076 - 251s/epoch - 414ms/step
Epoch 183/200

Epoch 183: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-183.ckpt
606/606 - 251s - loss: 0.1285 - mse: 0.1285 - val_loss: 0.1068 - val_mse: 0.1068 - 251s/epoch - 414ms/step
Epoch 184/200

Epoch 184: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-184.ckpt
606/606 - 251s - loss: 0.1276 - mse: 0.1276 - val_loss: 0.1034 - val_mse: 0.1034 - 251s/epoch - 414ms/step
Epoch 185/200

Epoch 185: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-185.ckpt
606/606 - 251s - loss: 0.1292 - mse: 0.1292 - val_loss: 0.1104 - val_mse: 0.1104 - 251s/epoch - 414ms/step
Epoch 186/200

Epoch 186: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-186.ckpt
606/606 - 251s - loss: 0.1290 - mse: 0.1290 - val_loss: 0.1023 - val_mse: 0.1023 - 251s/epoch - 415ms/step
Epoch 187/200

Epoch 187: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-187.ckpt
606/606 - 251s - loss: 0.1293 - mse: 0.1293 - val_loss: 0.1049 - val_mse: 0.1049 - 251s/epoch - 414ms/step
Epoch 188/200

Epoch 188: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-188.ckpt
606/606 - 251s - loss: 0.1277 - mse: 0.1277 - val_loss: 0.1100 - val_mse: 0.1100 - 251s/epoch - 414ms/step
Epoch 189/200

Epoch 189: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-189.ckpt
606/606 - 248s - loss: 0.1297 - mse: 0.1297 - val_loss: 0.1113 - val_mse: 0.1113 - 248s/epoch - 410ms/step
Epoch 190/200

Epoch 190: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-190.ckpt
606/606 - 251s - loss: 0.1284 - mse: 0.1284 - val_loss: 0.1060 - val_mse: 0.1060 - 251s/epoch - 414ms/step
Epoch 191/200

Epoch 191: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-191.ckpt
606/606 - 251s - loss: 0.1285 - mse: 0.1285 - val_loss: 0.1128 - val_mse: 0.1128 - 251s/epoch - 414ms/step
Epoch 192/200

Epoch 192: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-192.ckpt
606/606 - 251s - loss: 0.1283 - mse: 0.1283 - val_loss: 0.1055 - val_mse: 0.1055 - 251s/epoch - 414ms/step
Epoch 193/200

Epoch 193: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-193.ckpt
606/606 - 248s - loss: 0.1285 - mse: 0.1285 - val_loss: 0.1125 - val_mse: 0.1125 - 248s/epoch - 410ms/step
Epoch 194/200

Epoch 194: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-194.ckpt
606/606 - 249s - loss: 0.1281 - mse: 0.1281 - val_loss: 0.1034 - val_mse: 0.1034 - 249s/epoch - 410ms/step
Epoch 195/200

Epoch 195: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-195.ckpt
606/606 - 251s - loss: 0.1286 - mse: 0.1286 - val_loss: 0.1112 - val_mse: 0.1112 - 251s/epoch - 414ms/step
Epoch 196/200

Epoch 196: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-196.ckpt
606/606 - 249s - loss: 0.1283 - mse: 0.1283 - val_loss: 0.1086 - val_mse: 0.1086 - 249s/epoch - 410ms/step
Epoch 197/200

Epoch 197: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-197.ckpt
606/606 - 248s - loss: 0.1290 - mse: 0.1290 - val_loss: 0.1067 - val_mse: 0.1067 - 248s/epoch - 410ms/step
Epoch 198/200

Epoch 198: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-198.ckpt
606/606 - 249s - loss: 0.1290 - mse: 0.1290 - val_loss: 0.1119 - val_mse: 0.1119 - 249s/epoch - 410ms/step
Epoch 199/200

Epoch 199: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-199.ckpt
606/606 - 251s - loss: 0.1285 - mse: 0.1285 - val_loss: 0.1151 - val_mse: 0.1151 - 251s/epoch - 414ms/step
Epoch 200/200

Epoch 200: saving model to /content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-200.ckpt
606/606 - 252s - loss: 0.1284 - mse: 0.1284 - val_loss: 0.1063 - val_mse: 0.1063 - 252s/epoch - 416ms/step

In [ ]:
#**********************************************predicting***********************************************

In [22]:
wieght='/content/drive/MyDrive/image/porosity_filtering/kernel_dimension/7*3*3*3*3/training_model_weights/cp-179.ckpt'
model.load_weights(wieght)

In [23]:
model.evaluate_generator(test_gen, nbatches_test, workers=1)

<ipython-input-23-7a06d8a850cb>:1: UserWarning: `Model.evaluate_generator` is deprecated and will be removed in a future version. Please use `Model.evaluate`, which supports generators.
  model.evaluate_generator(test_gen, nbatches_test, workers=1)

[0.1037132665514946, 0.1037132665514946]

In [24]:
y=model.predict_generator(
    test_gen_pre,
    verbose=1,
    steps=nbatches_test,
    callbacks=None,
    max_queue_size=10,
    workers=1,
    use_multiprocessing=False)

<ipython-input-24-e1afb12c7042>:1: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  y=model.predict_generator(

80/80 [==============================] - 13s 157ms/step

In [25]:
y_1=pd.DataFrame({'porosity':((y[:,0]*df_new['Porosity'].std())+df_new['Porosity'].mean()),
                  'throat radius':((y[:,1]*df_new['throat radius'].std())+df_new['throat radius'].mean()),
                'pore radius':((y[:,2]*df_new['pore radius'].std())+df_new['pore radius'].mean()),
                'pore_connection_number':((y[:,3]*df_new.pore_connection_number.std())+df_new.pore_connection_number.mean()),
                 'pore shape factor':((y[:,4]*df_new['pore shape factor'].std())+df_new['pore shape factor'].mean())})

In [26]:
df_test_1=np.array(df_test)
df_test_2=pd.DataFrame({'porosity':((df_test_1[:,1]*df_new.Porosity.std())+df_new.Porosity.mean()),
                  'throat radius':((df_test_1[:,2]*df_new['throat radius'].std())+df_new['throat radius'].mean()),
                'pore radius':((df_test_1[:,3]*df_new['pore radius'].std())+df_new['pore radius'].mean()),
                'pore_connection_number':((df_test_1[:,4]*df_new.pore_connection_number.std())+df_new.pore_connection_number.mean()),
                 'pore shape factor':((df_test_1[:,5]*df_new['pore shape factor'].std())+df_new['pore shape factor'].mean())})

In [27]:
#R^2_porosity
from sklearn.metrics import r2_score
x_values = np.array(df_test_2['porosity'])
y_values = np.array(y_1['porosity'])
r_squared_porosity=r2_score(x_values, y_values)
#orrelation_matrix = np.corrcoef(x_values, y_values)
#correlation_xy = correlation_matrix[0,1]
#r_squared_porosity = correlation_xy**2
print(r_squared_porosity)

0.9794906697431445

In [28]:
#R^2_porosity
from sklearn.metrics import r2_score
x_values = np.array(df_test_2['pore shape factor'])
y_values = np.array(y_1['pore shape factor'])
r_squared_pore_shape_factor=r2_score(x_values, y_values)
#orrelation_matrix = np.corrcoef(x_values, y_values)
#correlation_xy = correlation_matrix[0,1]
#r_squared_porosity = correlation_xy**2
print(r_squared_pore_shape_factor)

0.7332580344948727

In [29]:
from sklearn.metrics import r2_score
x_values = np.array(df_test_2['throat radius'])
y_values = np.array(y_1['throat radius'])
r_squared_throat_radius=r2_score(x_values, y_values)
#orrelation_matrix = np.corrcoef(x_values, y_values)
#correlation_xy = correlation_matrix[0,1]
#r_squared_porosity = correlation_xy**2
print(r_squared_throat_radius)

0.9109324464969923

In [30]:
#R^2_porosity
from sklearn.metrics import r2_score
x_values = np.array(df_test_2['pore radius'])
y_values = np.array(y_1['pore radius'])
r_squared_pore_radius=r2_score(x_values, y_values)
#orrelation_matrix = np.corrcoef(x_values, y_values)
#correlation_xy = correlation_matrix[0,1]
#r_squared_porosity = correlation_xy**2
print(r_squared_pore_radius)

0.9267964324411416

In [31]:
#R^2_porosity
from sklearn.metrics import r2_score
x_values = np.array(df_test_2['pore_connection_number'])
y_values = np.array(y_1['pore_connection_number'])
r_squared_pore_connection_number=r2_score(x_values, y_values)
#orrelation_matrix = np.corrcoef(x_values, y_values)
#correlation_xy = correlation_matrix[0,1]
#r_squared_porosity = correlation_xy**2
print(r_squared_pore_connection_number)

0.9239617195187041