In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!cp /content/drive/MyDrive/image/images.zip -d /content/images.zip
!unzip -q images.zip

In [3]:
!rm /content/images.zip

In [4]:
import os
A=os.listdir('/content')
A

['.config', 'images', 'drive', 'sample_data']

In [5]:
import pandas as pd
import glob
import os
import numpy as np
import matplotlib.pyplot as plt
s='/content/images/*'
path=glob.glob(s)
import re
def sorted_alphanumeric(data):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ]
    return sorted(data, key=alphanum_key)

path1=sorted_alphanumeric(path)
path1 = [item.replace('p','_') for item in path1]
data=pd.read_excel('/content/drive/MyDrive/image/data_c.xlsx')
data
len(path1)
print(path1)
type(path1)
path1=np.array(path1)
path1.shape
path1[0]

['/content/images/C_1_1_1.raw', '/content/images/C_1_1_16.raw', '/content/images/C_1_1_31.raw', '/content/images/C_1_1_46.raw', '/content/images/C_1_1_61.raw', '/content/images/C_1_1_76.raw', '/content/images/C_1_1_91.raw', '/content/images/C_1_1_106.raw', '/content/images/C_1_1_121.raw', '/content/images/C_1_1_136.raw', '/content/images/C_1_1_151.raw', '/content/images/C_1_1_166.raw', '/content/images/C_1_1_181.raw', '/content/images/C_1_1_196.raw', '/content/images/C_1_1_211.raw', '/content/images/C_1_1_226.raw', '/content/images/C_1_1_241.raw', '/content/images/C_1_1_256.raw', '/content/images/C_1_1_271.raw', '/content/images/C_1_1_286.raw', '/content/images/C_1_1_301.raw', '/content/images/C_1_16_1.raw', '/content/images/C_1_16_16.raw', '/content/images/C_1_16_31.raw', '/content/images/C_1_16_46.raw', '/content/images/C_1_16_61.raw', '/content/images/C_1_16_76.raw', '/content/images/C_1_16_91.raw', '/content/images/C_1_16_106.raw', '/content/images/C_1_16_121.raw', '/content/images/C_1_16_136.raw', '/content/images/C_1_16_151.raw', '/content/images/C_1_16_166.raw', '/content/images/C_1_16_181.raw', '/content/images/C_1_16_196.raw', '/content/images/C_1_16_211.raw', '/content/images/C_1_16_226.raw', '/content/images/C_1_16_241.raw', '/content/images/C_1_16_256.raw', '/content/images/C_1_16_271.raw', '/content/images/C_1_16_286.raw', '/content/images/C_1_16_301.raw', '/content/images/C_1_31_1.raw', '/content/images/C_1_31_16.raw', '/content/images/C_1_31_31.raw', '/content/images/C_1_31_46.raw', '/content/images/C_1_31_61.raw', '/content/images/C_1_31_76.raw', '/content/images/C_1_31_91.raw', '/content/images/C_1_31_106.raw', '/content/images/C_1_31_121.raw', '/content/images/C_1_31_136.raw', '/content/images/C_1_31_151.raw', '/content/images/C_1_31_166.raw', '/content/images/C_1_31_181.raw', '/content/images/C_1_31_196.raw', '/content/images/C_1_31_211.raw', '/content/images/C_1_31_226.raw', '/content/images/C_1_31_241.raw', '/content/images/C_1_31_256.raw', '/content/images/C_1_31_271.raw', '/content/images/C_1_31_286.raw', '/content/images/C_1_31_301.raw', '/content/images/C_1_46_1.raw', '/content/images/C_1_46_16.raw', '/content/images/C_1_46_31.raw', '/content/images/C_1_46_46.raw', '/content/images/C_1_46_61.raw', '/content/images/C_1_46_76.raw', '/content/images/C_1_46_91.raw', '/content/images/C_1_46_106.raw', '/content/images/C_1_46_121.raw', '/content/images/C_1_46_136.raw', '/content/images/C_1_46_151.raw', '/content/images/C_1_46_166.raw', '/content/images/C_1_46_181.raw', '/content/images/C_1_46_196.raw', '/content/images/C_1_46_211.raw', '/content/images/C_1_46_226.raw', '/content/images/C_1_46_241.raw', '/content/images/C_1_46_256.raw', '/content/images/C_1_46_271.raw', '/content/images/C_1_46_286.raw', '/content/images/C_1_46_301.raw', '/content/images/C_1_61_1.raw', '/content/images/C_1_61_16.raw', '/content/images/C_1_61_31.raw', '/content/images/C_1_61_46.raw', '/content/images/C_1_61_61.raw', '/content/images/C_1_61_76.raw', '/content/images/C_1_61_91.raw', '/content/images/C_1_61_106.raw', '/content/images/C_1_61_121.raw', '/content/images/C_1_61_136.raw', '/content/images/C_1_61_151.raw', '/content/images/C_1_61_166.raw', '/content/images/C_1_61_181.raw', '/content/images/C_1_61_196.raw', '/content/images/C_1_61_211.raw', '/content/images/C_1_61_226.raw', '/content/images/C_1_61_241.raw', '/content/images/C_1_61_256.raw', '/content/images/C_1_61_271.raw', '/content/images/C_1_61_286.raw', '/content/images/C_1_61_301.raw', '/content/images/C_1_76_1.raw', '/content/images/C_1_76_16.raw', '/content/images/C_1_76_31.raw', '/content/images/C_1_76_46.raw', '/content/images/C_1_76_61.raw', '/content/images/C_1_76_76.raw', '/content/images/C_1_76_91.raw', '/content/images/C_1_76_106.raw', '/content/images/C_1_76_121.raw', '/content/images/C_1_76_136.raw', '/content/images/C_1_76_151.raw', '/content/images/C_1_76_166.raw', '/content/images/C_1_76_181.raw', '/content/images/C_1_76_196.raw', '/content/images/C_1_76_211.raw', '/content/images/C_1_76_226.raw', '/content/images/C_1_76_241.raw', '/content/images/C_1_76_256.raw', '/content/images/C_1_76_271.raw', '/content/images/C_1_76_286.raw', '/content/images/C_1_76_301.raw', '/content/images/C_1_91_1.raw', '/content/images/C_1_91_16.raw', '/content/images/C_1_91_31.raw', '/content/images/C_1_91_46.raw', '/content/images/C_1_91_61.raw', '/content/images/C_1_91_76.raw', '/content/images/C_1_91_91.raw', '/content/images/C_1_91_106.raw', '/content/images/C_1_91_121.raw', '/content/images/C_1_91_136.raw', '/content/images/C_1_91_151.raw', '/content/images/C_1_91_166.raw', '/content/images/C_1_91_181.raw', '/content/images/C_1_91_196.raw', '/content/images/C_1_91_211.raw', '/content/images/C_1_91_226.raw', '/content/images/C_1_91_241.raw', '/content/images/C_1_91_256.raw', '/content/images/C_1_91_271.raw', '/content/images/C_1_91_286.raw', '/content/images/C_1_91_301.raw', '/content/images/C_1_106_1.raw', '/content/images/C_1_106_16.raw', '/content/images/C_1_106_31.raw', '/content/images/C_1_106_46.raw', '/content/images/C_1_106_61.raw', '/content/images/C_1_106_76.raw', '/content/images/C_1_106_91.raw', '/content/images/C_1_106_106.raw', '/content/images/C_1_106_121.raw', '/content/images/C_1_106_136.raw', '/content/images/C_1_106_151.raw', '/content/images/C_1_106_166.raw', '/content/images/C_1_106_181.raw', '/content/images/C_1_106_196.raw', '/content/images/C_1_106_211.raw', '/content/images/C_1_106_226.raw', '/content/images/C_1_106_241.raw', '/content/images/C_1_106_256.raw', '/content/images/C_1_106_271.raw', '/content/images/C_1_106_286.raw', '/content/images/C_1_106_301.raw', '/content/images/C_1_121_1.raw', '/content/images/C_1_121_16.raw', '/content/images/C_1_121_31.raw', '/content/images/C_1_121_46.raw', '/content/images/C_1_121_61.raw', '/content/images/C_1_121_76.raw', '/content/images/C_1_121_91.raw', '/content/images/C_1_121_106.raw', '/content/images/C_1_121_121.raw', '/content/images/C_1_121_136.raw', '/content/images/C_1_121_151.raw', '/content/images/C_1_121_166.raw', '/content/images/C_1_121_181.raw', '/content/images/C_1_121_196.raw', '/content/images/C_1_121_211.raw', '/content/images/C_1_121_226.raw', '/content/images/C_1_121_241.raw', '/content/images/C_1_121_256.raw', '/content/images/C_1_121_271.raw', '/content/images/C_1_121_286.raw', '/content/images/C_1_121_301.raw', '/content/images/C_1_136_1.raw', '/content/images/C_1_136_16.raw', '/content/images/C_1_136_31.raw', '/content/images/C_1_136_46.raw', '/content/images/C_1_136_61.raw', '/content/images/C_1_136_76.raw', '/content/images/C_1_136_91.raw', '/content/images/C_1_136_106.raw', '/content/images/C_1_136_121.raw', '/content/images/C_1_136_136.raw', '/content/images/C_1_136_151.raw', '/content/images/C_1_136_166.raw', '/content/images/C_1_136_181.raw', '/content/images/C_1_136_196.raw', '/content/images/C_1_136_211.raw', '/content/images/C_1_136_226.raw', '/content/images/C_1_136_241.raw', '/content/images/C_1_136_256.raw', '/content/images/C_1_136_271.raw', '/content/images/C_1_136_286.raw', '/content/images/C_1_136_301.raw', '/content/images/C_1_151_1.raw', '/content/images/C_1_151_16.raw', '/content/images/C_1_151_31.raw', '/content/images/C_1_151_46.raw', '/content/images/C_1_151_61.raw', '/content/images/C_1_151_76.raw', '/content/images/C_1_151_91.raw', '/content/images/C_1_151_106.raw', '/content/images/C_1_151_121.raw', '/content/images/C_1_151_136.raw', '/content/images/C_1_151_151.raw', '/content/images/C_1_151_166.raw', '/content/images/C_1_151_181.raw', '/content/images/C_1_151_196.raw', '/content/images/C_1_151_211.raw', '/content/images/C_1_151_226.raw', '/content/images/C_1_151_241.raw', '/content/images/C_1_151_256.raw', '/content/images/C_1_151_271.raw', '/content/images/C_1_151_286.raw', '/content/images/C_1_151_301.raw', '/content/images/C_1_166_1.raw', '/content/images/C_1_166_16.raw', '/content/images/C_1_166_31.raw', '/content/images/C_1_166_46.raw', '/content/images/C_1_166_61.raw', '/content/images/C_1_166_76.raw', '/content/images/C_1_166_91.raw', '/content/images/C_1_166_106.raw', '/content/images/C_1_166_121.raw', '/content/images/C_1_166_136.raw', '/content/images/C_1_166_151.raw', '/content/images/C_1_166_166.raw', '/content/images/C_1_166_181.raw', '/content/images/C_1_166_196.raw', '/content/images/C_1_166_211.raw', '/content/images/C_1_166_226.raw', '/content/images/C_1_166_241.raw', '/content/images/C_1_166_256.raw', '/content/images/C_1_166_271.raw', '/content/images/C_1_166_286.raw', '/content/images/C_1_166_301.raw', '/content/images/C_1_181_1.raw', '/content/images/C_1_181_16.raw', '/content/images/C_1_181_31.raw', '/content/images/C_1_181_46.raw', '/content/images/C_1_181_61.raw', '/content/images/C_1_181_76.raw', '/content/images/C_1_181_91.raw', '/content/images/C_1_181_106.raw', '/content/images/C_1_181_121.raw', '/content/images/C_1_181_136.raw', '/content/images/C_1_181_151.raw', '/content/images/C_1_181_166.raw', '/content/images/C_1_181_181.raw', '/content/images/C_1_181_196.raw', '/content/images/C_1_181_211.raw', '/content/images/C_1_181_226.raw', '/content/images/C_1_181_241.raw', '/content/images/C_1_181_256.raw', '/content/images/C_1_181_271.raw', '/content/images/C_1_181_286.raw', '/content/images/C_1_181_301.raw', '/content/images/C_1_196_1.raw', '/content/images/C_1_196_16.raw', '/content/images/C_1_196_31.raw', '/content/images/C_1_196_46.raw', '/content/images/C_1_196_61.raw', '/content/images/C_1_196_76.raw', '/content/images/C_1_196_91.raw', '/content/images/C_1_196_106.raw', '/content/images/C_1_196_121.raw', '/content/images/C_1_196_136.raw', '/content/images/C_1_196_151.raw', '/content/images/C_1_196_166.raw', '/content/images/C_1_196_181.raw', '/content/images/C_1_196_196.raw', '/content/images/C_1_196_211.raw', '/content/images/C_1_196_226.raw', '/content/images/C_1_196_241.raw', '/content/images/C_1_196_256.raw', '/content/images/C_1_196_271.raw', '/content/images/C_1_196_286.raw', '/content/images/C_1_196_301.raw', '/content/images/C_1_211_1.raw', '/content/images/C_1_211_16.raw', '/content/images/C_1_211_31.raw', '/content/images/C_1_211_46.raw', '/content/images/C_1_211_61.raw', '/content/images/C_1_211_76.raw', '/content/images/C_1_211_91.raw', '/content/images/C_1_211_106.raw', '/content/images/C_1_211_121.raw', '/content/images/C_1_211_136.raw', '/content/images/C_1_211_151.raw', '/content/images/C_1_211_166.raw', '/content/images/C_1_211_181.raw', '/content/images/C_1_211_196.raw', '/content/images/C_1_211_211.raw', '/content/images/C_1_211_226.raw', '/content/images/C_1_211_241.raw', '/content/images/C_1_211_256.raw', '/content/images/C_1_211_271.raw', '/content/images/C_1_211_286.raw', '/content/images/C_1_211_301.raw', '/content/images/C_1_226_1.raw', '/content/images/C_1_226_16.raw', '/content/images/C_1_226_31.raw', '/content/images/C_1_226_46.raw', '/content/images/C_1_226_61.raw', '/content/images/C_1_226_76.raw', '/content/images/C_1_226_91.raw', '/content/images/C_1_226_106.raw', '/content/images/C_1_226_121.raw', '/content/images/C_1_226_136.raw', '/content/images/C_1_226_151.raw', '/content/images/C_1_226_166.raw', '/content/images/C_1_226_181.raw', '/content/images/C_1_226_196.raw', '/content/images/C_1_226_211.raw', '/content/images/C_1_226_226.raw', '/content/images/C_1_226_241.raw', '/content/images/C_1_226_256.raw', '/content/images/C_1_226_271.raw', '/content/images/C_1_226_286.raw', '/content/images/C_1_226_301.raw', '/content/images/C_1_241_1.raw', '/content/images/C_1_241_16.raw', '/content/images/C_1_241_31.raw', '/content/images/C_1_241_46.raw', '/content/images/C_1_241_61.raw', '/content/images/C_1_241_76.raw', '/content/images/C_1_241_91.raw', '/content/images/C_1_241_106.raw', '/content/images/C_1_241_121.raw', '/content/images/C_1_241_136.raw', '/content/images/C_1_241_151.raw', '/content/images/C_1_241_166.raw', '/content/images/C_1_241_181.raw', '/content/images/C_1_241_196.raw', '/content/images/C_1_241_211.raw', '/content/images/C_1_241_226.raw', '/content/images/C_1_241_241.raw', '/content/images/C_1_241_256.raw', '/content/images/C_1_241_271.raw', '/content/images/C_1_241_286.raw', '/content/images/C_1_241_301.raw', '/content/images/C_1_256_1.raw', '/content/images/C_1_256_16.raw', '/content/images/C_1_256_31.raw', '/content/images/C_1_256_46.raw', '/content/images/C_1_256_61.raw', '/content/images/C_1_256_76.raw', '/content/images/C_1_256_91.raw', '/content/images/C_1_256_106.raw', '/content/images/C_1_256_121.raw', '/content/images/C_1_256_136.raw', '/content/images/C_1_256_151.raw', '/content/images/C_1_256_166.raw', '/content/images/C_1_256_181.raw', '/content/images/C_1_256_196.raw', '/content/images/C_1_256_211.raw', '/content/images/C_1_256_226.raw', '/content/images/C_1_256_241.raw', '/content/images/C_1_256_256.raw', '/content/images/C_1_256_271.raw', '/content/images/C_1_256_286.raw', '/content/images/C_1_256_301.raw', '/content/images/C_1_271_1.raw', '/content/images/C_1_271_16.raw', '/content/images/C_1_271_31.raw', '/content/images/C_1_271_46.raw', '/content/images/C_1_271_61.raw', '/content/images/C_1_271_76.raw', '/content/images/C_1_271_91.raw', '/content/images/C_1_271_106.raw', '/content/images/C_1_271_121.raw', '/content/images/C_1_271_136.raw', '/content/images/C_1_271_151.raw', '/content/images/C_1_271_166.raw', '/content/images/C_1_271_181.raw', '/content/images/C_1_271_196.raw', '/content/images/C_1_271_211.raw', '/content/images/C_1_271_226.raw', '/content/images/C_1_271_241.raw', '/content/images/C_1_271_256.raw', '/content/images/C_1_271_271.raw', '/content/images/C_1_271_286.raw', '/content/images/C_1_271_301.raw', '/content/images/C_1_286_1.raw', '/content/images/C_1_286_16.raw', '/content/images/C_1_286_31.raw', '/content/images/C_1_286_46.raw', '/content/images/C_1_286_61.raw', '/content/images/C_1_286_76.raw', '/content/images/C_1_286_91.raw', '/content/images/C_1_286_106.raw', '/content/images/C_1_286_121.raw', '/content/images/C_1_286_136.raw', '/content/images/C_1_286_151.raw', '/content/images/C_1_286_166.raw', '/content/images/C_1_286_181.raw', '/content/images/C_1_286_196.raw', '/content/images/C_1_286_211.raw', '/content/images/C_1_286_226.raw', '/content/images/C_1_286_241.raw', '/content/images/C_1_286_256.raw', '/content/images/C_1_286_271.raw', '/content/images/C_1_286_286.raw', '/content/images/C_1_286_301.raw', '/content/images/C_1_301_1.raw', '/content/images/C_1_301_16.raw', '/content/images/C_1_301_31.raw', '/content/images/C_1_301_46.raw', '/content/images/C_1_301_61.raw', '/content/images/C_1_301_76.raw', '/content/images/C_1_301_91.raw', '/content/images/C_1_301_106.raw', '/content/images/C_1_301_121.raw', '/content/images/C_1_301_136.raw', '/content/images/C_1_301_151.raw', '/content/images/C_1_301_166.raw', '/content/images/C_1_301_181.raw', '/content/images/C_1_301_196.raw', '/content/images/C_1_301_211.raw', '/content/images/C_1_301_226.raw', '/content/images/C_1_301_241.raw', '/content/images/C_1_301_256.raw', '/content/images/C_1_301_271.raw', '/content/images/C_1_301_286.raw', '/content/images/C_1_301_301.raw', '/content/images/C_16_1_1.raw', '/content/images/C_16_1_16.raw', '/content/images/C_16_1_31.raw', '/content/images/C_16_1_46.raw', '/content/images/C_16_1_61.raw', '/content/images/C_16_1_76.raw', '/content/images/C_16_1_91.raw', '/content/images/C_16_1_106.raw', '/content/images/C_16_1_121.raw', '/content/images/C_16_1_136.raw', '/content/images/C_16_1_151.raw', '/content/images/C_16_1_166.raw', '/content/images/C_16_1_181.raw', '/content/images/C_16_1_196.raw', '/content/images/C_16_1_211.raw', '/content/images/C_16_1_226.raw', '/content/images/C_16_1_241.raw', '/content/images/C_16_1_256.raw', '/content/images/C_16_1_271.raw', '/content/images/C_16_1_286.raw', '/content/images/C_16_1_301.raw', '/content/images/C_16_16_1.raw', '/content/images/C_16_16_16.raw', '/content/images/C_16_16_31.raw', '/content/images/C_16_16_46.raw', '/content/images/C_16_16_61.raw', '/content/images/C_16_16_76.raw', '/content/images/C_16_16_91.raw', '/content/images/C_16_16_106.raw', '/content/images/C_16_16_121.raw', '/content/images/C_16_16_136.raw', '/content/images/C_16_16_151.raw', '/content/images/C_16_16_166.raw', '/content/images/C_16_16_181.raw', '/content/images/C_16_16_196.raw', '/content/images/C_16_16_211.raw', '/content/images/C_16_16_226.raw', '/content/images/C_16_16_241.raw', '/content/images/C_16_16_256.raw', '/content/images/C_16_16_271.raw', '/content/images/C_16_16_286.raw', '/content/images/C_16_16_301.raw', '/content/images/C_16_31_1.raw', '/content/images/C_16_31_16.raw', '/content/images/C_16_31_31.raw', '/content/images/C_16_31_46.raw', '/content/images/C_16_31_61.raw', '/content/images/C_16_31_76.raw', '/content/images/C_16_31_91.raw', '/content/images/C_16_31_106.raw', '/content/images/C_16_31_121.raw', '/content/images/C_16_31_136.raw', '/content/images/C_16_31_151.raw', '/content/images/C_16_31_166.raw', '/content/images/C_16_31_181.raw', '/content/images/C_16_31_196.raw', '/content/images/C_16_31_211.raw', '/content/images/C_16_31_226.raw', '/content/images/C_16_31_241.raw', '/content/images/C_16_31_256.raw', '/content/images/C_16_31_271.raw', '/content/images/C_16_31_286.raw', '/content/images/C_16_31_301.raw', '/content/images/C_16_46_1.raw', '/content/images/C_16_46_16.raw', '/content/images/C_16_46_31.raw', '/content/images/C_16_46_46.raw', '/content/images/C_16_46_61.raw', '/content/images/C_16_46_76.raw', '/content/images/C_16_46_91.raw', '/content/images/C_16_46_106.raw', '/content/images/C_16_46_121.raw', '/content/images/C_16_46_136.raw', '/content/images/C_16_46_151.raw', '/content/images/C_16_46_166.raw', '/content/images/C_16_46_181.raw', '/content/images/C_16_46_196.raw', '/content/images/C_16_46_211.raw', '/content/images/C_16_46_226.raw', '/content/images/C_16_46_241.raw', '/content/images/C_16_46_256.raw', '/content/images/C_16_46_271.raw', '/content/images/C_16_46_286.raw', '/content/images/C_16_46_301.raw', '/content/images/C_16_61_1.raw', '/content/images/C_16_61_16.raw', '/content/images/C_16_61_31.raw', '/content/images/C_16_61_46.raw', '/content/images/C_16_61_61.raw', '/content/images/C_16_61_76.raw', '/content/images/C_16_61_91.raw', '/content/images/C_16_61_106.raw', '/content/images/C_16_61_121.raw', '/content/images/C_16_61_136.raw', '/content/images/C_16_61_151.raw', '/content/images/C_16_61_166.raw', '/content/images/C_16_61_181.raw', '/content/images/C_16_61_196.raw', '/content/images/C_16_61_211.raw', '/content/images/C_16_61_226.raw', '/content/images/C_16_61_241.raw', '/content/images/C_16_61_256.raw', '/content/images/C_16_61_271.raw', '/content/images/C_16_61_286.raw', '/content/images/C_16_61_301.raw', '/content/images/C_16_76_1.raw', '/content/images/C_16_76_16.raw', '/content/images/C_16_76_31.raw', '/content/images/C_16_76_46.raw', '/content/images/C_16_76_61.raw', '/content/images/C_16_76_76.raw', '/content/images/C_16_76_91.raw', '/content/images/C_16_76_106.raw', '/content/images/C_16_76_121.raw', '/content/images/C_16_76_136.raw', '/content/images/C_16_76_151.raw', '/content/images/C_16_76_166.raw', '/content/images/C_16_76_181.raw', '/content/images/C_16_76_196.raw', '/content/images/C_16_76_211.raw', '/content/images/C_16_76_226.raw', '/content/images/C_16_76_241.raw', '/content/images/C_16_76_256.raw', '/content/images/C_16_76_271.raw', '/content/images/C_16_76_286.raw', '/content/images/C_16_76_301.raw', '/content/images/C_16_91_1.raw', '/content/images/C_16_91_16.raw', '/content/images/C_16_91_31.raw', '/content/images/C_16_91_46.raw', '/content/images/C_16_91_61.raw', '/content/images/C_16_91_76.raw', '/content/images/C_16_91_91.raw', '/content/images/C_16_91_106.raw', '/content/images/C_16_91_121.raw', '/content/images/C_16_91_136.raw', '/content/images/C_16_91_151.raw', '/content/images/C_16_91_166.raw', '/content/images/C_16_91_181.raw', '/content/images/C_16_91_196.raw', '/content/images/C_16_91_211.raw', '/content/images/C_16_91_226.raw', '/conte

'/content/images/C_1_1_1.raw'

In [6]:
path1=np.array(path1)
data=np.array(data)

In [7]:
df=pd.DataFrame({'imgpath':path1,'Porosity':data[:,0],'throat radius':data[:,1],'pore radius':data[:,2],'pore_connection_number':data[:,3],'pore shape factor':data[:,4]})

In [8]:
df_new=df[df['Porosity'] <0.35 ]
df_new.shape
df_new

,imgpath,Porosity,throat radius,pore radius,pore_connection_number,pore shape factor
0,/content/images/C_1_1_1.raw,0.200016,0.000009,0.000013,1.92857,0.037024
1,/content/images/C_1_1_16.raw,0.211707,0.000008,0.000012,2.25000,0.036642
2,/content/images/C_1_1_31.raw,0.233293,0.000008,0.000013,1.96875,0.038013
3,/content/images/C_1_1_46.raw,0.264409,0.000009,0.000014,2.18182,0.039828
4,/content/images/C_1_1_61.raw,0.277295,0.000009,0.000014,2.27273,0.038306
...,...,...,...,...,...,...
9256,/content/images/C_301_301_241.raw,0.136927,0.000008,0.000013,2.35443,0.036514
9257,/content/images/C_301_301_256.raw,0.136191,0.000008,0.000013,2.12658,0.036236
9258,/content/images/C_301_301_271.raw,0.147490,0.000008,0.000014,2.17722,0.033896
9259,/content/images/C_301_301_286.raw,0.161413,0.000008,0.000013,2.18987,0.035108
9260,/content/images/C_301_301_301.raw,0.179779,0.000009,0.000015,1.97468,0.029493

In [9]:
from sklearn.preprocessing import StandardScaler
import numpy as np
data1=np.array(df_new)
scaler = StandardScaler()
data1= scaler.fit_transform(data1[:,1:])
print(data1)
print(type(data1))
data1.shape

[[ 0.11455659  0.58493673  0.28969785 -0.82815281 -0.22691552]
 [ 0.27058416 -0.34306756 -0.15901557 -0.0260099  -0.34020621]
 [ 0.55866997 -0.05166937  0.52032542 -0.72788183  0.06680977]
 ...
 [-0.58645309 -0.39830083  0.62718527 -0.20763563 -1.1561657 ]
 [-0.40063734  0.06434896  0.10229779 -0.17606699 -0.79601231]
 [-0.15552552  0.3087704   1.25751387 -0.71308325 -2.46407987]]
<class 'numpy.ndarray'>

(7921, 5)

In [10]:
df=pd.DataFrame({'imgpath':df_new['imgpath'],'Porosity':data1[:,0],'throat radius':data1[:,1],'pore radius':data1[:,2],'pore_connection_number':data1[:,3],'pore shape factor':data1[:,4]})
df

,imgpath,Porosity,throat radius,pore radius,pore_connection_number,pore shape factor
0,/content/images/C_1_1_1.raw,0.114557,0.584937,0.289698,-0.828153,-0.226916
1,/content/images/C_1_1_16.raw,0.270584,-0.343068,-0.159016,-0.026010,-0.340206
2,/content/images/C_1_1_31.raw,0.558670,-0.051669,0.520325,-0.727882,0.066810
3,/content/images/C_1_1_46.raw,0.973943,0.745227,0.630089,-0.196156,0.606040
4,/content/images/C_1_1_61.raw,1.145919,0.514543,1.057970,0.030714,0.154056
...,...,...,...,...,...,...
9256,/content/images/C_301_301_241.raw,-0.727426,-0.487201,0.223571,0.234600,-0.378288
9257,/content/images/C_301_301_256.raw,-0.737249,-0.264275,0.454180,-0.334010,-0.460952
9258,/content/images/C_301_301_271.raw,-0.586453,-0.398301,0.627185,-0.207636,-1.156166
9259,/content/images/C_301_301_286.raw,-0.400637,0.064349,0.102298,-0.176067,-0.796012
9260,/content/images/C_301_301_301.raw,-0.155526,0.308770,1.257514,-0.713083,-2.464080

In [11]:
data_t_general=df.sample(frac=0.9,random_state=1)
df_valid=data_t_general.sample(frac=0.15,random_state=2)
df_train=data_t_general.loc[~data_t_general.index.isin(df_valid.index)]
df_test =df.loc[~df.index.isin(data_t_general.index)]
len(df_train)

6060

In [12]:
def Data_generator(df, batch_size, augment=False):

    while True:

            for start in range(0, df.shape[0], batch_size):
                x_batch_img = []
                y_batch=[]
                end = min(start + batch_size, df.shape[0])

                for idd in range(start,end):
                    img = open(np.array(df.imgpath)[idd],'rb').read()
                    img_1=np.frombuffer(img,dtype=np.uint8)
                    img_1=img_1.reshape(100,100,100,1)
                    Porosity=np.array(df.Porosity)[idd]
                    throat_radius=np.array(df['throat radius'])[idd]
                    pore_radius=np.array(df['pore radius'])[idd]
                    pore_connection_number=np.array(df.pore_connection_number)[idd]
                    pore_shape_factor=np.array(df['pore shape factor'])[idd]
                    y_1=np.concatenate((Porosity, throat_radius,pore_radius,pore_connection_number, pore_shape_factor),axis=None)
                    y=np.array([y_1])
                    x_batch_img.append(img_1)
                    y_batch.append(y)


                x_batch_img = np.array(x_batch_img)
                y_batch= np.array(y_batch)
                y_batch=y_batch.reshape(-1,5)
              #y_batch = to_categorical(y_batch,5)
                yield x_batch_img , y_batch

In [13]:
def Data_predict_generator(df, batch_size, augment=False):

    while True:

            for start in range(0, df.shape[0], batch_size):
                x_batch_img_2 = []

                end = min(start + batch_size, df.shape[0])

                for idd in range(start,end):
                    img = open(np.array(df.imgpath)[idd],'rb').read()
                    img_1=np.frombuffer(img,dtype=np.uint8)
                    img_1=img_1.reshape(100,100,100,1)
                    x_batch_img_2.append(img_1)



                x_batch_img_2 = np.array(x_batch_img_2)

              #y_batch = to_categorical(y_batch,5)
                yield x_batch_img_2

In [14]:
batch_size=10
train_gen= Data_generator(df_train,batch_size)
valid_gen= Data_generator(df_valid,batch_size)
train_gen_pre=Data_predict_generator(df_train,batch_size)
valid_gen_pre=Data_predict_generator(df_valid,batch_size)
test_gen= Data_generator(df_test,batch_size)
test_gen_pre=Data_predict_generator(df_test,batch_size)

In [15]:
import math
ntrain, nvalid, ntest = df_train.shape[0], df_valid.shape[0],  df_test.shape[0]
nbatches_train=math.ceil(df_train.shape[0]/batch_size)
nbatches_valid=math.ceil(df_valid.shape[0]/batch_size)
nbatches_test=math.ceil( df_test.shape[0]/batch_size)
nworkers=1

In [16]:
print(nbatches_valid,nbatches_train,nbatches_test)

107 606 80

In [17]:
from keras.models import Sequential
from keras.layers import Conv3D,MaxPooling3D,Dropout,Flatten,Dense,BatchNormalization,ReLU
from tensorflow.keras import initializers
from keras.callbacks import *
import tensorflow as tf

In [18]:
model=Sequential()
model.add(Conv3D(16,kernel_size=(7,7,7),input_shape=(100,100,100,1),padding="same",activation='relu',kernel_initializer=initializers.RandomNormal(stddev=0.01),))
model.add(BatchNormalization())
model.add(MaxPooling3D(pool_size=(2,2,2)))
model.add(Conv3D(32,kernel_size=(5,5,5),activation='relu',padding="same",kernel_initializer=initializers.RandomNormal(stddev=0.01)))
model.add(BatchNormalization())
#model.add(Dropout(0.2))
model.add(MaxPooling3D(pool_size=(2,2,2)))
model.add(Conv3D(64,kernel_size=(3,3,3),activation='relu',padding="same",kernel_initializer=initializers.RandomNormal(stddev=0.01)))
model.add(BatchNormalization())
#model.add(Dropout(0.2))
model.add(MaxPooling3D(pool_size=(2,2,2)))
model.add(Conv3D(128,kernel_size=(3,3,3),activation='relu',padding="same",kernel_initializer=initializers.RandomNormal(stddev=0.01)))
model.add(BatchNormalization())
#model.add(Dropout(0.2))
model.add(MaxPooling3D(pool_size=(2,2,2)))
model.add(Conv3D(256,kernel_size=(3,3,3),activation='relu',padding="same",kernel_initializer=initializers.RandomNormal(stddev=0.01)))
model.add(BatchNormalization())
model.add(MaxPooling3D(pool_size=(2,2,2)))
#model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(1024,activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(512,activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(5))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv3d (Conv3D)             (None, 100, 100, 100, 1   5504
                             6)

 batch_normalization (Batch  (None, 100, 100, 100, 1   64
 Normalization)              6)

 max_pooling3d (MaxPooling3  (None, 50, 50, 50, 16)    0
 D)

 conv3d_1 (Conv3D)           (None, 50, 50, 50, 32)    64032

 batch_normalization_1 (Bat  (None, 50, 50, 50, 32)    128
 chNormalization)

 max_pooling3d_1 (MaxPoolin  (None, 25, 25, 25, 32)    0
 g3D)

 conv3d_2 (Conv3D)           (None, 25, 25, 25, 64)    55360

 batch_normalization_2 (Bat  (None, 25, 25, 25, 64)    256
 chNormalization)

 max_pooling3d_2 (MaxPoolin  (None, 12, 12, 12, 64)    0
 g3D)

 conv3d_3 (Conv3D)           (None, 12, 12, 12, 128)   221312

 batch_normalization_3 (Bat  (None, 12, 12, 12, 128)   512
 chNormalization)

 max_pooling3d_3 (MaxPoolin  (None, 6, 6, 6, 128)      0
 g3D)

 conv3d_4 (Conv3D)           (None, 6, 6, 6, 256)      884992

 batch_normalization_4 (Bat  (None, 6, 6, 6, 256)      1024
 chNormalization)

 max_pooling3d_4 (MaxPoolin  (None, 3, 3, 3, 256)      0
 g3D)

 flatten (Flatten)           (None, 6912)              0

 dense (Dense)               (None, 1024)              7078912

 batch_normalization_5 (Bat  (None, 1024)              4096
 chNormalization)

 dropout (Dropout)           (None, 1024)              0

 dense_1 (Dense)             (None, 512)               524800

 batch_normalization_6 (Bat  (None, 512)               2048
 chNormalization)

 dropout_1 (Dropout)         (None, 512)               0

 dense_2 (Dense)             (None, 5)                 2565

=================================================================
Total params: 8845605 (33.74 MB)
Trainable params: 8841541 (33.73 MB)
Non-trainable params: 4064 (15.88 KB)
_________________________________________________________________

In [19]:
import os
checkpoint_path="/content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-{epoch:03d}.ckpt"
#os.makedirs("/content/drive/MyDrive/image/porosity_filtering/training_5layers", exist_ok=True)
#ckpt_callback = ModelCheckpoint(filepath='/content/drive/MyDrive/image/porosity_filtering/training_model_5layers/weights.{epoch:02d}-{val_loss:.2f}.hdf5', monitor='val_loss')
cp_callback=ModelCheckpoint(filepath=checkpoint_path,save_weights_only=True,verbose=1)

In [20]:
csvlogger=CSVLogger('/content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/Training_189.log')

In [21]:
opt = tf.keras.optimizers.Adam(learning_rate=0.0005)
model.compile(opt,loss='mse',metrics=['mse'])

In [ ]:
history=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger])

Epoch 1/200

<ipython-input-22-2be0de0fe96b>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger])

Epoch 1: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-001.ckpt
606/606 - 381s - loss: 2.3660 - mse: 2.3660 - val_loss: 60.4507 - val_mse: 60.4507 - 381s/epoch - 628ms/step
Epoch 2/200

Epoch 2: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-002.ckpt
606/606 - 336s - loss: 1.0187 - mse: 1.0187 - val_loss: 66.2787 - val_mse: 66.2787 - 336s/epoch - 554ms/step
Epoch 3/200

Epoch 3: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-003.ckpt
606/606 - 335s - loss: 0.6078 - mse: 0.6078 - val_loss: 0.8930 - val_mse: 0.8930 - 335s/epoch - 553ms/step
Epoch 4/200

Epoch 4: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-004.ckpt
606/606 - 335s - loss: 0.4394 - mse: 0.4394 - val_loss: 1.4190 - val_mse: 1.4190 - 335s/epoch - 553ms/step
Epoch 5/200

Epoch 5: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-005.ckpt
606/606 - 353s - loss: 0.3651 - mse: 0.3651 - val_loss: 6.6720 - val_mse: 6.6720 - 353s/epoch - 582ms/step
Epoch 6/200

Epoch 6: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-006.ckpt
606/606 - 353s - loss: 0.3321 - mse: 0.3321 - val_loss: 3.3434 - val_mse: 3.3434 - 353s/epoch - 583ms/step
Epoch 7/200

Epoch 7: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-007.ckpt
606/606 - 353s - loss: 0.3178 - mse: 0.3178 - val_loss: 0.5414 - val_mse: 0.5414 - 353s/epoch - 583ms/step
Epoch 8/200

Epoch 8: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-008.ckpt
606/606 - 336s - loss: 0.2948 - mse: 0.2948 - val_loss: 4.0351 - val_mse: 4.0351 - 336s/epoch - 554ms/step
Epoch 9/200

Epoch 9: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-009.ckpt
606/606 - 353s - loss: 0.2773 - mse: 0.2773 - val_loss: 0.4107 - val_mse: 0.4107 - 353s/epoch - 582ms/step
Epoch 10/200

Epoch 10: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-010.ckpt
606/606 - 336s - loss: 0.2649 - mse: 0.2649 - val_loss: 0.5799 - val_mse: 0.5799 - 336s/epoch - 554ms/step
Epoch 11/200

Epoch 11: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-011.ckpt
606/606 - 352s - loss: 0.2531 - mse: 0.2531 - val_loss: 0.9750 - val_mse: 0.9750 - 352s/epoch - 581ms/step
Epoch 12/200

Epoch 12: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-012.ckpt
606/606 - 335s - loss: 0.2435 - mse: 0.2435 - val_loss: 0.6700 - val_mse: 0.6700 - 335s/epoch - 553ms/step
Epoch 13/200

Epoch 13: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-013.ckpt
606/606 - 352s - loss: 0.2396 - mse: 0.2396 - val_loss: 0.5966 - val_mse: 0.5966 - 352s/epoch - 581ms/step
Epoch 14/200

Epoch 14: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-014.ckpt
606/606 - 335s - loss: 0.2322 - mse: 0.2322 - val_loss: 0.6010 - val_mse: 0.6010 - 335s/epoch - 553ms/step
Epoch 15/200

Epoch 15: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-015.ckpt
606/606 - 334s - loss: 0.2259 - mse: 0.2259 - val_loss: 0.2686 - val_mse: 0.2686 - 334s/epoch - 552ms/step
Epoch 16/200

Epoch 16: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-016.ckpt
606/606 - 335s - loss: 0.2219 - mse: 0.2219 - val_loss: 0.3228 - val_mse: 0.3228 - 335s/epoch - 552ms/step
Epoch 17/200

Epoch 17: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-017.ckpt
606/606 - 334s - loss: 0.2176 - mse: 0.2176 - val_loss: 0.2240 - val_mse: 0.2240 - 334s/epoch - 551ms/step
Epoch 18/200

Epoch 18: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-018.ckpt
606/606 - 334s - loss: 0.2035 - mse: 0.2035 - val_loss: 0.7543 - val_mse: 0.7543 - 334s/epoch - 552ms/step
Epoch 19/200

Epoch 19: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-019.ckpt
606/606 - 334s - loss: 0.2037 - mse: 0.2037 - val_loss: 0.3098 - val_mse: 0.3098 - 334s/epoch - 552ms/step
Epoch 20/200

Epoch 20: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-020.ckpt
606/606 - 352s - loss: 0.2086 - mse: 0.2086 - val_loss: 0.5550 - val_mse: 0.5550 - 352s/epoch - 580ms/step
Epoch 21/200

Epoch 21: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-021.ckpt
606/606 - 335s - loss: 0.1989 - mse: 0.1989 - val_loss: 0.2586 - val_mse: 0.2586 - 335s/epoch - 553ms/step
Epoch 22/200

Epoch 22: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-022.ckpt
606/606 - 335s - loss: 0.1893 - mse: 0.1893 - val_loss: 0.2327 - val_mse: 0.2327 - 335s/epoch - 552ms/step
Epoch 23/200

Epoch 23: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-023.ckpt
606/606 - 335s - loss: 0.1885 - mse: 0.1885 - val_loss: 0.1737 - val_mse: 0.1737 - 335s/epoch - 552ms/step
Epoch 24/200

Epoch 24: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-024.ckpt
606/606 - 352s - loss: 0.1865 - mse: 0.1865 - val_loss: 0.3188 - val_mse: 0.3188 - 352s/epoch - 581ms/step
Epoch 25/200

Epoch 25: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-025.ckpt
606/606 - 335s - loss: 0.1874 - mse: 0.1874 - val_loss: 0.1484 - val_mse: 0.1484 - 335s/epoch - 553ms/step
Epoch 26/200

Epoch 26: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-026.ckpt
606/606 - 335s - loss: 0.1835 - mse: 0.1835 - val_loss: 0.1632 - val_mse: 0.1632 - 335s/epoch - 552ms/step
Epoch 27/200

Epoch 27: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-027.ckpt
606/606 - 334s - loss: 0.1784 - mse: 0.1784 - val_loss: 0.1916 - val_mse: 0.1916 - 334s/epoch - 552ms/step
Epoch 28/200

Epoch 28: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-028.ckpt
606/606 - 352s - loss: 0.1750 - mse: 0.1750 - val_loss: 0.1932 - val_mse: 0.1932 - 352s/epoch - 581ms/step
Epoch 29/200

Epoch 29: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-029.ckpt
606/606 - 336s - loss: 0.1750 - mse: 0.1750 - val_loss: 0.1915 - val_mse: 0.1915 - 336s/epoch - 555ms/step
Epoch 30/200

Epoch 30: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-030.ckpt
606/606 - 335s - loss: 0.1733 - mse: 0.1733 - val_loss: 0.2003 - val_mse: 0.2003 - 335s/epoch - 553ms/step
Epoch 31/200

Epoch 31: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-031.ckpt
606/606 - 335s - loss: 0.1714 - mse: 0.1714 - val_loss: 0.2633 - val_mse: 0.2633 - 335s/epoch - 552ms/step
Epoch 32/200

Epoch 32: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-032.ckpt
606/606 - 335s - loss: 0.1692 - mse: 0.1692 - val_loss: 0.1379 - val_mse: 0.1379 - 335s/epoch - 553ms/step
Epoch 33/200

Epoch 33: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-033.ckpt
606/606 - 352s - loss: 0.1671 - mse: 0.1671 - val_loss: 0.1691 - val_mse: 0.1691 - 352s/epoch - 581ms/step
Epoch 34/200

Epoch 34: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-034.ckpt
606/606 - 336s - loss: 0.1650 - mse: 0.1650 - val_loss: 0.1475 - val_mse: 0.1475 - 336s/epoch - 554ms/step
Epoch 35/200

Epoch 35: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-035.ckpt
606/606 - 336s - loss: 0.1643 - mse: 0.1643 - val_loss: 0.2368 - val_mse: 0.2368 - 336s/epoch - 554ms/step
Epoch 36/200

Epoch 36: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-036.ckpt
606/606 - 352s - loss: 0.1620 - mse: 0.1620 - val_loss: 0.1688 - val_mse: 0.1688 - 352s/epoch - 581ms/step
Epoch 37/200

Epoch 37: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-037.ckpt
606/606 - 353s - loss: 0.1604 - mse: 0.1604 - val_loss: 0.1318 - val_mse: 0.1318 - 353s/epoch - 583ms/step
Epoch 38/200

Epoch 38: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-038.ckpt
606/606 - 353s - loss: 0.1597 - mse: 0.1597 - val_loss: 0.1401 - val_mse: 0.1401 - 353s/epoch - 583ms/step
Epoch 39/200

Epoch 39: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-039.ckpt
606/606 - 335s - loss: 0.1601 - mse: 0.1601 - val_loss: 0.1370 - val_mse: 0.1370 - 335s/epoch - 553ms/step
Epoch 40/200

Epoch 40: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-040.ckpt
606/606 - 334s - loss: 0.1578 - mse: 0.1578 - val_loss: 0.1384 - val_mse: 0.1384 - 334s/epoch - 552ms/step
Epoch 41/200

In [ ]:
wieght='/content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-040.ckpt'
model.load_weights(wieght)

In [ ]:
history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=40)

<ipython-input-23-ba9e5818ed4d>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=40)

Epoch 41/200

Epoch 41: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-041.ckpt
606/606 - 384s - loss: 0.1581 - mse: 0.1581 - val_loss: 0.2086 - val_mse: 0.2086 - 384s/epoch - 633ms/step
Epoch 42/200

Epoch 42: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-042.ckpt
606/606 - 317s - loss: 0.1563 - mse: 0.1563 - val_loss: 0.1553 - val_mse: 0.1553 - 317s/epoch - 524ms/step
Epoch 43/200

Epoch 43: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-043.ckpt
606/606 - 317s - loss: 0.1558 - mse: 0.1558 - val_loss: 0.2043 - val_mse: 0.2043 - 317s/epoch - 524ms/step
Epoch 44/200

Epoch 44: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-044.ckpt
606/606 - 336s - loss: 0.1551 - mse: 0.1551 - val_loss: 0.1529 - val_mse: 0.1529 - 336s/epoch - 554ms/step
Epoch 45/200

Epoch 45: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-045.ckpt
606/606 - 336s - loss: 0.1517 - mse: 0.1517 - val_loss: 0.1748 - val_mse: 0.1748 - 336s/epoch - 554ms/step
Epoch 46/200

Epoch 46: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-046.ckpt
606/606 - 317s - loss: 0.1524 - mse: 0.1524 - val_loss: 0.1287 - val_mse: 0.1287 - 317s/epoch - 523ms/step
Epoch 47/200

Epoch 47: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-047.ckpt
606/606 - 317s - loss: 0.1515 - mse: 0.1515 - val_loss: 0.1539 - val_mse: 0.1539 - 317s/epoch - 523ms/step
Epoch 48/200

Epoch 48: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-048.ckpt
606/606 - 336s - loss: 0.1496 - mse: 0.1496 - val_loss: 0.1356 - val_mse: 0.1356 - 336s/epoch - 554ms/step
Epoch 49/200

Epoch 49: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-049.ckpt
606/606 - 336s - loss: 0.1493 - mse: 0.1493 - val_loss: 0.1539 - val_mse: 0.1539 - 336s/epoch - 554ms/step
Epoch 50/200

Epoch 50: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-050.ckpt
606/606 - 336s - loss: 0.1483 - mse: 0.1483 - val_loss: 0.1276 - val_mse: 0.1276 - 336s/epoch - 554ms/step
Epoch 51/200

Epoch 51: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-051.ckpt
606/606 - 336s - loss: 0.1465 - mse: 0.1465 - val_loss: 0.1444 - val_mse: 0.1444 - 336s/epoch - 554ms/step
Epoch 52/200

Epoch 52: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-052.ckpt
606/606 - 336s - loss: 0.1483 - mse: 0.1483 - val_loss: 0.1779 - val_mse: 0.1779 - 336s/epoch - 554ms/step
Epoch 53/200

Epoch 53: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-053.ckpt
606/606 - 317s - loss: 0.1479 - mse: 0.1479 - val_loss: 0.1443 - val_mse: 0.1443 - 317s/epoch - 523ms/step
Epoch 54/200

In [ ]:
wieght='/content/drive/MyDrive/image/porosity_filtering/learnin_rate/training_model_weights/cp-108.ckpt'
model.load_weights(wieght)

In [ ]:
history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=108)

Epoch 109/200

<ipython-input-23-54cce96ec699>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=108)

Epoch 109: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-109.ckpt
606/606 - 376s - loss: 0.1306 - mse: 0.1306 - val_loss: 0.1127 - val_mse: 0.1127 - 376s/epoch - 621ms/step
Epoch 110/200

Epoch 110: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-110.ckpt
606/606 - 329s - loss: 0.1304 - mse: 0.1304 - val_loss: 0.1064 - val_mse: 0.1064 - 329s/epoch - 542ms/step
Epoch 111/200

Epoch 111: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-111.ckpt
606/606 - 329s - loss: 0.1298 - mse: 0.1298 - val_loss: 0.1108 - val_mse: 0.1108 - 329s/epoch - 543ms/step
Epoch 112/200

Epoch 112: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-112.ckpt
606/606 - 309s - loss: 0.1292 - mse: 0.1292 - val_loss: 0.1158 - val_mse: 0.1158 - 309s/epoch - 510ms/step
Epoch 113/200

Epoch 113: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-113.ckpt
606/606 - 328s - loss: 0.1296 - mse: 0.1296 - val_loss: 0.1155 - val_mse: 0.1155 - 328s/epoch - 541ms/step
Epoch 114/200

In [ ]:
wieght='/content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-115.ckpt'
model.load_weights(wieght)

In [ ]:
history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=115)

Epoch 116/200

<ipython-input-23-4dbef963fa09>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=115)

Epoch 116: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-116.ckpt
606/606 - 363s - loss: 0.1283 - mse: 0.1283 - val_loss: 0.1120 - val_mse: 0.1120 - 363s/epoch - 599ms/step
Epoch 117/200

Epoch 117: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-117.ckpt
606/606 - 310s - loss: 0.1293 - mse: 0.1293 - val_loss: 0.1075 - val_mse: 0.1075 - 310s/epoch - 512ms/step
Epoch 118/200

Epoch 118: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-118.ckpt
606/606 - 310s - loss: 0.1285 - mse: 0.1285 - val_loss: 0.1046 - val_mse: 0.1046 - 310s/epoch - 511ms/step
Epoch 119/200

Epoch 119: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-119.ckpt
606/606 - 329s - loss: 0.1291 - mse: 0.1291 - val_loss: 0.1075 - val_mse: 0.1075 - 329s/epoch - 543ms/step
Epoch 120/200

Epoch 120: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-120.ckpt
606/606 - 310s - loss: 0.1283 - mse: 0.1283 - val_loss: 0.1198 - val_mse: 0.1198 - 310s/epoch - 512ms/step
Epoch 121/200

Epoch 121: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-121.ckpt
606/606 - 309s - loss: 0.1278 - mse: 0.1278 - val_loss: 0.1066 - val_mse: 0.1066 - 309s/epoch - 511ms/step
Epoch 122/200

Epoch 122: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-122.ckpt
606/606 - 329s - loss: 0.1288 - mse: 0.1288 - val_loss: 0.1086 - val_mse: 0.1086 - 329s/epoch - 543ms/step
Epoch 123/200

Epoch 123: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-123.ckpt
606/606 - 310s - loss: 0.1286 - mse: 0.1286 - val_loss: 0.1105 - val_mse: 0.1105 - 310s/epoch - 512ms/step
Epoch 124/200

Epoch 124: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-124.ckpt
606/606 - 310s - loss: 0.1269 - mse: 0.1269 - val_loss: 0.1124 - val_mse: 0.1124 - 310s/epoch - 511ms/step
Epoch 125/200

Epoch 125: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-125.ckpt
606/606 - 309s - loss: 0.1283 - mse: 0.1283 - val_loss: 0.1082 - val_mse: 0.1082 - 309s/epoch - 511ms/step
Epoch 126/200

Epoch 126: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-126.ckpt
606/606 - 310s - loss: 0.1289 - mse: 0.1289 - val_loss: 0.1065 - val_mse: 0.1065 - 310s/epoch - 511ms/step
Epoch 127/200

Epoch 127: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-127.ckpt
606/606 - 310s - loss: 0.1277 - mse: 0.1277 - val_loss: 0.1074 - val_mse: 0.1074 - 310s/epoch - 511ms/step
Epoch 128/200

Epoch 128: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-128.ckpt
606/606 - 310s - loss: 0.1284 - mse: 0.1284 - val_loss: 0.1161 - val_mse: 0.1161 - 310s/epoch - 511ms/step
Epoch 129/200

In [ ]:
wieght='/content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-130.ckpt'
model.load_weights(wieght)

In [ ]:
history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=130)

Epoch 131/200

<ipython-input-23-94637ded49ca>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=130)

Epoch 131: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-131.ckpt
606/606 - 356s - loss: 0.1276 - mse: 0.1276 - val_loss: 0.1105 - val_mse: 0.1105 - 356s/epoch - 587ms/step
Epoch 132/200

Epoch 132: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-132.ckpt
606/606 - 302s - loss: 0.1273 - mse: 0.1273 - val_loss: 0.1069 - val_mse: 0.1069 - 302s/epoch - 498ms/step
Epoch 133/200

Epoch 133: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-133.ckpt
606/606 - 302s - loss: 0.1271 - mse: 0.1271 - val_loss: 0.1139 - val_mse: 0.1139 - 302s/epoch - 498ms/step
Epoch 134/200

Epoch 134: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-134.ckpt
606/606 - 302s - loss: 0.1275 - mse: 0.1275 - val_loss: 0.1127 - val_mse: 0.1127 - 302s/epoch - 498ms/step
Epoch 135/200

Epoch 135: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-135.ckpt
606/606 - 303s - loss: 0.1273 - mse: 0.1273 - val_loss: 0.1055 - val_mse: 0.1055 - 303s/epoch - 500ms/step
Epoch 136/200

Epoch 136: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-136.ckpt
606/606 - 301s - loss: 0.1268 - mse: 0.1268 - val_loss: 0.1191 - val_mse: 0.1191 - 301s/epoch - 497ms/step
Epoch 137/200

Epoch 137: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-137.ckpt
606/606 - 303s - loss: 0.1272 - mse: 0.1272 - val_loss: 0.1036 - val_mse: 0.1036 - 303s/epoch - 499ms/step
Epoch 138/200

Epoch 138: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-138.ckpt
606/606 - 302s - loss: 0.1272 - mse: 0.1272 - val_loss: 0.1046 - val_mse: 0.1046 - 302s/epoch - 498ms/step
Epoch 139/200

Epoch 139: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-139.ckpt
606/606 - 301s - loss: 0.1267 - mse: 0.1267 - val_loss: 0.1076 - val_mse: 0.1076 - 301s/epoch - 497ms/step
Epoch 140/200

Epoch 140: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-140.ckpt
606/606 - 303s - loss: 0.1268 - mse: 0.1268 - val_loss: 0.1027 - val_mse: 0.1027 - 303s/epoch - 500ms/step
Epoch 141/200

Epoch 141: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-141.ckpt
606/606 - 301s - loss: 0.1263 - mse: 0.1263 - val_loss: 0.1036 - val_mse: 0.1036 - 301s/epoch - 497ms/step
Epoch 142/200

Epoch 142: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-142.ckpt
606/606 - 303s - loss: 0.1268 - mse: 0.1268 - val_loss: 0.1066 - val_mse: 0.1066 - 303s/epoch - 500ms/step
Epoch 143/200

Epoch 143: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-143.ckpt
606/606 - 302s - loss: 0.1266 - mse: 0.1266 - val_loss: 0.1040 - val_mse: 0.1040 - 302s/epoch - 498ms/step
Epoch 144/200

Epoch 144: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-144.ckpt
606/606 - 303s - loss: 0.1264 - mse: 0.1264 - val_loss: 0.1078 - val_mse: 0.1078 - 303s/epoch - 499ms/step
Epoch 145/200

Epoch 145: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-145.ckpt
606/606 - 302s - loss: 0.1254 - mse: 0.1254 - val_loss: 0.1319 - val_mse: 0.1319 - 302s/epoch - 499ms/step
Epoch 146/200

Epoch 146: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-146.ckpt
606/606 - 301s - loss: 0.1260 - mse: 0.1260 - val_loss: 0.1027 - val_mse: 0.1027 - 301s/epoch - 497ms/step
Epoch 147/200

Epoch 147: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-147.ckpt
606/606 - 301s - loss: 0.1272 - mse: 0.1272 - val_loss: 0.1086 - val_mse: 0.1086 - 301s/epoch - 497ms/step
Epoch 148/200

Epoch 148: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-148.ckpt
606/606 - 303s - loss: 0.1257 - mse: 0.1257 - val_loss: 0.1047 - val_mse: 0.1047 - 303s/epoch - 500ms/step
Epoch 149/200

Epoch 149: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-149.ckpt
606/606 - 303s - loss: 0.1260 - mse: 0.1260 - val_loss: 0.1083 - val_mse: 0.1083 - 303s/epoch - 499ms/step
Epoch 150/200

Epoch 150: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-150.ckpt
606/606 - 301s - loss: 0.1264 - mse: 0.1264 - val_loss: 0.1044 - val_mse: 0.1044 - 301s/epoch - 497ms/step
Epoch 151/200

Epoch 151: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-151.ckpt
606/606 - 303s - loss: 0.1269 - mse: 0.1269 - val_loss: 0.1022 - val_mse: 0.1022 - 303s/epoch - 499ms/step
Epoch 152/200

Epoch 152: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-152.ckpt
606/606 - 301s - loss: 0.1254 - mse: 0.1254 - val_loss: 0.1014 - val_mse: 0.1014 - 301s/epoch - 497ms/step
Epoch 153/200

Epoch 153: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-153.ckpt
606/606 - 303s - loss: 0.1256 - mse: 0.1256 - val_loss: 0.1054 - val_mse: 0.1054 - 303s/epoch - 499ms/step
Epoch 154/200

Epoch 154: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-154.ckpt
606/606 - 301s - loss: 0.1263 - mse: 0.1263 - val_loss: 0.1075 - val_mse: 0.1075 - 301s/epoch - 497ms/step
Epoch 155/200

In [22]:
wieght='/content/drive/MyDrive/image/porosity_filtering/learnin_rate/training_model_weights/cp-180.ckpt'
model.load_weights(wieght)

In [ ]:
history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=180)

Epoch 181/200

<ipython-input-23-d0589dc395fd>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=180)

Epoch 181: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-181.ckpt
606/606 - 406s - loss: 0.1246 - mse: 0.1246 - val_loss: 0.1025 - val_mse: 0.1025 - 406s/epoch - 670ms/step
Epoch 182/200

Epoch 182: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-182.ckpt
606/606 - 340s - loss: 0.1255 - mse: 0.1255 - val_loss: 0.1009 - val_mse: 0.1009 - 340s/epoch - 561ms/step
Epoch 183/200

Epoch 183: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-183.ckpt
606/606 - 321s - loss: 0.1237 - mse: 0.1237 - val_loss: 0.1020 - val_mse: 0.1020 - 321s/epoch - 530ms/step
Epoch 184/200

Epoch 184: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-184.ckpt
606/606 - 321s - loss: 0.1253 - mse: 0.1253 - val_loss: 0.1083 - val_mse: 0.1083 - 321s/epoch - 529ms/step
Epoch 185/200

Epoch 185: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-185.ckpt
606/606 - 339s - loss: 0.1246 - mse: 0.1246 - val_loss: 0.1014 - val_mse: 0.1014 - 339s/epoch - 560ms/step
Epoch 186/200

Epoch 186: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-186.ckpt
606/606 - 340s - loss: 0.1249 - mse: 0.1249 - val_loss: 0.1036 - val_mse: 0.1036 - 340s/epoch - 561ms/step
Epoch 187/200

Epoch 187: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-187.ckpt
606/606 - 340s - loss: 0.1247 - mse: 0.1247 - val_loss: 0.1027 - val_mse: 0.1027 - 340s/epoch - 561ms/step
Epoch 188/200

Epoch 188: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-188.ckpt
606/606 - 340s - loss: 0.1236 - mse: 0.1236 - val_loss: 0.1025 - val_mse: 0.1025 - 340s/epoch - 561ms/step
Epoch 189/200

In [22]:
wieght='/content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-190.ckpt'
model.load_weights(wieght)

In [ ]:
history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=190)

<ipython-input-23-b0b03c26e90b>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=190)

Epoch 191/200

Epoch 191: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-191.ckpt
606/606 - 369s - loss: 0.1246 - mse: 0.1246 - val_loss: 0.1020 - val_mse: 0.1020 - 369s/epoch - 609ms/step
Epoch 192/200

Epoch 192: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-192.ckpt
606/606 - 338s - loss: 0.1241 - mse: 0.1241 - val_loss: 0.1030 - val_mse: 0.1030 - 338s/epoch - 558ms/step
Epoch 193/200

Epoch 193: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-193.ckpt
606/606 - 338s - loss: 0.1234 - mse: 0.1234 - val_loss: 0.1309 - val_mse: 0.1309 - 338s/epoch - 557ms/step
Epoch 194/200

Epoch 194: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-194.ckpt
606/606 - 318s - loss: 0.1243 - mse: 0.1243 - val_loss: 0.1106 - val_mse: 0.1106 - 318s/epoch - 524ms/step
Epoch 195/200

Epoch 195: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-195.ckpt
606/606 - 337s - loss: 0.1236 - mse: 0.1236 - val_loss: 0.1048 - val_mse: 0.1048 - 337s/epoch - 557ms/step
Epoch 196/200

Epoch 196: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-196.ckpt
606/606 - 338s - loss: 0.1237 - mse: 0.1237 - val_loss: 0.2086 - val_mse: 0.2086 - 338s/epoch - 557ms/step
Epoch 197/200

Epoch 197: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-197.ckpt
606/606 - 318s - loss: 0.1238 - mse: 0.1238 - val_loss: 7.7054 - val_mse: 7.7054 - 318s/epoch - 524ms/step
Epoch 198/200

Epoch 198: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-198.ckpt
606/606 - 317s - loss: 0.1250 - mse: 0.1250 - val_loss: 0.2855 - val_mse: 0.2855 - 317s/epoch - 523ms/step
Epoch 199/200

Epoch 199: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-199.ckpt
606/606 - 317s - loss: 0.1243 - mse: 0.1243 - val_loss: 5.0829 - val_mse: 5.0829 - 317s/epoch - 524ms/step
Epoch 200/200

Epoch 200: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-200.ckpt
606/606 - 337s - loss: 0.1236 - mse: 0.1236 - val_loss: 0.5809 - val_mse: 0.5809 - 337s/epoch - 556ms/step